#' ---
#' title: <center><b>Markdown document from&colon;</b><br>Traces of Genetic but Not Epigenetic Adaptation in the Invasive Goldenrod _Solidago canadensis_ Despite the Absence of Population Structure</center>
#' pagetitle: RMarkdown document from:&nbsp;Eckert&nbsp;et&nbsp;al.&nbsp;(2022)
#' subtitle: <center>doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.3389/fevo.2022.856453">10.3389/fevo.2022.856453</a></center>
#' author: <center>Eckert, S., Herden, J., Stift, M., Durka, W., van Kleunen, M., & Joshi, J.</center>
#' date: <center>`r Sys.Date()`</center>
#' abstract: <p align="justify">This RMarkdown script belongs
#'   to a series of scripts generated by Silvia Eckert as part of
#'   the statistical analysis for the above-mentioned manuscript.
#'   The data underlying the applied R code can be found in the ZENODO
#'   repository and contains genetic (AFLP) and epigenetic (MSAP) markers
#'   from offspring of 25 _Solidago canadensis_ populations sampled along a
#'   latitudinal gradient in Central Europe. This particular RMarkdown script
#'   applies calculation of the log-fold change and heatmaps on MSAP datasets. <b>Please cite this
#'   script as follows:</b></p><br><p>Eckert, S., Herden, J.,
#'   Stift, M., Durka, W., van Kleunen, M., & Joshi, J. (2022). Data From&colon;
#'   Traces of Genetic but Not Epigenetic Adaptation in the Invasive
#'   Goldenrod _Solidago canadensis_ Despite the Absence of Population
#'   Structure. _Zenodo_. doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.5281/zenodo.6388135">10.5281/zenodo.6388135</a></center></p>
#' geometry: margin=2cm
#' output:
#'   html_document:
#'      code_folding: show
#'      keep_md: FALSE
#'      theme: flatly
#'      highlight: textmate
#'      df_print: paged
#'      toc: true
#'      toc_float: true
#' ---
#' 

#'
#'```{r setup, include = FALSE}
#'knitr::opts_chunk$set(eval=FALSE, cache=FALSE, warning=FALSE)
#'```

#' # Packages
#' <a href="#top">Back to top</a>
#+ project_packages, results='hide', message=FALSE, warning=FALSE
########### packages ...................... ####
# install.packages("name_of_package") # install necessary packages
# install knitr to save this script as html output using RStudio with Ctrl+Shift+K (Windows & Linux) or Command+Shift+K (macOS)
# install.packages("knitr") 
# getwd() # get current working directory
# setwd() # set working directory
# create folder for datasets to be stored to get this RMarkdown script running
dir.create("./data",
           showWarnings=F)
# add necessary libraries
library(ade4)
library(tibble)
library(ggplot2)
library(cowplot)
library(ggpubr)
library(reshape2)
library(tibble)
library(ggplot2)
library(ggpattern)
library(reshape2)
library(data.table)
library(dplyr)
library(data.table)

#' # Load data
#' <a href="#top">Back to top</a>
#+ project_load.data
########### load data ....................... ####
# load AFLP/MSAP data
source("RMarkdown_Eckert_et_al_2022_loadMolecularData.R")

#' ## MSAP-n
#' <a href="#top">Back to top</a>
#+ project_load.MSAPn
######## MSAP-n ####
# subset to maternal lines that are present in both control and zebularine group
MSAPn$pop_ind <- paste0(MSAPn$populationID,"_",MSAPn$maternal_line)
# subset
MSAPn_C <- MSAPn[MSAPn$treatment == "CON",]; tibble(MSAPn_C)
MSAPn_Z <- MSAPn[MSAPn$treatment == "ZEB",]; tibble(MSAPn_Z)
MSAPn_subset <- tibble(MSAPn[MSAPn_Z$pop_ind %in%
                                 intersect(MSAPn_C$pop_ind,
                                           MSAPn_Z$pop_ind),]); MSAPn_subset

#' ## MSAP-m
#' <a href="#top">Back to top</a>
#+ project_load.MSAPm
######## MSAP-m ####
# subset to maternal lines that are present in both control and zebularine group
MSAPm$pop_ind <- paste0(MSAPm$populationID,"_",MSAPm$maternal_line)
# subset
MSAPm_C <- MSAPm[MSAPm$treatment == "CON",]; tibble(MSAPm_C)
MSAPm_Z <- MSAPm[MSAPm$treatment == "ZEB",]; tibble(MSAPm_Z)
MSAPm_subset <- tibble(MSAPm[MSAPm_Z$pop_ind %in%
                                 intersect(MSAPm_C$pop_ind,
                                           MSAPm_Z$pop_ind),]); MSAPm_subset

#' # Heatmaps
#' <a href="#top">Back to top</a>
#+ project_heatmaps
########### Heatmaps ...................... ####
#' ## MSAP-m
#' <a href="#top">Back to top</a>
#+ project_heatmaps.MSAPm
########### MSAP-m ####
# melt data (remove pop_ind factor from table)
MSAPm_melt <- reshape2::melt(MSAPm_subset[,-c(1:3,5:6,196)],
                              c("populationID",
                                "treatment",
                                "maternal_line")); tibble(MSAPm_melt)
# replace zeros with NA (= locus not present)
MSAPm_melt[MSAPm_melt == 0] <- NA
# create pop_ind variable
MSAPm_melt$pop_ind <- paste0(MSAPm_melt$populationID,"_",
                              MSAPm_melt$maternal_line); tibble(MSAPm_melt)
# remove column of maternal lines
MSAPm_melt$maternal_line <- NULL
# shown: populationID, treatment, variable=locus, value=binary, pop_ind
tibble(MSAPm_melt)
# trim to complete cases where pop_ind is present in both treatment levels
MSAPm_trimmed <- MSAPm_melt %>%
  tidyr::complete(treatment,
                  pop_ind=unique(pop_ind)) %>%
  group_by(treatment) %>%
  ungroup(); MSAPm_trimmed
# remove rows with NA
MSAPm_trimmed <- MSAPm_trimmed[complete.cases(MSAPm_trimmed),]; MSAPm_trimmed
# aggregate the counts of loci per population and treatment
MSAPm_agg <- aggregate(value ~ populationID +
                          treatment +
                          variable,
                        data=MSAPm_trimmed,
                        FUN=length); tibble(MSAPm_agg)
# change format from data frame to data table
MSAPm_agg <- data.table(MSAPm_agg); MSAPm_agg; tail(MSAPm_agg)
# calculate fold change for each locus per population and treatment
MSAPm_log2FC <- MSAPm_agg[order(treatment),
                            .(fold_change=value[2]/value[1]),
                            by=.(populationID,
                                 variable)]; tibble(MSAPm_log2FC)
MSAPm_log2FC$log2FC <- log2(MSAPm_log2FC$fold_change); tibble(MSAPm_log2FC)
# again reduce to complete cases
MSAPm_log2FC <- MSAPm_log2FC[complete.cases(MSAPm_log2FC),]
# number of loci with 4-fold decreased presence
MSAPm_desc <- MSAPm_log2FC[MSAPm_log2FC$log2FC <= -2,]
length(unique(MSAPm_desc$variable))
# number of loci with 4-fold increased presence
MSAPm_asc <- MSAPm_log2FC[MSAPm_log2FC$log2FC >= 2,]
length(unique(MSAPm_asc$variable))
# total number of loci present in all individuals (loci for who fold-change could be calculated)
MSAPm_nloc <- length(unique(MSAPm_log2FC$variable)); MSAPm_nloc
# percentage of 4-fold decreased loci
100/MSAPm_nloc * length(unique(MSAPm_desc$variable))
# percentage of 4-fold increased loci
100/MSAPm_nloc * length(unique(MSAPm_asc$variable))
# plot heatmap
MSAPm_heatmap <- ggplot(MSAPm_log2FC,
                         aes(y=variable,
                             x=rev(populationID))) +
  geom_tile(aes(fill=log2FC),
            colour="transparent") +
  scale_x_discrete(position="top") +
  scale_fill_gradient2(low="darkblue",
                       mid="transparent",
                       high="red") +
  labs(y="MSAP-m loci",
       x="Populations",
       fill=expression(paste("log"["2"]*"(fold change)"))) +
  theme_cowplot()+
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.x=element_text(size=9),
        panel.border=element_rect(colour="black",
                                    fill="transparent"),
        panel.background=element_rect(fill="transparent"),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        legend.position="none"); MSAPm_heatmap

#' ## MSAP-n
#' <a href="#top">Back to top</a>
#+ project_heatmaps.MSAPn
########### MSAP-n ####
# to remove
names(MSAPn_subset[,c(1:3,5:6,191)])
# melt data
MSAPn_melt <- reshape2::melt(MSAPn_subset[,-c(1:3,5:6,191)],
                              c("populationID",
                                "treatment",
                                "maternal_line")); tibble(MSAPn_melt)
# replace zeros with NA (= locus not present)
MSAPn_melt[MSAPn_melt == 0] <- NA; tibble(MSAPn_melt)
# create pop_ind variable
MSAPn_melt$pop_ind <- paste0(MSAPn_melt$populationID,"_",
                              MSAPn_melt$maternal_line); tibble(MSAPn_melt)
# remove column of maternal lines
MSAPn_melt$maternal_line <- NULL
# shown: populationID, treatment, variable=locus, value=binary, pop_ind
tibble(MSAPn_melt)
# trim to complete cases where pop_ind is present in both treatment levels
MSAPn_trimmed <- MSAPn_melt %>%
  tidyr::complete(treatment,
                  pop_ind=unique(pop_ind)) %>%
  group_by(treatment) %>%
  ungroup(); MSAPn_trimmed
# remove rows with NA
MSAPn_trimmed <- MSAPn_trimmed[complete.cases(MSAPn_trimmed),]; MSAPn_trimmed
# aggregate the counts of loci per population and treatment
MSAPn_agg <- aggregate(value ~ populationID +
                          treatment +
                          variable,
                        data=MSAPn_trimmed,
                        FUN=length); tibble(MSAPn_agg)
# change format from data frame to data table
MSAPn_agg <- data.table(MSAPn_agg); MSAPn_agg; tail(MSAPn_agg)
# calculate fold change for each locus per population and treatment
MSAPn_log2FC <- MSAPn_agg[order(treatment),
                            .(fold_change=value[2]/value[1]),
                            by=.(populationID,
                                 variable)]; tibble(MSAPn_log2FC)
MSAPn_log2FC$log2FC <- log2(MSAPn_log2FC$fold_change); tibble(MSAPn_log2FC)
# again reduce to complete cases
MSAPn_log2FC <- MSAPn_log2FC[complete.cases(MSAPn_log2FC),]
# number of loci with 4-fold decreased presence
MSAPn_desc <- MSAPn_log2FC[MSAPn_log2FC$log2FC <= -2,]
length(unique(MSAPn_desc$variable))
# number of loci with 4-fold increased presence
MSAPn_asc <- MSAPn_log2FC[MSAPn_log2FC$log2FC >= 2,]
length(unique(MSAPn_asc$variable))
# total number of loci present in all individuals (loci for who fold-change could be calculated)
MSAPn_nloc <- length(unique(MSAPn_log2FC$variable)); MSAPn_nloc
# percentage of 4-fold decreased loci
100/MSAPn_nloc * length(unique(MSAPn_desc$variable))
# percentage of 4-fold increased loci
100/MSAPn_nloc * length(unique(MSAPn_asc$variable))
# plot heatmap
MSAPn_heatmap <- ggplot(MSAPn_log2FC,
                         aes(y=variable,
                             x=rev(populationID))) +
  geom_tile(aes(fill=log2FC),
            colour="transparent") +
  scale_x_discrete(position="top") +
  scale_fill_gradient2(low="darkblue",
                       mid="transparent",
                       high="red") +
  labs(y="MSAP-n loci",
       x="Populations",
       fill=expression(paste("log"["2"]*"FC"))) +
  guides(fill=guide_colourbar(barwidth=0.5,
                                barheight=20)) +
  theme_cowplot()+
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.x=element_text(size=9),
        panel.border=element_rect(colour="black",
                                    fill="transparent"),
        panel.background=element_rect(fill="transparent"),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        legend.position="right"); MSAPn_heatmap

#' # Boxplots
#' <a href="#top">Back to top</a>
#+ project_heatmaps.boxplots
########### Boxplots ......................... ####
#' ## MSAP-m
#' <a href="#top">Back to top</a>
#+ project_heatmaps.boxplots_msapm
########### MSAP-m ####
# 4-fold decrease per population
MSAPm_decr_logFC2_agg <- aggregate(MSAPm_desc,
                                    by=list(MSAPm_desc$populationID),
                                    FUN=length); tibble(MSAPm_decr_logFC2_agg)
# add logFC information
MSAPm_decr_logFC2_agg$logFC_change <- ">=|2|"; tibble(MSAPm_decr_logFC2_agg)
# 2-fold decrease per population
MSAPm_decr_logFC1_agg <- aggregate(MSAPm_decr,
                                    by=list(MSAPm_decr$populationID),
                                    FUN=length); tibble(MSAPm_decr_logFC1_agg)
# add logFC information
MSAPm_decr_logFC1_agg$logFC_change <- ">=|1|"; tibble(MSAPm_decr_logFC1_agg)
# merge
MSAPm_decr_agg <- rbind(MSAPm_decr_logFC1_agg,
                         MSAPm_decr_logFC2_agg); tibble(MSAPm_decr_agg)
# add change factor
MSAPm_decr_agg$variation <- "down"; tibble(MSAPm_decr_agg)
# 4-fold increase per population
MSAPm_incr_logFC2_agg <- aggregate(MSAPm_asc,
                                    by=list(MSAPm_asc$populationID),
                                    FUN=length); tibble(MSAPm_incr_logFC2_agg)
# add logFC information
MSAPm_incr_logFC2_agg$logFC_change <- ">=|2|"; tibble(MSAPm_incr_logFC2_agg)
# 2-fold decrease per population
MSAPm_incr_logFC1_agg <- aggregate(MSAPm_incr,
                                    by=list(MSAPm_incr$populationID),
                                    FUN=length); tibble(MSAPm_incr_logFC1_agg)
# add logFC information
MSAPm_incr_logFC1_agg$logFC_change <- ">=|1|"; tibble(MSAPm_incr_logFC1_agg)
# merge
MSAPm_incr_agg <- rbind(MSAPm_incr_logFC1_agg,
                         MSAPm_incr_logFC2_agg); tibble(MSAPm_incr_agg)
# add change factor
MSAPm_incr_agg$variation <- "up"; tibble(MSAPm_incr_agg)
# merge all
MSAPm_frec_agg <- rbind(MSAPm_decr_agg,
                         MSAPm_incr_agg); tibble(MSAPm_frec_agg)
names(MSAPm_frec_agg)[1] <- "populationID"
names(MSAPm_frec_agg)[2] <- "counts"
MSAPm_frec_agg$logFC_change <- as.factor(MSAPm_frec_agg$logFC_change)
MSAPm_frec_agg$variation <- as.factor(MSAPm_frec_agg$variation)
# remove unnecessary columns
MSAPm_frec_agg$variable <- NULL
MSAPm_frec_agg$fold_change <- NULL
MSAPm_frec_agg$log2FC <- NULL
tibble(MSAPm_frec_agg)
# add populations with no changes detectable above/below threshold
MSAPm_frec_agg$populationID
# no fold change at all detected in the following populations:
# missing downs in |1|: 15,17,23
# missing downs in |1|: 2,11,14:19,22:23,25
# missing ups in |2|: 8,12,21
# missing ups in |2|: 1:14,19,21:25
MSAPm_noChange_pops <- data.frame(populationID=c(15,17,23, # >|1|
                                                    2,11,14:19,22:23,25, # >|2|
                                                    8,12,21, # >|1|
                                                    1:14,19,21:25), # >|2|
                                   counts=rep(0,37),
                                   logFC_change=c(rep(">=|1|",3),
                                                    rep(">=|2|",11),
                                                    rep(">=|1|",3),
                                                    rep(">=|2|",20)),
                                   variation=c(rep("down",14),
                                                 rep("up",23))); MSAPm_noChange_pops
# combine
MSAPm_frec_agg <- rbind(MSAPm_frec_agg,
                        MSAPm_noChange_pops)
# sort
MSAPm_frec_agg <- MSAPm_frec_agg[with(MSAPm_frec_agg,
                                      order(variation,
                                            logFC_change,
                                            populationID)),]
MSAPm_frec_agg; MSAPm_frec_agg$populationID # check
# average values
aggregate(counts ~ variation +
            logFC_change,
          data=MSAPm_frec_agg,
          FUN=mean)
# boxplot
MSAPm_frec_agg_boxplot <- ggplot(data=MSAPm_frec_agg,
                                  aes(x=logFC_change,
                                      y=counts,
                                      fill=variation)) +
  geom_boxplot() +
  scale_x_discrete(labels=c(">=|1|"=expression(''>="|1|"),
                            ">=|2|"=expression(''>="|2|"))) +
  scale_fill_manual(values=c("slateblue","red")) +
  guides(fill=guide_legend(expression(paste(log[2],"FC")))) +
  labs(x=NULL,
       y="Varying loci / population",
       fill=expression(paste(log[2]*"FC")),
       title="MSAP-m") +
  theme_cowplot() +
  theme(legend.position="top",
        panel.border=element_rect(colour="black",
                                    fill=NA)); MSAPm_frec_agg_boxplot

#' ## MSAP-n
#' <a href="#top">Back to top</a>
#+ project_heatmaps.boxplots_MSAPn
########### MSAP-n ####
# 4-fold decrease per population
MSAPn_decr_logFC2_agg <- aggregate(MSAPn_desc,
                                    by=list(MSAPn_desc$populationID),
                                    FUN=length); tibble(MSAPn_decr_logFC2_agg)
# add logFC information
MSAPn_decr_logFC2_agg$logFC_change <- ">=|2|"; tibble(MSAPn_decr_logFC2_agg)
# 2-fold decrease per population
MSAPn_decr_logFC1_agg <- aggregate(MSAPn_decr,
                                    by=list(MSAPn_decr$populationID),
                                    FUN=length); tibble(MSAPn_decr_logFC1_agg)
# add logFC information
MSAPn_decr_logFC1_agg$logFC_change <- ">=|1|"; tibble(MSAPn_decr_logFC1_agg)
# merge
MSAPn_decr_agg <- rbind(MSAPn_decr_logFC1_agg,
                         MSAPn_decr_logFC2_agg); tibble(MSAPn_decr_agg)
# add change factor
MSAPn_decr_agg$variation <- "down"; tibble(MSAPn_decr_agg)
# 4-fold increase per population
MSAPn_incr_logFC2_agg <- aggregate(MSAPn_asc,
                                    by=list(MSAPn_asc$populationID),
                                    FUN=length); tibble(MSAPn_incr_logFC2_agg)
# add logFC information
MSAPn_incr_logFC2_agg$logFC_change <- ">=|2|"; tibble(MSAPn_incr_logFC2_agg)
# 2-fold decrease per population
MSAPn_incr_logFC1_agg <- aggregate(MSAPn_incr,
                                    by=list(MSAPn_incr$populationID),
                                    FUN=length); tibble(MSAPn_incr_logFC1_agg)
# add logFC information
MSAPn_incr_logFC1_agg$logFC_change <- ">=|1|"; tibble(MSAPn_incr_logFC1_agg)
# merge
MSAPn_incr_agg <- rbind(MSAPn_incr_logFC1_agg,
                         MSAPn_incr_logFC2_agg); tibble(MSAPn_incr_agg)
# add change factor
MSAPn_incr_agg$variation <- "up"; tibble(MSAPn_incr_agg)
# merge all
MSAPn_frec_agg <- rbind(MSAPn_decr_agg,
                         MSAPn_incr_agg); tibble(MSAPn_frec_agg)
names(MSAPn_frec_agg)[1] <- "populationID"
names(MSAPn_frec_agg)[2] <- "counts"
MSAPn_frec_agg$logFC_change <- as.factor(MSAPn_frec_agg$logFC_change)
MSAPn_frec_agg$variation <- as.factor(MSAPn_frec_agg$variation)
# remove unnecessary columns
MSAPn_frec_agg$variable <- NULL
MSAPn_frec_agg$fold_change <- NULL
MSAPn_frec_agg$log2FC <- NULL
tibble(MSAPn_frec_agg)
# add populations with no changes detectable above/below threshold
MSAPn_frec_agg$populationID
# no fold change at all detected in the following populations:
# missing downs in |1|: 15,18,19,23
# missing downs in |1|: 1:4,11,14:19,23,25
# missing ups in |2|: 6,8,12,21,23
# missing ups in |2|: 1:3,6:10,12,14:17,19,21:25
MSAPn_noChange_pops <- data.frame(populationID=c(15,18,19,23, # |1|
                                                    1:4,11,14:19,23,25, # |2|
                                                    6,8,12,21,23, # |1|
                                                    1:3,6:10,12,14:17,19,21:25), # |2|
                                   counts=rep(0,41),
                                   logFC_change=c(rep(">=|1|",4),
                                                    rep(">=|2|",13),
                                                    rep(">=|1|",5),
                                                    rep(">=|2|",19)),
                                   variation=c(rep("down",17),
                                                 rep("up",24))); MSAPn_noChange_pops
# combine
MSAPn_frec_agg <- rbind(MSAPn_frec_agg,
                        MSAPn_noChange_pops)
# sort
MSAPn_frec_agg <- MSAPn_frec_agg[with(MSAPn_frec_agg,
                                      order(variation,
                                            logFC_change,
                                            populationID)),]
MSAPn_frec_agg; MSAPn_frec_agg$populationID # check
# average values
aggregate(counts ~ variation +
            logFC_change,
          data=MSAPn_frec_agg,
          FUN=mean)
# boxplot
MSAPn_frec_agg_boxplot <- ggplot(data=MSAPn_frec_agg,
                                  aes(x=logFC_change,
                                      y=counts,
                                      fill=variation)) +
  geom_boxplot() +
  scale_x_discrete(labels=c(">=|1|"=expression(''>="|1|"),
                            ">=|2|"=expression(''>="|2|"))) +
  scale_fill_manual(values=c("slateblue","red1")) +
  guides(fill=guide_legend(expression(paste(log[2],"FC")))) +
  labs(x=expression(paste(log[2],"FC threshold")),
       y="Varying loci / population",
       fill=expression(paste(log[2]*"FC")),
       title="MSAP-n") +
  theme_cowplot() +
  theme(legend.position="none",
        panel.border=element_rect(colour="black",
                                    fill=NA)); MSAPn_frec_agg_boxplot
# combine boxplot figures
MSAP_frec_agg_combined <- plot_grid(MSAPm_frec_agg_boxplot,
                                    MSAPn_frec_agg_boxplot,
                                    labels=LETTERS[3:4],
                                    ncol=1); MSAP_frec_agg_combined

#' # Figure S6
#' <a href="#top">Back to top</a>
#+ project_heatmaps.figureS6
########### Figure S6 ......................... ####
# build the third column
third_column <- plot_grid(MSAPm_frec_agg_boxplot,
                          MSAPn_frec_agg_boxplot,
                          ncol=1,
                          labels=LETTERS[3:4],
                          label_size=20); third_column

# combine with heatmaps for final plot
heatmap_combi <- plot_grid(MSAPm_heatmap,
                           MSAPn_heatmap,
                           third_column,
                           ncol=3,
                           labels=c(LETTERS[1:2],''),
                           label_size=20,
                           rel_widths=c(1,1.2,0.6)) +
  theme(plot.margin=unit(c(0.5,0.5,0.5,0.5),"cm")); heatmap_combi
# save as png
ggsave(heatmap_combi,
       file="./data/FigureS6_Eckert_et_al_2022_heatmaps.png",
       dpi=300,
       width=12,
       height=8)
# save as tiff
ggsave(heatmap_combi,
       file="./data/FigureS6_Eckert_et_al_2022_heatmaps.TIFF",
       dpi=300,
       width=12,
       height=8,
       device=grDevices::tiff)

#' # Session info
#' <a href="#top">Back to top</a>
#+ Session.info
sessionInfo()
#' <a href="#top">Back to top</a>
######## Session info .................. ####