#' ---
#' title: <center><b>Markdown document from&colon;</b><br>Traces of Genetic but Not Epigenetic Adaptation in the Invasive Goldenrod _Solidago canadensis_ Despite the Absence of Population Structure</center>
#' pagetitle: RMarkdown document from:&nbsp;Eckert&nbsp;et&nbsp;al.&nbsp;(2022)
#' subtitle: <center>doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.3389/fevo.2022.856453">10.3389/fevo.2022.856453</a></center>
#' author: <center>Eckert, S., Herden, J., Stift, M., Durka, W., van Kleunen, M., & Joshi, J.</center>
#' date: <center>`r Sys.Date()`</center>
#' abstract: <p align="justify">This RMarkdown script belongs
#'   to a series of scripts generated by Silvia Eckert as part of
#'   the statistical analysis for the above-mentioned manuscript.
#'   The data underlying the applied R code can be found in the ZENODO
#'   repository and contains genetic (AFLP) and epigenetic (MSAP) markers
#'   from offspring of 25 _Solidago canadensis_ populations sampled along a
#'   latitudinal gradient in Central Europe. This particular RMarkdown script
#'   applies plotting of results from the BayeScEnv genome-scan results. <b>Please cite this
#'   script as follows:</b></p><br><p>Eckert, S., Herden, J.,
#'   Stift, M., Durka, W., van Kleunen, M., & Joshi, J. (2022). Data From&colon;
#'   Traces of Genetic but Not Epigenetic Adaptation in the Invasive
#'   Goldenrod _Solidago canadensis_ Despite the Absence of Population
#'   Structure. _Zenodo_. doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.5281/zenodo.6388135">10.5281/zenodo.6388135</a></center></p>
#' geometry: margin=2cm
#' output:
#'   html_document:
#'      code_folding: show
#'      keep_md: FALSE
#'      theme: flatly
#'      highlight: textmate
#'      df_print: paged
#'      toc: true
#'      toc_float: true
#' ---
#' 

#'
#'```{r setup, include = FALSE}
#'knitr::opts_chunk$set(eval=FALSE, cache=FALSE, warning=FALSE)
#'```

#' # Packages
#' <a href="#top">Back to top</a>
#+ project_packages, results='hide', message=FALSE, warning=FALSE
########### packages ...................... ####
# install.packages("name_of_package") # install necessary packages
# install knitr to save this script as html output using RStudio with Ctrl+Shift+K (Windows & Linux) or Command+Shift+K (macOS)
# install.packages("knitr") 
# getwd() # get current working directory
# setwd() # set working directory
# create folder for datasets to be stored to get this RMarkdown script running
dir.create("./data",
           showWarnings=F)
# add necessary libraries
library(tibble)
library(ggplot2) # plotting
library(cowplot) 
library(ggthemes)
library(ggpubr)
library(qvalue)
library(forcats)
library(adegenet)

#' # Load data
#' <a href="#top">Back to top</a>
#+ project_load.data
########### load data ....................... ####
#' ## Climate data
#+ project_load.Climate.Data
######## WorldClim 2.0 ####
ClimVar <- tibble(read.table("./data/Data_wc2_PopulationData.txt",
                             header=T)); ClimVar

#' ## AFLP
#' <a href="#top">Back to top</a> 
#+ project_load.AFLP
######## AFLP ####
# load AFLP/MSAP data
source("RMarkdown_Eckert_et_al_2022_loadMolecularData.R")
# transform to genind opject with all data
# presence/absence data (@type: PA)
AFLP.genind <- df2genind(AFLP[,-c(1:8)],
                         sep=",",
                         pop=AFLP$populationID,
                         ind=AFLP$uniqueID,
                         strata=AFLP[,c(2:8)],
                         ploidy=2,
                         type=c("PA")); AFLP.genind
# subset data to control plants only
AFLP_C <- AFLP[AFLP$treatment=="CON",]; dim(AFLP_C)
# presence/absence data
AFLP_C.genind <- df2genind(AFLP_C[,-c(1:8)],
                           sep=",",
                           pop=AFLP_C$populationID,
                           ind=AFLP_C$uniqueID,
                           strata=AFLP_C[,c(1:8)],
                           ploidy=2,
                           type=c("PA")); AFLP_C.genind
tibble(strata(AFLP_C.genind)) # strata

#' ## MSAP-u
#' <a href="#top">Back to top</a>
#+ project_load.MSAPu
######## MSAP-u ####
# transform to genind object
MSAPn.genind <- df2genind(MSAPn[,-c(1:8)],
                           sep=",",
                           pop=MSAPn$populationID,
                           ind=MSAPn$uniqueID,
                           strata=MSAPn[,c(1:8)],
                           ploidy=2,
                           type=c("PA")); MSAPn.genind
# subset to control plants
# presence/absence data (@type: PA)
MSAPn_C <- MSAPn[MSAPn$treatment=='CON',]; MSAPn_C; dim(MSAPn_C)
MSAPn_C.genind <- df2genind(MSAPn_C[,-c(1:8)],
                             sep=",",
                             pop=MSAPn_C$populationID,
                             ind=MSAPn_C$uniqueID,
                             strata=MSAPn_C[,c(1:8)],
                             ploidy=2,
                             type=c("PA")); MSAPn_C.genind
tibble(strata(MSAPn_C.genind)) # strata

#' ## MSAP-m
#' <a href="#top">Back to top</a>
#+ CANADENSIS-load.MSAPm
######## MSAP-m ####
# transform to genind object
MSAPm.genind <- df2genind(MSAPm[,-c(1:8)],
                           sep=",",
                           pop=MSAPm$populationID,
                           ind=MSAPm$uniqueID,
                           strata=MSAPm[,c(1:8)],
                           ploidy=2,
                           type=c("PA")); MSAPm.genind
# subset to control plants
MSAPm_C <- MSAPm[MSAPm$treatment=="CON",]; dim(MSAPm_C)
MSAPm_C.genind <- df2genind(MSAPm_C[,-c(1:8)],
                             sep=",",
                             pop=MSAPm_C$populationID,
                             ind=MSAPm_C$uniqueID,
                             strata=MSAPm_C[,c(1:8)],
                             ploidy=2,
                             type=c("PA")); MSAPm_C.genind
tibble(strata(MSAPm_C.genind)) # strata

#' # Environment variables
#' <a href="#top">Back to top</a>
#+ project_environment.data
########### transform data ................ ####
# PC1 and PC2 from climato-spatial PCA (including WorldClim-data, latidude, and MEMGENE variables)
ClimData <- tibble(read.table("./data/Data_PCA_WorldClim.txt",
                              header=T)); ClimData
# PC1
ClimVar_meanPC1=mean(ClimData$PC1); ClimVar_meanPC1
# PC2
ClimVar_meanPC2=mean(ClimData$PC2); ClimVar_meanPC2
# PC3
ClimVar_meanPC3=mean(ClimData$PC3); ClimVar_meanPC3
# standardize environment variables
# PC1
PC1.bayescenv <- t(ClimData$PC1-ClimVar_meanPC1); PC1.bayescenv
# PC2
PC2.bayescenv <- t(ClimData$PC2-ClimVar_meanPC2); PC2.bayescenv
# PC3
PC3.bayescenv <- t(ClimData$PC3-ClimVar_meanPC3); PC3.bayescenv
# save as text files for BayeScEnv
write.table(PC1.bayescenv,
            row.names=F,
            col.names=F,
            file="./data/Data_BayeScEnv_PC1_env.txt",
            sep=" ")
write.table(PC2.bayescenv,
            row.names=F,
            col.names=F,
            file="./data/Data_BayeScEnv_PC2_env.txt",
            sep=" ")
write.table(PC3.bayescenv,
            row.names=F,
            col.names=F,
            file="./data/Data_BayeScEnv_PC3_env.txt",
            sep=" ")

#' # BayeScEnv plots
#' <a href="#top">Back to top</a>
#+ project_bayeScEnv
######## BAYESCENV ................... ####
#' ## AFLP
#+ project_bayescan.aflp
######## AFLP ................................ ####
#' ### PC1
#' <a href="#top">Back to top</a>
#+ project_bayescan.aflp.PC1
######## PC1 ####
## load BayeScEnv data (Fst table)
AFLP_PC1_BayeScEnv.data <- tibble(read.table("./data/Data_BayeScEnv_AFLP_PC1_fst.txt",
                                             header=T)); AFLP_PC1_BayeScEnv.data
AFLP_PC1_BayeScEnv.data$ID <- names(AFLP_C)[-c(1:8)]
# add locus IDs (dye from multiplexing and base-pair position)
AFLP_PC1_BayeScEnv.data$marker <- names(AFLP_C)[-c(1:8)]
# replace FAM_AAC_CCT_* with loc
AFLP_PC1_BayeScEnv.data$marker <- stringr::str_replace(AFLP_PC1_BayeScEnv.data$marker,
                                                       "FAM_AAC_CCT_",
                                                       "loc")
# replace VIC_ACG_CAT_* with loc
AFLP_PC1_BayeScEnv.data$marker <- stringr::str_replace(AFLP_PC1_BayeScEnv.data$marker,
                                                       "VIC_ACG_CAT_",
                                                       "loc")
# replace NED_ACC_CTG_* with loc
AFLP_PC1_BayeScEnv.data$marker <- stringr::str_replace(AFLP_PC1_BayeScEnv.data$marker,
                                                       "NED_ACC_CTG_",
                                                       "loc")
# replace PET_AGG_CGA_* with loc
AFLP_PC1_BayeScEnv.data$marker <- stringr::str_replace(AFLP_PC1_BayeScEnv.data$marker,
                                                       "PET_AGG_CGA_",
                                                       "loc")
AFLP_PC1_BayeScEnv.data$marker # check
# add locus number for x-axis (base-pair value)
AFLP_PC1_BayeScEnv.data$basepair <- AFLP_PC1_BayeScEnv.data$marker
# remove FAM_AAC_CCT_* from label
AFLP_PC1_BayeScEnv.data$basepair <- stringr::str_replace(AFLP_PC1_BayeScEnv.data$basepair,
                                                         "loc",
                                                         "")
# remove VIC_ACG_CAT_* from label
AFLP_PC1_BayeScEnv.data$basepair <- stringr::str_replace(AFLP_PC1_BayeScEnv.data$basepair,
                                                         "loc",
                                                         "")
# remove NED_ACC_CTG_* from label
AFLP_PC1_BayeScEnv.data$basepair <- stringr::str_replace(AFLP_PC1_BayeScEnv.data$basepair,
                                                         "loc",
                                                         "")
# remove PET_AGG_CGA_* from label
AFLP_PC1_BayeScEnv.data$basepair <- stringr::str_replace(AFLP_PC1_BayeScEnv.data$basepair,
                                                         "loc",
                                                         "")
AFLP_PC1_BayeScEnv.data$basepair <- as.numeric(AFLP_PC1_BayeScEnv.data$basepair)
AFLP_PC1_BayeScEnv.data$basepair# check
# negative logarithm on the basis of 10
AFLP_PC1_BayeScEnv.data$log10.qVal <- -log10(AFLP_PC1_BayeScEnv.data$qval_g)
# add dye label
AFLP_PC1_BayeScEnv.data$dye <- AFLP_PC1_BayeScEnv.data$ID
# replace FAM_AAC_CCT[0-9|_]+ with FAM
AFLP_PC1_BayeScEnv.data$dye <- stringr::str_replace(AFLP_PC1_BayeScEnv.data$dye,
                                                    "FAM_AAC_CCT[0-9|_]+",
                                                    "FAM")
# replace VIC_ACG_CAT[0-9|_]+ with FAM
AFLP_PC1_BayeScEnv.data$dye <- stringr::str_replace(AFLP_PC1_BayeScEnv.data$dye,
                                                    "VIC_ACG_CAT[0-9|_]+",
                                                    "VIC")
# replace NED_ACC_CTG[0-9|_]+ with FAM
AFLP_PC1_BayeScEnv.data$dye <- stringr::str_replace(AFLP_PC1_BayeScEnv.data$dye,
                                                    "NED_ACC_CTG[0-9|_]+",
                                                    "NED")
# replace PET_AGG_CGA[0-9|_]+ with FAM
AFLP_PC1_BayeScEnv.data$dye <- stringr::str_replace(AFLP_PC1_BayeScEnv.data$dye,
                                                    "PET_AGG_CGA[0-9|_]+",
                                                    "PET")
AFLP_PC1_BayeScEnv.data$dye <- as.factor(AFLP_PC1_BayeScEnv.data$dye)
AFLP_PC1_BayeScEnv.data$dye # check
AFLP_PC1_BayeScEnv.data
# subset to the significant ones (PEP_g < PEP_alpha)
AFLP_PC1_signf.loc <- AFLP_PC1_BayeScEnv.data[(AFLP_PC1_BayeScEnv.data$PEP_g<
                                                 AFLP_PC1_BayeScEnv.data$PEP_alpha),]
AFLP_PC1_signf.loc$env <- "PC1"
AFLP_PC1_signf.loc
# and plot
set.seed(123)
AFLP_PC1_BayeScEnv.plot <- ggplot(AFLP_PC1_BayeScEnv.data,
                                  aes(x=basepair,
                                      y=log10(PEP_g/PEP_alpha))) +
  geom_point(alpha=0.3,
             size=2) +
  geom_hline(yintercept=0,
             linetype="dashed") +
  labs(title="AFLP (Control)",
       subtitle="PC1 (explained variation: 40.3%)",
       x="",
       y=expression(paste(log[10]~"("*PEP[gamma]/PEP[alpha]*")"))) +
  coord_cartesian(ylim=c(-0.2,0.4),
                  xlim=c(50,500)) +
  theme_cowplot()+
  theme(axis.line.y.right=element_line(color="transparent"),
        axis.ticks.y.right=element_blank(),
        axis.text.y.right=element_text(color="transparent"),
        panel.border=element_rect(color="black"),
        legend.position="none") +
  ggrepel::geom_text_repel(data=AFLP_PC1_signf.loc,
                           aes(x=basepair,
                               y=log10(PEP_g/PEP_alpha),
                               label=marker,
                               color=dye),
                           segment.color="gray80",
                           max.overlaps=50,
                           size=3,
                           direction="both",
                           angle=0,
                           hjust=0,
                           force_pull=0,
                           nudge_y=0.8-(AFLP_PC1_signf.loc$PEP_g/
                                              AFLP_PC1_signf.loc$PEP_alpha),
                           seed=123) +
  scale_color_manual(values=c("blue","black","tomato","green3")); AFLP_PC1_BayeScEnv.plot

#' ### PC2
#' <a href="#top">Back to top</a>
#+ project_bayescan.aflp.PC2
######## PC2 ####
## load BayeScEnv data (Fst table)
AFLP_PC2_BayeScEnv.data <- tibble(read.table("./data/Data_BayeScEnv_AFLP_PC2_fst.txt",
                                             header=T)); AFLP_PC2_BayeScEnv.data
AFLP_PC2_BayeScEnv.data$ID <- names(AFLP_C)[-c(1:8)]
# add locus IDs (dye from multiplexing and base-pair position)
AFLP_PC2_BayeScEnv.data$marker <- names(AFLP_C)[-c(1:8)]
# replace FAM_AAC_CCT_* with loc
AFLP_PC2_BayeScEnv.data$marker <- stringr::str_replace(AFLP_PC2_BayeScEnv.data$marker,
                                                       "FAM_AAC_CCT_",
                                                       "loc")
# replace VIC_ACG_CAT_* with loc
AFLP_PC2_BayeScEnv.data$marker <- stringr::str_replace(AFLP_PC2_BayeScEnv.data$marker,
                                                       "VIC_ACG_CAT_",
                                                       "loc")
# replace NED_ACC_CTG_* with loc
AFLP_PC2_BayeScEnv.data$marker <- stringr::str_replace(AFLP_PC2_BayeScEnv.data$marker,
                                                       "NED_ACC_CTG_",
                                                       "loc")
# replace PET_AGG_CGA_* with loc
AFLP_PC2_BayeScEnv.data$marker <- stringr::str_replace(AFLP_PC2_BayeScEnv.data$marker,
                                                       "PET_AGG_CGA_",
                                                       "loc")
AFLP_PC2_BayeScEnv.data$marker # check
# add locus number for x-axis (base-pair value)
AFLP_PC2_BayeScEnv.data$basepair <- AFLP_PC2_BayeScEnv.data$marker
# remove FAM_AAC_CCT_* from label
AFLP_PC2_BayeScEnv.data$basepair <- stringr::str_replace(AFLP_PC2_BayeScEnv.data$basepair,
                                                         "loc",
                                                         "")
# remove VIC_ACG_CAT_* from label
AFLP_PC2_BayeScEnv.data$basepair <- stringr::str_replace(AFLP_PC2_BayeScEnv.data$basepair,
                                                         "loc",
                                                         "")
# remove NED_ACC_CTG_* from label
AFLP_PC2_BayeScEnv.data$basepair <- stringr::str_replace(AFLP_PC2_BayeScEnv.data$basepair,
                                                         "loc",
                                                         "")
# remove PET_AGG_CGA_* from label
AFLP_PC2_BayeScEnv.data$basepair <- stringr::str_replace(AFLP_PC2_BayeScEnv.data$basepair,
                                                         "loc",
                                                         "")
AFLP_PC2_BayeScEnv.data$basepair <- as.numeric(AFLP_PC2_BayeScEnv.data$basepair)
AFLP_PC2_BayeScEnv.data$basepair# check
# negative logarithm on the basis of 10
AFLP_PC2_BayeScEnv.data$log10.qVal <- -log10(AFLP_PC2_BayeScEnv.data$qval_g)
# add dye label
AFLP_PC2_BayeScEnv.data$dye <- names(AFLP_C)[-c(1:8)]
# replace FAM_AAC_CCT[0-9|_]+ with FAM
AFLP_PC2_BayeScEnv.data$dye <- stringr::str_replace(AFLP_PC2_BayeScEnv.data$dye,
                                                    "FAM_AAC_CCT[0-9|_]+",
                                                    "FAM")
# replace VIC_ACG_CAT[0-9|_]+ with FAM
AFLP_PC2_BayeScEnv.data$dye <- stringr::str_replace(AFLP_PC2_BayeScEnv.data$dye,
                                                    "VIC_ACG_CAT[0-9|_]+",
                                                    "VIC")
# replace NED_ACC_CTG[0-9|_]+ with FAM
AFLP_PC2_BayeScEnv.data$dye <- stringr::str_replace(AFLP_PC2_BayeScEnv.data$dye,
                                                    "NED_ACC_CTG[0-9|_]+",
                                                    "NED")
# replace PET_AGG_CGA[0-9|_]+ with FAM
AFLP_PC2_BayeScEnv.data$dye <- stringr::str_replace(AFLP_PC2_BayeScEnv.data$dye,
                                                    "PET_AGG_CGA[0-9|_]+",
                                                    "PET")
AFLP_PC2_BayeScEnv.data$dye <- as.factor(AFLP_PC2_BayeScEnv.data$dye)
AFLP_PC2_BayeScEnv.data$dye # check
AFLP_PC2_BayeScEnv.data
# subset to the significant ones (PEP_g < PEP_alpha)
AFLP_PC2_signf.loc <- AFLP_PC2_BayeScEnv.data[(AFLP_PC2_BayeScEnv.data$PEP_g<
                                                 AFLP_PC2_BayeScEnv.data$PEP_alpha),]
AFLP_PC2_signf.loc$env <- "PC2"
AFLP_PC2_signf.loc
# and plot
set.seed(123)
AFLP_PC2_BayeScEnv.plot <- ggplot(AFLP_PC2_BayeScEnv.data,
                                  aes(x=basepair,
                                      y=log10(PEP_g/PEP_alpha))) +
  geom_point(alpha=0.3,
             size=2) +
  geom_hline(yintercept=0,
             linetype="dashed") +
  labs(title="",
       subtitle="PC2 (explained variation: 32.7%)",
       x="",
       y="") +
  coord_cartesian(ylim=c(-0.2,0.4),xlim=c(50,500)) +
  theme_cowplot()+
  theme(axis.line.y.right=element_line(color="transparent"),
        axis.ticks.y.right=element_blank(),
        axis.text.y.right=element_text(color="transparent"),
        panel.border=element_rect(color="black"),
        legend.position="none") +
  ggrepel::geom_text_repel(data=AFLP_PC2_signf.loc,
                           aes(x=basepair,
                               y=log10(PEP_g/PEP_alpha),
                               label=marker,
                               color=dye),
                           segment.color="gray80",
                           max.overlaps=50,
                           size=3,
                           direction="both",
                           angle=0,
                           hjust=0,
                           force_pull=0,
                           nudge_y=0.8-(AFLP_PC2_signf.loc$PEP_g/
                                              AFLP_PC2_signf.loc$PEP_alpha),
                           seed=123) +
  scale_color_manual(values=c("black","green3","tomato","blue")); AFLP_PC2_BayeScEnv.plot

#' ### PC3
#' <a href="#top">Back to top</a>
#+ project_bayescan.aflp.PC3
######## PC3 ####
## load BayeScEnv data (Fst table)
AFLP_PC3_BayeScEnv.data <- tibble(read.table("./data/Data_BayeScEnv_AFLP_PC3_fst.txt",
                                             header=T)); AFLP_PC3_BayeScEnv.data
AFLP_PC3_BayeScEnv.data$ID <- names(AFLP_C)[-c(1:8)]
# add locus IDs (dye from multiplexing and base-pair position)
AFLP_PC3_BayeScEnv.data$marker <- names(AFLP_C)[-c(1:8)]
# replace FAM_AAC_CCT_* with loc
AFLP_PC3_BayeScEnv.data$marker <- stringr::str_replace(AFLP_PC3_BayeScEnv.data$marker,
                                                       "FAM_AAC_CCT_",
                                                       "loc")
# replace VIC_ACG_CAT_* with loc
AFLP_PC3_BayeScEnv.data$marker <- stringr::str_replace(AFLP_PC3_BayeScEnv.data$marker,
                                                       "VIC_ACG_CAT_",
                                                       "loc")
# replace NED_ACC_CTG_* with loc
AFLP_PC3_BayeScEnv.data$marker <- stringr::str_replace(AFLP_PC3_BayeScEnv.data$marker,
                                                       "NED_ACC_CTG_",
                                                       "loc")
# replace PET_AGG_CGA_* with loc
AFLP_PC3_BayeScEnv.data$marker <- stringr::str_replace(AFLP_PC3_BayeScEnv.data$marker,
                                                       "PET_AGG_CGA_",
                                                       "loc")
AFLP_PC3_BayeScEnv.data$marker # check
# add locus number for x-axis (base-pair value)
AFLP_PC3_BayeScEnv.data$basepair <- AFLP_PC3_BayeScEnv.data$marker
# remove FAM_AAC_CCT_* from label
AFLP_PC3_BayeScEnv.data$basepair <- stringr::str_replace(AFLP_PC3_BayeScEnv.data$basepair,
                                                         "loc",
                                                         "")
# remove VIC_ACG_CAT_* from label
AFLP_PC3_BayeScEnv.data$basepair <- stringr::str_replace(AFLP_PC3_BayeScEnv.data$basepair,
                                                         "loc",
                                                         "")
# remove NED_ACC_CTG_* from label
AFLP_PC3_BayeScEnv.data$basepair <- stringr::str_replace(AFLP_PC3_BayeScEnv.data$basepair,
                                                         "loc",
                                                         "")
# remove PET_AGG_CGA_* from label
AFLP_PC3_BayeScEnv.data$basepair <- stringr::str_replace(AFLP_PC3_BayeScEnv.data$basepair,
                                                         "loc",
                                                         "")
AFLP_PC3_BayeScEnv.data$basepair <- as.numeric(AFLP_PC3_BayeScEnv.data$basepair)
AFLP_PC3_BayeScEnv.data$basepair# check
# negative logarithm on the basis of 10
AFLP_PC3_BayeScEnv.data$log10.qVal <- -log10(AFLP_PC3_BayeScEnv.data$qval_g)
# add dye label
AFLP_PC3_BayeScEnv.data$dye <- names(AFLP_C)[-c(1:8)]
# replace FAM_AAC_CCT[0-9|_]+ with FAM
AFLP_PC3_BayeScEnv.data$dye <- stringr::str_replace(AFLP_PC3_BayeScEnv.data$dye,
                                                    "FAM_AAC_CCT[0-9|_]+",
                                                    "FAM")
# replace VIC_ACG_CAT[0-9|_]+ with FAM
AFLP_PC3_BayeScEnv.data$dye <- stringr::str_replace(AFLP_PC3_BayeScEnv.data$dye,
                                                    "VIC_ACG_CAT[0-9|_]+",
                                                    "VIC")
# replace NED_ACC_CTG[0-9|_]+ with FAM
AFLP_PC3_BayeScEnv.data$dye <- stringr::str_replace(AFLP_PC3_BayeScEnv.data$dye,
                                                    "NED_ACC_CTG[0-9|_]+",
                                                    "NED")
# replace PET_AGG_CGA[0-9|_]+ with FAM
AFLP_PC3_BayeScEnv.data$dye <- stringr::str_replace(AFLP_PC3_BayeScEnv.data$dye,
                                                    "PET_AGG_CGA[0-9|_]+",
                                                    "PET")
AFLP_PC3_BayeScEnv.data$dye <- as.factor(AFLP_PC3_BayeScEnv.data$dye)
AFLP_PC3_BayeScEnv.data$dye # check
AFLP_PC3_BayeScEnv.data
# subset to the significant ones (PEP_g < PEP_alpha)
AFLP_PC3_signf.loc <- AFLP_PC3_BayeScEnv.data[(AFLP_PC3_BayeScEnv.data$PEP_g<
                                                 AFLP_PC3_BayeScEnv.data$PEP_alpha),]
AFLP_PC3_signf.loc$env <- "PC3"
AFLP_PC3_signf.loc
# and plot
set.seed(123)
AFLP_PC3_BayeScEnv.plot <- ggplot(AFLP_PC3_BayeScEnv.data,
                                  aes(x=basepair,
                                      y=log10(PEP_g/PEP_alpha))) +
  geom_point(alpha=0.3,
             size=2) +
  geom_hline(yintercept=0,
             linetype="dashed") +
  labs(title="",
       subtitle="PC3 (explained variation: 14.4%)",
       x="",
       y="")+
  coord_cartesian(ylim=c(-0.2,0.4),
                  xlim=c(50,500)) +
  theme_cowplot()+
  theme(axis.line.y.right=element_line(color="transparent"),
        axis.ticks.y.right=element_blank(),
        axis.text.y.right=element_text(color="transparent"),
        panel.border=element_rect(color="black"),
        legend.position="none") +
  ggrepel::geom_text_repel(data=AFLP_PC3_signf.loc,
                           aes(x=basepair,
                               y=log10(PEP_g/PEP_alpha),
                               label=marker,
                               color=dye),
                           segment.color="gray80",
                           max.overlaps=50,
                           size=3,
                           direction="both",
                           angle=0,
                           hjust=0,
                           force_pull=0,
                           nudge_y=0.8-(AFLP_PC3_signf.loc$PEP_g/
                                              AFLP_PC3_signf.loc$PEP_alpha),
                           seed=123) +
  scale_color_manual(values=c("black","green3","tomato","blue")); AFLP_PC3_BayeScEnv.plot

#' ### Outlier data
#' <a href="#top">Back to top</a>
#+ project_bayescan.aflp.dataset
######## Outlier table ####
# combine tables
AFLP_signf.loc <- tibble(rbind(AFLP_PC1_signf.loc,
                               AFLP_PC2_signf.loc,
                               AFLP_PC3_signf.loc)); AFLP_signf.loc
# save outlier data
write.table(AFLP_signf.loc,
            row.names=F,
            file="./data/Data_BayeScEnv_AFLP_Outlier.txt",
            sep="\t")

#' ## MSAP-n
#' <a href="#top">Back to top</a>
#+ project_bayescan.MSAPn
######## MSAP-n ............................ ####
#' ### PC1
#' <a href="#top">Back to top</a>
#+ project_bayescan.MSAPn.PC1
######## PC1 ####
## load BayeScEnv data (Fst table)
MSAPn_PC1_BayeScEnv.data <- tibble(read.table("./data/Data_BayeScEnv_MSAPu_PC1_fst.txt",
                                               header=T)); MSAPn_PC1_BayeScEnv.data
MSAPn_PC1_BayeScEnv.data$ID <- names(data.frame(MSAPn.genind@tab))
# add locus IDs (dye from multiplexing and base-pair position)
MSAPn_PC1_BayeScEnv.data$marker <- names(data.frame(MSAPn.genind@tab))
# replace FAM_AAC_CCT_* with loc
MSAPn_PC1_BayeScEnv.data$marker <- stringr::str_replace(MSAPn_PC1_BayeScEnv.data$marker,
                                                         "uFAM_AAC_CCT_",
                                                         "loc")
# replace VIC_ACG_CAT_* with loc
MSAPn_PC1_BayeScEnv.data$marker <- stringr::str_replace(MSAPn_PC1_BayeScEnv.data$marker,
                                                         "uVIC_ACG_CAT_",
                                                         "loc")
# replace NED_ACC_CTG_* with loc
MSAPn_PC1_BayeScEnv.data$marker <- stringr::str_replace(MSAPn_PC1_BayeScEnv.data$marker,
                                                         "uNED_ACC_CTG_",
                                                         "loc")
# replace PET_AGG_CGA_* with loc
MSAPn_PC1_BayeScEnv.data$marker <- stringr::str_replace(MSAPn_PC1_BayeScEnv.data$marker,
                                                         "uPET_AGG_CGA_",
                                                         "loc")
MSAPn_PC1_BayeScEnv.data$marker # check
# add locus number for x-axis (base-pair value)
MSAPn_PC1_BayeScEnv.data$basepair <- MSAPn_PC1_BayeScEnv.data$marker
# remove FAM_AAC_CCT_* from label
MSAPn_PC1_BayeScEnv.data$basepair <- stringr::str_replace(MSAPn_PC1_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
# remove VIC_ACG_CAT_* from label
MSAPn_PC1_BayeScEnv.data$basepair <- stringr::str_replace(MSAPn_PC1_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
# remove NED_ACC_CTG_* from label
MSAPn_PC1_BayeScEnv.data$basepair <- stringr::str_replace(MSAPn_PC1_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
# remove PET_AGG_CGA_* from label
MSAPn_PC1_BayeScEnv.data$basepair <- stringr::str_replace(MSAPn_PC1_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
MSAPn_PC1_BayeScEnv.data$basepair <- as.numeric(MSAPn_PC1_BayeScEnv.data$basepair)
MSAPn_PC1_BayeScEnv.data$basepair# check
# negative logarithm on the basis of 10
MSAPn_PC1_BayeScEnv.data$log10.qVal <- -log10(MSAPn_PC1_BayeScEnv.data$qval_g)
# add dye label
MSAPn_PC1_BayeScEnv.data$dye <- names(data.frame(MSAPn.genind@tab))
# replace FAM_AAC_CCT[0-9|_]+ with FAM
MSAPn_PC1_BayeScEnv.data$dye <- stringr::str_replace(MSAPn_PC1_BayeScEnv.data$dye,
                                                      "uFAM_AAC_CCT[0-9|_]+",
                                                      "FAM")
# replace VIC_ACG_CAT[0-9|_]+ with FAM
MSAPn_PC1_BayeScEnv.data$dye <- stringr::str_replace(MSAPn_PC1_BayeScEnv.data$dye,
                                                      "uVIC_ACG_CAT[0-9|_]+",
                                                      "VIC")
# replace NED_ACC_CTG[0-9|_]+ with FAM
MSAPn_PC1_BayeScEnv.data$dye <- stringr::str_replace(MSAPn_PC1_BayeScEnv.data$dye,
                                                      "uNED_ACC_CTG[0-9|_]+",
                                                      "NED")
# replace PET_AGG_CGA[0-9|_]+ with FAM
MSAPn_PC1_BayeScEnv.data$dye <- stringr::str_replace(MSAPn_PC1_BayeScEnv.data$dye,
                                                      "uPET_AGG_CGA[0-9|_]+",
                                                      "PET")
MSAPn_PC1_BayeScEnv.data$dye <- as.factor(MSAPn_PC1_BayeScEnv.data$dye)
MSAPn_PC1_BayeScEnv.data$dye # check
MSAPn_PC1_BayeScEnv.data
# subset to the significant ones (PEP_g < PEP_alpha)
MSAPn_PC1_signf.loc <- MSAPn_PC1_BayeScEnv.data[(MSAPn_PC1_BayeScEnv.data$PEP_g<
                                                     MSAPn_PC1_BayeScEnv.data$PEP_alpha),]
MSAPn_PC1_signf.loc$env <- "PC1"
MSAPn_PC1_signf.loc
# and plot
set.seed(123)
MSAPn_PC1_BayeScEnv.plot <- ggplot(MSAPn_PC1_BayeScEnv.data,
                                    aes(x=basepair,
                                        y=log10(PEP_g/PEP_alpha))) +
  geom_point(alpha=0.3,
             size=2) +
  geom_hline(yintercept=0,
             linetype="dashed") +
  labs(title="MSAP-n (Control)",
       subtitle="PC1 (explained variation: 40.3%)",
       x="Scored loci [basepairs]",
       y=expression(paste(log[10]~"("*PEP[gamma]/PEP[alpha]*")"))) +
  coord_cartesian(ylim=c(-0.15,0.1),
                  xlim=c(50,500)) +
  theme_cowplot()+
  theme(axis.line.y.right=element_line(color="transparent"),
        axis.ticks.y.right=element_blank(),
        axis.text.y.right=element_text(color="transparent"),
        panel.border=element_rect(color="black"),
        legend.position="none") +
  ggrepel::geom_text_repel(data=MSAPn_PC1_signf.loc,
                           aes(x=basepair,
                               y=log10(PEP_g/PEP_alpha),
                               label=marker,
                               color=dye),
                           segment.color="gray80",
                           max.overlaps=50,
                           size=3,
                           direction="both",
                           angle=0,
                           hjust=0,
                           force_pull=0,
                           nudge_y=-0.05-log10(MSAPn_PC1_signf.loc$PEP_g/
                                                     MSAPn_PC1_signf.loc$PEP_alpha),
                           seed=123) +
  scale_color_manual(values=c("blue","black","tomato","green3")); MSAPn_PC1_BayeScEnv.plot

#' ### PC2
#' <a href="#top">Back to top</a>
#+ project_bayescan.MSAPn.PC2
######## PC2 ####
## load BayeScEnv data (Fst table)
MSAPn_PC2_BayeScEnv.data <- tibble(read.table(paste0(data_path,
                                                      "BayeScEnv_MSAPu_CON_all_PC2_fst.txt"),
                                               header=T)); MSAPn_PC2_BayeScEnv.data
MSAPn_PC2_BayeScEnv.data$ID <- names(data.frame(MSAPn.genind@tab))
# add locus IDs (dye from multiplexing and base-pair position)
MSAPn_PC2_BayeScEnv.data$marker <- names(data.frame(MSAPn.genind@tab))
# replace FAM_AAC_CCT_* with loc
MSAPn_PC2_BayeScEnv.data$marker <- stringr::str_replace(MSAPn_PC2_BayeScEnv.data$marker,
                                                         "uFAM_AAC_CCT_","loc")
# replace VIC_ACG_CAT_* with loc
MSAPn_PC2_BayeScEnv.data$marker <- stringr::str_replace(MSAPn_PC2_BayeScEnv.data$marker,
                                                         "uVIC_ACG_CAT_","loc")
# replace NED_ACC_CTG_* with loc
MSAPn_PC2_BayeScEnv.data$marker <- stringr::str_replace(MSAPn_PC2_BayeScEnv.data$marker,
                                                         "uNED_ACC_CTG_","loc")
# replace PET_AGG_CGA_* with loc
MSAPn_PC2_BayeScEnv.data$marker <- stringr::str_replace(MSAPn_PC2_BayeScEnv.data$marker,
                                                         "uPET_AGG_CGA_","loc")
MSAPn_PC2_BayeScEnv.data$marker # check
# add locus number for x-axis (base-pair value)
MSAPn_PC2_BayeScEnv.data$basepair <- MSAPn_PC2_BayeScEnv.data$marker
# remove FAM_AAC_CCT_* from label
MSAPn_PC2_BayeScEnv.data$basepair <- stringr::str_replace(MSAPn_PC2_BayeScEnv.data$basepair,
                                                           "loc","")
# remove VIC_ACG_CAT_* from label
MSAPn_PC2_BayeScEnv.data$basepair <- stringr::str_replace(MSAPn_PC2_BayeScEnv.data$basepair,
                                                           "loc","")
# remove NED_ACC_CTG_* from label
MSAPn_PC2_BayeScEnv.data$basepair <- stringr::str_replace(MSAPn_PC2_BayeScEnv.data$basepair,
                                                           "loc","")
# remove PET_AGG_CGA_* from label
MSAPn_PC2_BayeScEnv.data$basepair <- stringr::str_replace(MSAPn_PC2_BayeScEnv.data$basepair,
                                                           "loc","")
MSAPn_PC2_BayeScEnv.data$basepair <- as.numeric(MSAPn_PC2_BayeScEnv.data$basepair)
MSAPn_PC2_BayeScEnv.data$basepair# check
# negative logarithm on the basis of 10
MSAPn_PC2_BayeScEnv.data$log10.qVal <- -log10(MSAPn_PC2_BayeScEnv.data$qval_g)
# add dye label
MSAPn_PC2_BayeScEnv.data$dye <- names(data.frame(MSAPn.genind@tab))
# replace FAM_AAC_CCT[0-9|_]+ with FAM
MSAPn_PC2_BayeScEnv.data$dye <- stringr::str_replace(MSAPn_PC2_BayeScEnv.data$dye,
                                                      "uFAM_AAC_CCT[0-9|_]+","FAM")
# replace VIC_ACG_CAT[0-9|_]+ with FAM
MSAPn_PC2_BayeScEnv.data$dye <- stringr::str_replace(MSAPn_PC2_BayeScEnv.data$dye,
                                                      "uVIC_ACG_CAT[0-9|_]+","VIC")
# replace NED_ACC_CTG[0-9|_]+ with FAM
MSAPn_PC2_BayeScEnv.data$dye <- stringr::str_replace(MSAPn_PC2_BayeScEnv.data$dye,
                                                      "uNED_ACC_CTG[0-9|_]+","NED")
# replace PET_AGG_CGA[0-9|_]+ with FAM
MSAPn_PC2_BayeScEnv.data$dye <- stringr::str_replace(MSAPn_PC2_BayeScEnv.data$dye,
                                                      "uPET_AGG_CGA[0-9|_]+","PET")
MSAPn_PC2_BayeScEnv.data$dye <- as.factor(MSAPn_PC2_BayeScEnv.data$dye)
MSAPn_PC2_BayeScEnv.data$dye # check
MSAPn_PC2_BayeScEnv.data
# subset to the significant ones (PEP_g < PEP_alpha)
MSAPn_PC2_signf.loc <- MSAPn_PC2_BayeScEnv.data[(MSAPn_PC2_BayeScEnv.data$PEP_g<
                                                     MSAPn_PC2_BayeScEnv.data$PEP_alpha),]
MSAPn_PC2_signf.loc$env <- "PC2"
MSAPn_PC2_signf.loc
# and plot
set.seed(123)
MSAPn_PC2_BayeScEnv.plot <- ggplot(MSAPn_PC2_BayeScEnv.data,
                                    aes(x=basepair,
                                        y=log10(PEP_g/PEP_alpha))) +
  geom_point(alpha=0.3,
             size=2) +
  geom_hline(yintercept=0,
             linetype="dashed") +
  labs(title="",
       subtitle="PC2 (explained variation: 32.7%)",
       x="Scored loci [basepairs]",
       y="") +
  coord_cartesian(ylim=c(-0.15,0.1),xlim=c(50,500)) +
  theme_cowplot()+
  theme(axis.line.y.right=element_line(color="transparent"),
        axis.ticks.y.right=element_blank(),
        axis.text.y.right=element_text(color="transparent"),
        panel.border=element_rect(color="black"),
        legend.position="none") +
  ggrepel::geom_text_repel(data=MSAPn_PC2_signf.loc,
                           aes(x=basepair,
                               y=log10(PEP_g/PEP_alpha),
                               label=marker,
                               color=dye),
                           segment.color="gray80",
                           max.overlaps=50,
                           size=3,
                           direction="both",
                           angle=0,
                           hjust=0,
                           force_pull=0,
                           nudge_y=-0.05-log10(MSAPn_PC2_signf.loc$PEP_g/
                                                     MSAPn_PC2_signf.loc$PEP_alpha),
                           seed=123) +
  scale_color_manual(values=c("red","black","blue","green3")); MSAPn_PC2_BayeScEnv.plot

#' ### PC3
#' <a href="#top">Back to top</a>
#+ project_bayescan.MSAPn.PC3
######## PC3 ####
## load BayeScEnv data (Fst table)
MSAPn_PC3_BayeScEnv.data <- tibble(read.table("./data/BayeScEnv_MSAPu_CON_all_PC3_fst.txt",
                                               header=T)); MSAPn_PC3_BayeScEnv.data
MSAPn_PC3_BayeScEnv.data$ID <- names(data.frame(MSAPn.genind@tab))
# add locus IDs (dye from multiplexing and base-pair position)
MSAPn_PC3_BayeScEnv.data$marker <- names(data.frame(MSAPn.genind@tab))
# replace FAM_AAC_CCT_* with loc
MSAPn_PC3_BayeScEnv.data$marker <- stringr::str_replace(MSAPn_PC3_BayeScEnv.data$marker,
                                                         "uFAM_AAC_CCT_",
                                                         "loc")
# replace VIC_ACG_CAT_* with loc
MSAPn_PC3_BayeScEnv.data$marker <- stringr::str_replace(MSAPn_PC3_BayeScEnv.data$marker,
                                                         "uVIC_ACG_CAT_",
                                                         "loc")
# replace NED_ACC_CTG_* with loc
MSAPn_PC3_BayeScEnv.data$marker <- stringr::str_replace(MSAPn_PC3_BayeScEnv.data$marker,
                                                         "uNED_ACC_CTG_",
                                                         "loc")
# replace PET_AGG_CGA_* with loc
MSAPn_PC3_BayeScEnv.data$marker <- stringr::str_replace(MSAPn_PC3_BayeScEnv.data$marker,
                                                         "uPET_AGG_CGA_",
                                                         "loc")
MSAPn_PC3_BayeScEnv.data$marker # check
# add locus number for x-axis (base-pair value)
MSAPn_PC3_BayeScEnv.data$basepair <- MSAPn_PC3_BayeScEnv.data$marker
# remove FAM_AAC_CCT_* from label
MSAPn_PC3_BayeScEnv.data$basepair <- stringr::str_replace(MSAPn_PC3_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
# remove VIC_ACG_CAT_* from label
MSAPn_PC3_BayeScEnv.data$basepair <- stringr::str_replace(MSAPn_PC3_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
# remove NED_ACC_CTG_* from label
MSAPn_PC3_BayeScEnv.data$basepair <- stringr::str_replace(MSAPn_PC3_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
# remove PET_AGG_CGA_* from label
MSAPn_PC3_BayeScEnv.data$basepair <- stringr::str_replace(MSAPn_PC3_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
MSAPn_PC3_BayeScEnv.data$basepair <- as.numeric(MSAPn_PC3_BayeScEnv.data$basepair)
MSAPn_PC3_BayeScEnv.data$basepair# check
# negative logarithm on the basis of 10
MSAPn_PC3_BayeScEnv.data$log10.qVal <- -log10(MSAPn_PC3_BayeScEnv.data$qval_g)
# add dye label
MSAPn_PC3_BayeScEnv.data$dye <- names(data.frame(MSAPn.genind@tab))
# replace FAM_AAC_CCT[0-9|_]+ with FAM
MSAPn_PC3_BayeScEnv.data$dye <- stringr::str_replace(MSAPn_PC3_BayeScEnv.data$dye,
                                                      "uFAM_AAC_CCT[0-9|_]+",
                                                      "FAM")
# replace VIC_ACG_CAT[0-9|_]+ with FAM
MSAPn_PC3_BayeScEnv.data$dye <- stringr::str_replace(MSAPn_PC3_BayeScEnv.data$dye,
                                                      "uVIC_ACG_CAT[0-9|_]+",
                                                      "VIC")
# replace NED_ACC_CTG[0-9|_]+ with FAM
MSAPn_PC3_BayeScEnv.data$dye <- stringr::str_replace(MSAPn_PC3_BayeScEnv.data$dye,
                                                      "uNED_ACC_CTG[0-9|_]+",
                                                      "NED")
# replace PET_AGG_CGA[0-9|_]+ with FAM
MSAPn_PC3_BayeScEnv.data$dye <- stringr::str_replace(MSAPn_PC3_BayeScEnv.data$dye,
                                                      "uPET_AGG_CGA[0-9|_]+",
                                                      "PET")
MSAPn_PC3_BayeScEnv.data$dye <- as.factor(MSAPn_PC3_BayeScEnv.data$dye)
MSAPn_PC3_BayeScEnv.data$dye # check
MSAPn_PC3_BayeScEnv.data
# subset to the significant ones (PEP_g < PEP_alpha)
MSAPn_PC3_signf.loc <- MSAPn_PC3_BayeScEnv.data[(MSAPn_PC3_BayeScEnv.data$PEP_g<
                                                     MSAPn_PC3_BayeScEnv.data$PEP_alpha),]
MSAPn_PC3_signf.loc$env <- "PC3"
MSAPn_PC3_signf.loc
# and plot
set.seed(123)
MSAPn_PC3_BayeScEnv.plot <- ggplot(MSAPn_PC3_BayeScEnv.data,
                                    aes(x=basepair,
                                        y=log10(PEP_g/PEP_alpha))) +
  geom_point(alpha=0.3,
             size=2) +
  geom_hline(yintercept=0,
             linetype="dashed") +
  labs(title="",
       subtitle="PC3 (explained variation: 14.4%)",
       x="Scored loci [basepairs]",
       y="") +
  coord_cartesian(ylim=c(-0.15,0.1),
                  xlim=c(50,500)) +
  theme_cowplot()+
  theme(axis.line.y.right=element_line(color="transparent"),
        axis.ticks.y.right=element_blank(),
        axis.text.y.right=element_text(color="transparent"),
        panel.border=element_rect(color="black"),
        legend.position="none") +
  ggrepel::geom_text_repel(data=MSAPn_PC3_signf.loc,
                           aes(x=basepair,
                               y=log10(PEP_g/PEP_alpha),
                               label=marker,
                               color=dye),
                           segment.color="gray80",
                           max.overlaps=50,
                           size=3,
                           direction="both",
                           angle=0,
                           hjust=0,
                           force_pull=0,
                           nudge_y=-0.05-log10(MSAPn_PC3_signf.loc$PEP_g/
                                                     MSAPn_PC3_signf.loc$PEP_alpha),
                           seed=123) +
  scale_color_manual(values=c("blue","black","tomato","green3")); MSAPn_PC3_BayeScEnv.plot

#' ### Outlier data
#' <a href="#top">Back to top</a>
#+ project_bayescan.MSAPn.dataset
######## Outlier table ####
# combine tables
MSAPn_signf.loc <- tibble(rbind(MSAPn_PC1_signf.loc,
                                 MSAPn_PC2_signf.loc,
                                 MSAPn_PC3_signf.loc)); MSAPn_signf.loc
# save outlier data
write.table(MSAPn_signf.loc,
            row.names=F,
            file="./data/Data_BayeScEnv_MSAPu_Outlier.txt",
            sep="\t")

#' ## MSAP-m
#' <a href="#top">Back to top</a>
#+ project_bayescan.MSAPm
######## MSAPm ........................... ####
#' ### PC1
#' <a href="#top">Back to top</a>
#+ project_bayescan.MSAPm.PC1
######## PC1 ####
## load BayeScEnv data (Fst table)
MSAPm_PC1_BayeScEnv.data <- tibble(read.table("./data/BayeScEnv_MSAPm_PC1_fst.txt",
                                               header=T)); MSAPm_PC1_BayeScEnv.data
MSAPm_PC1_BayeScEnv.data$ID <- names(data.frame(MSAPm.genind@tab))
# add locus IDs (dye from multiplexing and base-pair position)
MSAPm_PC1_BayeScEnv.data$marker <- names(data.frame(MSAPm.genind@tab))
# replace FAM_AAC_CCT_* with loc
MSAPm_PC1_BayeScEnv.data$marker <- stringr::str_replace(MSAPm_PC1_BayeScEnv.data$marker,
                                                         "MFAM_AAC_CCT_",
                                                         "loc")
# replace VIC_ACG_CAT_* with loc
MSAPm_PC1_BayeScEnv.data$marker <- stringr::str_replace(MSAPm_PC1_BayeScEnv.data$marker,
                                                         "MVIC_ACG_CAT_",
                                                         "loc")
# replace NED_ACC_CTG_* with loc
MSAPm_PC1_BayeScEnv.data$marker <- stringr::str_replace(MSAPm_PC1_BayeScEnv.data$marker,
                                                         "MNED_ACC_CTG_",
                                                         "loc")
# replace PET_AGG_CGA_* with loc
MSAPm_PC1_BayeScEnv.data$marker <- stringr::str_replace(MSAPm_PC1_BayeScEnv.data$marker,
                                                         "MPET_AGG_CGA_",
                                                         "loc")
MSAPm_PC1_BayeScEnv.data$marker # check
# add locus number for x-axis (base-pair value)
MSAPm_PC1_BayeScEnv.data$basepair <- MSAPm_PC1_BayeScEnv.data$marker
# remove FAM_AAC_CCT_* from label
MSAPm_PC1_BayeScEnv.data$basepair <- stringr::str_replace(MSAPm_PC1_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
# remove VIC_ACG_CAT_* from label
MSAPm_PC1_BayeScEnv.data$basepair <- stringr::str_replace(MSAPm_PC1_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
# remove NED_ACC_CTG_* from label
MSAPm_PC1_BayeScEnv.data$basepair <- stringr::str_replace(MSAPm_PC1_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
# remove PET_AGG_CGA_* from label
MSAPm_PC1_BayeScEnv.data$basepair <- stringr::str_replace(MSAPm_PC1_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
MSAPm_PC1_BayeScEnv.data$basepair <- as.numeric(MSAPm_PC1_BayeScEnv.data$basepair)
MSAPm_PC1_BayeScEnv.data$basepair# check
# negative logarithm on the basis of 10
MSAPm_PC1_BayeScEnv.data$log10.qVal <- -log10(MSAPm_PC1_BayeScEnv.data$qval_g)
# add dye label
MSAPm_PC1_BayeScEnv.data$dye <- names(data.frame(MSAPm.genind@tab))
# replace FAM_AAC_CCT[0-9|_]+ with FAM
MSAPm_PC1_BayeScEnv.data$dye <- stringr::str_replace(MSAPm_PC1_BayeScEnv.data$dye,
                                                      "MFAM_AAC_CCT[0-9|_]+",
                                                      "FAM")
# replace VIC_ACG_CAT[0-9|_]+ with FAM
MSAPm_PC1_BayeScEnv.data$dye <- stringr::str_replace(MSAPm_PC1_BayeScEnv.data$dye,
                                                      "MVIC_ACG_CAT[0-9|_]+",
                                                      "VIC")
# replace NED_ACC_CTG[0-9|_]+ with FAM
MSAPm_PC1_BayeScEnv.data$dye <- stringr::str_replace(MSAPm_PC1_BayeScEnv.data$dye,
                                                      "MNED_ACC_CTG[0-9|_]+",
                                                      "NED")
# replace PET_AGG_CGA[0-9|_]+ with FAM
MSAPm_PC1_BayeScEnv.data$dye <- stringr::str_replace(MSAPm_PC1_BayeScEnv.data$dye,
                                                      "MPET_AGG_CGA[0-9|_]+",
                                                      "PET")
MSAPm_PC1_BayeScEnv.data$dye <- as.factor(MSAPm_PC1_BayeScEnv.data$dye)
MSAPm_PC1_BayeScEnv.data$dye # check
MSAPm_PC1_BayeScEnv.data
# subset to the significant ones (PEP_g < PEP_alpha)
MSAPm_PC1_signf.loc <- MSAPm_PC1_BayeScEnv.data[(MSAPm_PC1_BayeScEnv.data$PEP_g<
                                                     MSAPm_PC1_BayeScEnv.data$PEP_alpha),]
MSAPm_PC1_signf.loc$env <- "PC1"
MSAPm_PC1_signf.loc
# and plot
set.seed(123)
MSAPm_PC1_BayeScEnv.plot <- ggplot(MSAPm_PC1_BayeScEnv.data,
                                    aes(x=basepair,
                                        y=log10(PEP_g/PEP_alpha))) +
  geom_point(alpha=0.3,
             size=2) +
  geom_hline(yintercept=0,
             linetype="dashed") +
  labs(title="MSAP-m (Control)",
       subtitle="PC1 (explained variation: 40.3%)",
       x="",
       y=expression(paste(log[10]~"("*PEP[gamma]/PEP[alpha]*")"))) +
  coord_cartesian(ylim=c(-0.2,0.4),
                  xlim=c(50,500)) +
  theme_cowplot()+
  theme(axis.line.y.right=element_line(color="transparent"),
        axis.ticks.y.right=element_blank(),
        axis.text.y.right=element_text(color="transparent"),
        panel.border=element_rect(color="black"),
        legend.position="none") +
  ggrepel::geom_text_repel(data=MSAPm_PC1_signf.loc,
                           aes(x=basepair,
                               y=log10(PEP_g/PEP_alpha),
                               label=marker,
                               color=dye),
                           segment.color="gray80",
                           max.overlaps=50,
                           size=3,
                           direction="both",
                           angle=0,
                           hjust=0,
                           force_pull=0,
                           nudge_y=-0.05-log10(MSAPm_PC1_signf.loc$PEP_g/
                                                     MSAPm_PC1_signf.loc$PEP_alpha),
                           seed=123) +
  scale_color_manual(values=c("blue","black","tomato","green3")); MSAPm_PC1_BayeScEnv.plot

#' ### PC2
#' <a href="#top">Back to top</a>
#+ project_bayescan.MSAPm.PC2
######## PC2 ####
## load BayeScEnv data (Fst table)
MSAPm_PC2_BayeScEnv.data <- tibble(read.table("./data/BayeScEnv_MSAPm_PC2_fst.txt",
                                               header=T)); MSAPm_PC2_BayeScEnv.data
MSAPm_PC2_BayeScEnv.data$ID <- names(data.frame(MSAPm.genind@tab))
# add locus IDs (dye from multiplexing and base-pair position)
MSAPm_PC2_BayeScEnv.data$marker <- names(data.frame(MSAPm.genind@tab))
# replace FAM_AAC_CCT_* with loc
MSAPm_PC2_BayeScEnv.data$marker <- stringr::str_replace(MSAPm_PC2_BayeScEnv.data$marker,
                                                         "MFAM_AAC_CCT_",
                                                         "loc")
# replace VIC_ACG_CAT_* with loc
MSAPm_PC2_BayeScEnv.data$marker <- stringr::str_replace(MSAPm_PC2_BayeScEnv.data$marker,
                                                         "MVIC_ACG_CAT_",
                                                         "loc")
# replace NED_ACC_CTG_* with loc
MSAPm_PC2_BayeScEnv.data$marker <- stringr::str_replace(MSAPm_PC2_BayeScEnv.data$marker,
                                                         "MNED_ACC_CTG_",
                                                         "loc")
# replace PET_AGG_CGA_* with loc
MSAPm_PC2_BayeScEnv.data$marker <- stringr::str_replace(MSAPm_PC2_BayeScEnv.data$marker,
                                                         "MPET_AGG_CGA_",
                                                         "loc")
MSAPm_PC2_BayeScEnv.data$marker # check
# add locus number for x-axis (base-pair value)
MSAPm_PC2_BayeScEnv.data$basepair <- MSAPm_PC2_BayeScEnv.data$marker
# remove FAM_AAC_CCT_* from label
MSAPm_PC2_BayeScEnv.data$basepair <- stringr::str_replace(MSAPm_PC2_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
# remove VIC_ACG_CAT_* from label
MSAPm_PC2_BayeScEnv.data$basepair <- stringr::str_replace(MSAPm_PC2_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
# remove NED_ACC_CTG_* from label
MSAPm_PC2_BayeScEnv.data$basepair <- stringr::str_replace(MSAPm_PC2_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
# remove PET_AGG_CGA_* from label
MSAPm_PC2_BayeScEnv.data$basepair <- stringr::str_replace(MSAPm_PC2_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
MSAPm_PC2_BayeScEnv.data$basepair <- as.numeric(MSAPm_PC2_BayeScEnv.data$basepair)
MSAPm_PC2_BayeScEnv.data$basepair# check
# negative logarithm on the basis of 10
MSAPm_PC2_BayeScEnv.data$log10.qVal <- -log10(MSAPm_PC2_BayeScEnv.data$qval_g)
# add dye label
MSAPm_PC2_BayeScEnv.data$dye <- names(data.frame(MSAPm.genind@tab))
# replace FAM_AAC_CCT[0-9|_]+ with FAM
MSAPm_PC2_BayeScEnv.data$dye <- stringr::str_replace(MSAPm_PC2_BayeScEnv.data$dye,
                                                      "MFAM_AAC_CCT[0-9|_]+",
                                                      "FAM")
# replace VIC_ACG_CAT[0-9|_]+ with FAM
MSAPm_PC2_BayeScEnv.data$dye <- stringr::str_replace(MSAPm_PC2_BayeScEnv.data$dye,
                                                      "MVIC_ACG_CAT[0-9|_]+",
                                                      "VIC")
# replace NED_ACC_CTG[0-9|_]+ with FAM
MSAPm_PC2_BayeScEnv.data$dye <- stringr::str_replace(MSAPm_PC2_BayeScEnv.data$dye,
                                                      "MNED_ACC_CTG[0-9|_]+",
                                                      "NED")
# replace PET_AGG_CGA[0-9|_]+ with FAM
MSAPm_PC2_BayeScEnv.data$dye <- stringr::str_replace(MSAPm_PC2_BayeScEnv.data$dye,
                                                      "MPET_AGG_CGA[0-9|_]+",
                                                      "PET")
MSAPm_PC2_BayeScEnv.data$dye <- as.factor(MSAPm_PC2_BayeScEnv.data$dye)
MSAPm_PC2_BayeScEnv.data$dye # check
MSAPm_PC2_BayeScEnv.data
# subset to the significant ones (PEP_g < PEP_alpha)
MSAPm_PC2_signf.loc <- MSAPm_PC2_BayeScEnv.data[(MSAPm_PC2_BayeScEnv.data$PEP_g<
                                                     MSAPm_PC2_BayeScEnv.data$PEP_alpha),]
MSAPm_PC2_signf.loc$env <- "PC2"
MSAPm_PC2_signf.loc
# and plot
set.seed(123)
MSAPm_PC2_BayeScEnv.plot <- ggplot(MSAPm_PC2_BayeScEnv.data,
                                    aes(x=basepair,
                                        y=log10(PEP_g/PEP_alpha))) +
  geom_point(alpha=0.3,
             size=2) +
  geom_hline(yintercept=0,
             linetype="dashed") +
  labs(title="",
       subtitle="PC2 (explained variation: 32.7%)",
       x="",
       y="") +
  coord_cartesian(ylim=c(-0.2,0.4),xlim=c(50,500)) +
  theme_cowplot()+
  theme(axis.line.y.right=element_line(color="transparent"),
        axis.ticks.y.right=element_blank(),
        axis.text.y.right=element_text(color="transparent"),
        panel.border=element_rect(color="black"),
        legend.position="none") +
  ggrepel::geom_text_repel(data=MSAPm_PC2_signf.loc,
                           aes(x=basepair,
                               y=log10(PEP_g/PEP_alpha),
                               label=marker,
                               color=dye),
                           segment.color="gray80",
                           max.overlaps=50,
                           size=3,
                           direction="both",
                           angle=0,
                           hjust=0,
                           force_pull=0,
                           nudge_y=-0.05-log10(MSAPm_PC2_signf.loc$PEP_g/
                                                     MSAPm_PC2_signf.loc$PEP_alpha),
                           seed=123) +
  scale_color_manual(values=c("tomato","green3","blue","black")); MSAPm_PC2_BayeScEnv.plot

#' ### PC3
#' <a href="#top">Back to top</a>
#+ project_bayescan.MSAPm.PC3
######## PC3 ####
## load BayeScEnv data (Fst table)
MSAPm_PC3_BayeScEnv.data <- tibble(read.table("./data/Data_BayeScEnv_MSAPm_CON_all_PC3_fst.txt",
                                               header=T)); MSAPm_PC3_BayeScEnv.data
MSAPm_PC3_BayeScEnv.data$ID <- names(data.frame(MSAPm.genind@tab))
# add locus IDs (dye from multiplexing and base-pair position)
MSAPm_PC3_BayeScEnv.data$marker <- names(data.frame(MSAPm.genind@tab))
# replace FAM_AAC_CCT_* with loc
MSAPm_PC3_BayeScEnv.data$marker <- stringr::str_replace(MSAPm_PC3_BayeScEnv.data$marker,
                                                         "MFAM_AAC_CCT_",
                                                         "loc")
# replace VIC_ACG_CAT_* with loc
MSAPm_PC3_BayeScEnv.data$marker <- stringr::str_replace(MSAPm_PC3_BayeScEnv.data$marker,
                                                         "MVIC_ACG_CAT_",
                                                         "loc")
# replace NED_ACC_CTG_* with loc
MSAPm_PC3_BayeScEnv.data$marker <- stringr::str_replace(MSAPm_PC3_BayeScEnv.data$marker,
                                                         "MNED_ACC_CTG_",
                                                         "loc")
# replace PET_AGG_CGA_* with loc
MSAPm_PC3_BayeScEnv.data$marker <- stringr::str_replace(MSAPm_PC3_BayeScEnv.data$marker,
                                                         "MPET_AGG_CGA_",
                                                         "loc")
MSAPm_PC3_BayeScEnv.data$marker # check
# add locus number for x-axis (base-pair value)
MSAPm_PC3_BayeScEnv.data$basepair <- MSAPm_PC3_BayeScEnv.data$marker
# remove FAM_AAC_CCT_* from label
MSAPm_PC3_BayeScEnv.data$basepair <- stringr::str_replace(MSAPm_PC3_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
# remove VIC_ACG_CAT_* from label
MSAPm_PC3_BayeScEnv.data$basepair <- stringr::str_replace(MSAPm_PC3_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
# remove NED_ACC_CTG_* from label
MSAPm_PC3_BayeScEnv.data$basepair <- stringr::str_replace(MSAPm_PC3_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
# remove PET_AGG_CGA_* from label
MSAPm_PC3_BayeScEnv.data$basepair <- stringr::str_replace(MSAPm_PC3_BayeScEnv.data$basepair,
                                                           "loc",
                                                           "")
MSAPm_PC3_BayeScEnv.data$basepair <- as.numeric(MSAPm_PC3_BayeScEnv.data$basepair)
MSAPm_PC3_BayeScEnv.data$basepair# check
# negative logarithm on the basis of 10
MSAPm_PC3_BayeScEnv.data$log10.qVal <- -log10(MSAPm_PC3_BayeScEnv.data$qval_g)
# add dye label
MSAPm_PC3_BayeScEnv.data$dye <- names(data.frame(MSAPm.genind@tab))
# replace FAM_AAC_CCT[0-9|_]+ with FAM
MSAPm_PC3_BayeScEnv.data$dye <- stringr::str_replace(MSAPm_PC3_BayeScEnv.data$dye,
                                                      "MFAM_AAC_CCT[0-9|_]+",
                                                      "FAM")
# replace VIC_ACG_CAT[0-9|_]+ with FAM
MSAPm_PC3_BayeScEnv.data$dye <- stringr::str_replace(MSAPm_PC3_BayeScEnv.data$dye,
                                                      "MVIC_ACG_CAT[0-9|_]+",
                                                      "VIC")
# replace NED_ACC_CTG[0-9|_]+ with FAM
MSAPm_PC3_BayeScEnv.data$dye <- stringr::str_replace(MSAPm_PC3_BayeScEnv.data$dye,
                                                      "MNED_ACC_CTG[0-9|_]+",
                                                      "NED")
# replace PET_AGG_CGA[0-9|_]+ with FAM
MSAPm_PC3_BayeScEnv.data$dye <- stringr::str_replace(MSAPm_PC3_BayeScEnv.data$dye,
                                                      "MPET_AGG_CGA[0-9|_]+",
                                                      "PET")
MSAPm_PC3_BayeScEnv.data$dye <- as.factor(MSAPm_PC3_BayeScEnv.data$dye)
MSAPm_PC3_BayeScEnv.data$dye # check
MSAPm_PC3_BayeScEnv.data
# subset to the significant ones (PEP_g < PEP_alpha)
MSAPm_PC3_signf.loc <- MSAPm_PC3_BayeScEnv.data[(MSAPm_PC3_BayeScEnv.data$PEP_g<
                                                     MSAPm_PC3_BayeScEnv.data$PEP_alpha),]
MSAPm_PC3_signf.loc$env <- "PC3"
MSAPm_PC3_signf.loc
# and plot
set.seed(123)
MSAPm_PC3_BayeScEnv.plot <- ggplot(MSAPm_PC3_BayeScEnv.data,
                                    aes(x=basepair,
                                        y=log10(PEP_g/PEP_alpha))) +
  geom_point(alpha=0.3,
             size=2) +
  geom_hline(yintercept=0,
             linetype="dashed") +
  labs(title="",
       subtitle="PC3 (explained variation: 14.4%)",
       x="",
       y="") +
  coord_cartesian(ylim=c(-0.2,0.4),
                  xlim=c(50,500)) +
  theme_cowplot()+
  theme(axis.line.y.right=element_line(color="transparent"),
        axis.ticks.y.right=element_blank(),
        axis.text.y.right=element_text(color="transparent"),
        panel.border=element_rect(color="black"),
        legend.position="none") +
  ggrepel::geom_text_repel(data=MSAPm_PC3_signf.loc,
                           aes(x=basepair,
                               y=log10(PEP_g/PEP_alpha),
                               label=marker,
                               color=dye),
                           segment.color="gray80",
                           max.overlaps=50,
                           size=3,
                           direction="both",
                           angle=0,
                           hjust=0,
                           force_pull=0,
                           nudge_y=-0.05-log10(MSAPm_PC3_signf.loc$PEP_g/
                                                     MSAPm_PC3_signf.loc$PEP_alpha),
                           seed=123) +
  scale_color_manual(values=c("blue","green3","tomato","black")); MSAPm_PC3_BayeScEnv.plot

#' ### Outlier data
#' <a href="#top">Back to top</a>
#+ project_bayescan.MSAPm.dataset
######## Outlier table ####
# combine tables
MSAPm_signf.loc <- tibble(rbind(MSAPm_PC1_signf.loc,
                                 MSAPm_PC2_signf.loc,
                                 MSAPm_PC3_signf.loc)); MSAPm_signf.loc
# save outlier data
write.table(MSAPm_signf.loc,
            row.names=F,
            file="./data/Data_BayeScEnv_MSAPm_Outlier.txt",
            sep="\t")

#' # Figure S9
#' <a href="#top">Back to top</a>
#+ project_figureS9
######## Figure S9 ....................... ####
AFLPMSAP_BayeScEnv_combi <- plot_grid(AFLP_PC1_BayeScEnv.plot,
                                      AFLP_PC2_BayeScEnv.plot,
                                      AFLP_PC3_BayeScEnv.plot,
                                      MSAPm_PC1_BayeScEnv.plot,
                                      MSAPm_PC2_BayeScEnv.plot,
                                      MSAPm_PC3_BayeScEnv.plot,
                                      MSAPn_PC1_BayeScEnv.plot,
                                      MSAPn_PC2_BayeScEnv.plot,
                                      MSAPn_PC3_BayeScEnv.plot,
                                      ncol=3,
                                      nrow=3,
                                      label_size=18,
                                      labels=c('A','B','C','D',
                                               'E','F',"G","H","I")) +
  theme(plot.margin=unit(c(1,1,1,1),"cm"))
# save as png
ggsave(AFLPMSAP_BayeScEnv_combi,
       file="./data/FigureS9_Eckert_et_al_2022_BayeScEnv_GenomeScan.png",
       dpi=300,
       width=12,
       height=12)
# save as tiff
ggsave(AFLPMSAP_BayeScEnv_combi,
       file="./data/FigureS9_Eckert_et_al_2022_BayeScEnv_GenomeScan.TIFF",
       dpi=300,
       width=12,
       height=12,
       device=grDevices::tiff)

#' # Session info
#' <a href="#top">Back to top</a>
#+ Session.info
sessionInfo()
#' <a href="#top">Back to top</a>
######## Session info .................. ####