#' ---
#' title: <center><b>Markdown document from&colon;</b><br>Traces of Genetic but Not Epigenetic Adaptation in the Invasive Goldenrod _Solidago canadensis_ Despite the Absence of Population Structure</center>
#' pagetitle: RMarkdown document from:&nbsp;Eckert&nbsp;et&nbsp;al.&nbsp;(2022)
#' subtitle: <center>doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.3389/fevo.2022.856453">10.3389/fevo.2022.856453</a></center>
#' author: <center>Eckert, S., Herden, J., Stift, M., Durka, W., van Kleunen, M., & Joshi, J.</center>
#' date: <center>`r Sys.Date()`</center>
#' abstract: <p align="justify">This RMarkdown script belongs
#'   to a series of scripts generated by Silvia Eckert as part of
#'   the statistical analysis for the above-mentioned manuscript.
#'   The data underlying the applied R code can be found in the ZENODO
#'   repository and contains genetic (AFLP) and epigenetic (MSAP) markers
#'   from offspring of 25 _Solidago canadensis_ populations sampled along a
#'   latitudinal gradient in Central Europe. This particular RMarkdown script
#'   is part 02/06 and applies admixture coefficient estimation on the
#'   AFLP dataset. <b>Please cite this
#'   script as follows:</b></p><br><p>Eckert, S., Herden, J.,
#'   Stift, M., Durka, W., van Kleunen, M., & Joshi, J. (2022). Data From&colon;
#'   Traces of Genetic but Not Epigenetic Adaptation in the Invasive
#'   Goldenrod _Solidago canadensis_ Despite the Absence of Population
#'   Structure. _Zenodo_. doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.5281/zenodo.6388135">10.5281/zenodo.6388135</a></center></p>
#' geometry: margin=2cm
#' output:
#'   html_document:
#'      code_folding: show
#'      keep_md: FALSE
#'      theme: flatly
#'      highlight: textmate
#'      df_print: paged
#'      toc: true
#'      toc_float: true
#' ---
#' 

#'
#'```{r setup, include = FALSE}
#'knitr::opts_chunk$set(eval=FALSE, cache=FALSE, warning=FALSE)
#'```

#' # Packages
#' <a href="#top">Back to top</a>
#+ project_packages, results='hide', message=FALSE, warning=FALSE
########### packages ...................... ####
# install.packages("name_of_package") # install necessary packages
# install knitr to save this script as html output using RStudio with Ctrl+Shift+K (Windows & Linux) or Command+Shift+K (macOS)
# install.packages("knitr") 
# getwd() # get current working directory
# setwd() # set working directory
# create folder for datasets to be stored to get this RMarkdown script running
dir.create("./data",
           showWarnings=F)

#' # Load data
#' <a href="#top">Back to top</a>
#+ project_load.data
########### load data ....................... ####
source("RMarkdown_Eckert_et_al_2022_LEA_01.R")

#' # Population structure
#' <a href="#top">Back to top</a>
#+ project_LEA
######## LEA ................................ ####
# Estimation of individual ancestry coefficients using R package LEA
#' ## AFLP
#+ project_LEA.AFLP
######## AFLP .............................. ####
#' ### SNMF
#+ project_LEA.AFLP.snmf
######## SNMF ####
# convert struct files to geno and lfmm
# ploidy = 1, because dominant data (one column per marker)
struct2geno(input.file="./data_LEA/Input_AFLP_C.struct",
            ploidy=1,
            FORMAT=1,
            extra.row=1,
            extra.column=2) # 358 loci
# rename if necessary
#file.rename(from="./data_LEA/Input_AFLP_C.struct.geno",
#            to="./data_LEA/Input_AFLP_C.geno")
#file.rename(from="./data_LEA/Input_AFLP_C.struct.lfmm",
#            to="./data_LEA/Input_AFLP_C.lfmm")
# evaluate population structure
set.seed(123)
AFLP_C.pca=pca("./data_LEA/Input_AFLP_C.lfmm",
                 center=T,
                 scale=T); plot(AFLP_C.pca)
# run LEA
# takes up to 40 minutes on a regular laptop depending on the number of CPU cores used
AFLP_C.project=NULL # start new project
AFLP_C.project=snmf("RawData_LEA/Input_AFLP_C.geno",
                      K=1:11,
                      seed=123,
                      CPU=3,
                      ploidy=2,
                      entropy=T,
                      repetitions=20,
                      iterations=100000,
                      project="new")
# re-load project after finishing
# AFLP_C.project = load.snmfProject("RawData_LEA/AFLP_C.snmfProject")
# choose the number of ancestry coefficient K

#' ### Cross validation
#' <a href="#top">Back to top</a>
#+ project_LEA.AFLP.snmf_crossVal
######## cross validation ####
# ggplot
AFLP_C.snmf_data <- data.frame()
for (i in 1:length(AFLP_C.project@runs)){AFLP_C.snmf_data <- rbind(AFLP_C.snmf_data,
                                                  c(AFLP_C.project@runs[[i]]@K,
                                                    AFLP_C.project@runs[[i]]@run,
                                                    AFLP_C.project@runs[[i]]@crossEntropy))}
colnames(AFLP_C.snmf_data) <- c("K","run","crossEntropy")
AFLP_C.snmf_data$K <- as.factor(AFLP_C.snmf_data$K); tibble(AFLP_C.snmf_data)
AFLP_C.snmf_data_minCV <- aggregate(.~K,
                                    AFLP_C.snmf_data,
                                    min); AFLP_C.snmf_data_minCV
# plot
AFLP_crossVal <- ggplot(data=AFLP_C.snmf_data_minCV,
                        aes(x=K,
                            y=crossEntropy,
                            group=1)) +
  geom_line(alpha=0.3) +
  geom_point(shape=21,
             fill="gray60",
             size=4) +
  theme_bw() +
  labs(x=expression(paste("Number of ancestral populations"~italic("(K)"))),
       y="Cross entropy\n") +
  geom_vline(xintercept=2,
             linetype=2,
             col="gray60") +
  annotate(geom="text",
           x=7.5,
           y=0.4185,
           hjust=0,
           vjust=1,
           label=expression(paste(italic(n)[repetitions]~" = 20"))) +
  annotate(geom="text",
           x=7.5,
           y=0.417,
           hjust=0,
           vjust=1,
           label=expression(paste(italic(n)[iterations]~" = 100,000"))) +
  annotate(geom="text",
           x=7.5,
           y=0.4155,
           hjust=0,
           vjust=1,
           label=expression(paste(italic(K)[final]~" = 2")))+
  theme(panel.grid.major=element_line(color="gray97"),
        plot.margin=unit(c(1,0.5,1,0.5),"cm"),
        axis.title.x=element_text(size=12),
        axis.text.x=element_text(size=12),
        axis.title.y=element_text(size=12),
        axis.text.y=element_text(size=12)); AFLP_crossVal

#' ### Population structure
#' <a href="#top">Back to top</a>
#+ project_LEA.AFLP.snmf.stacked_barplot
######## population structure ####
# STRUCTURE-like barplot for first look
AFLP_C.best = which.min(cross.entropy(AFLP_C.project,K=2))
AFLP_C.q = Q(AFLP_C.project,K=2,run=AFLP_C.best)
# save Q matrix
AFLP_C.qmatrix <- tibble(data.frame(uniqueID=row.names(strata(AFLP_C.genind)),
                                    population_ID=strata(AFLP_C.genind)[7],
                                    AFLP_C.q)); AFLP_C.qmatrix
# prepare data
AFLP_C.stacked <- reshape2::melt(AFLP_C.qmatrix); tibble(AFLP_C.stacked)
colnames(AFLP_C.stacked)[3:4] <- c("cluster","proportion")
AFLP_C.stacked$cluster <- as.factor(as.numeric(gsub("V","",
                                                    AFLP_C.stacked$cluster)))
AFLP_C.stacked$treatment <- "CON"
AFLP_C.stacked$treatment <- as.factor(AFLP_C.stacked$treatment)
AFLP_C.stacked$populationID <- factor(AFLP_C.stacked$populationID,
                                      levels=as.character(1:25)); tibble(AFLP_C.stacked)
# labeller
treatment_labeller <- c(
  `CON`="Control",
  `ZEB`="Zebularine"
  )
# stacked barplot
AFLP_C.snmf.plot <- ggplot(AFLP_C.stacked,
                           aes(x=uniqueID,
                               y=proportion,
                               fill=cluster)) +
  geom_bar(position="fill",
           stat="identity",
           width=1.2) +
  scale_y_continuous(labels=percent_format(),
                     breaks=c(0.25,0.75),
                     expand=c(0,0)) + 
  facet_grid(treatment ~ populationID,
             scales="free_x",
             space="free_x",
             shrink=T,
             labeller=labeller(treatment=treatment_labeller)) +
  labs(title="AFLP",
       x=expression('Latitude [49.63 - 54.11 '*degree*N*']'),
       y=expression("Probability ("*italic(K)~"= 2)")) +
  theme_cowplot() +
  theme(plot.margin=unit(c(1,1,0.5,1),"lines"),
        plot.title=element_text(size=20),
        panel.spacing=unit(.1,"line"),
        strip.text=element_text(size=12),
        strip.background=element_rect(linetype="solid",
                                        fill="transparent",
                                        color="black",
                                        size=0.5),
        legend.position="none",
        axis.title.y=element_text(size=12),
        axis.line.x=element_blank(),
        axis.line.y=element_blank(),
        axis.title.x=element_text(size=12),
        axis.text.y=element_text(size=12),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  scale_fill_colorblind() +
  scale_x_discrete(breaks=c(0.1,5),
                   labels=c("a","b")) +
  coord_cartesian(clip="off"); AFLP_C.snmf.plot

#' ### Cluster variation
#' <a href="#top">Back to top</a>
#+ project_LEA.AFLP.snmf.cluster_Var
######## cluster variation ####
AFLP_C.qmatrix_long <- reshape2::melt(AFLP_C.qmatrix,
                                      by="populationID")
colnames(AFLP_C.qmatrix_long)[3:4] <- c("cluster","proportion")
tibble(AFLP_C.qmatrix_long)
# aggreagate population means
AFLP_C.qmatrix_agg <- aggregate(AFLP_C.qmatrix_long$proportion,
                                by=list(AFLP_C.qmatrix_long$populationID,
                                        AFLP_C.qmatrix_long$cluster),
                                FUN=mean)  # aggregate
colnames(AFLP_C.qmatrix_agg) <- c("populationID","cluster","proportion_avg")
AFLP_C.qmatrix_agg$populationID <- factor(AFLP_C.qmatrix_agg$populationID,
                                          levels=as.character(1:25))
# create labeller
clust_labeller <- c(
  `V1`="Cluster 1",
  `V2`="Cluster 2",
  `V3`="Cluster 3",
  `V4`="Cluster 4",
  `V5`="Cluster 5",
  `V6`="Cluster 6",
  `V7`="Cluster 7")
# plot
AFLP_clusterVar <- ggplot(AFLP_C.qmatrix_agg,
                          aes(x=populationID,
                              y=proportion_avg,
                              group=cluster,
                              fill=cluster)) +
  geom_area(aes(x=populationID,
                y=proportion_avg)) +
  facet_grid(.~cluster,
             labeller=labeller(cluster=clust_labeller)) +
  coord_flip()+
  labs(x="Population",
       y=expression(paste("Average proportion of"~italic(K)*"cluster assignment per population"))) +
  ggthemes::scale_fill_colorblind() +
  theme_bw() +
  theme(axis.text.x=element_text(angle=65,
                                   vjust=0.6,
                                   size=12),
        legend.position="none",
        plot.margin=unit(c(1,0.5,1,1),"cm"),
        axis.title.x=element_text(size=12),
        axis.title.y=element_text(size=12),
        axis.text.y=element_text(size=12)); AFLP_clusterVar

#' # Figure S10
#' <a href="#top">Back to top</a>
#+ project_LEA.AFLP.snmf_figureS10
######## Figure S10 ####
AFLP_SNMFcombi <- ggarrange(AFLP_C.snmf.plot,
                            ggarrange(AFLP_crossVal,
                                      AFLP_clusterVar,
                                      ncol=2,
                                      font.label=list(size=20),
                                      labels=c("B","C")),
                            nrow=2,
                            font.label=list(size=20),
                            labels="A") +
  theme(plot.margin=unit(c(1,1,1,1),"cm")); AFLP_SNMFcombi
# save as png
ggsave(AFLP_SNMFcombi,
       file="./data/FigureS10_Eckert_et_al_2022_LEA_snmf_AFLP.png",
       dpi=300,
       width=15,
       height=10)
# save as tiff
ggsave(AFLP_SNMFcombi,
       file="./data/FigureS10_Eckert_et_al_2022_LEA_snmf_AFLP.TIFF",
       dpi=300,
       width=15,
       height=10,
       device=grDevices::tiff)

#' # Session info
#' <a href="#top">Back to top</a>
#+ Session.info
######## Session info ###
sessionInfo()
#' <a href="#top">Back to top</a>
######## Session info .................. ####