#' ---
#' title: <center><b>Markdown document from&colon;</b><br>Traces of Genetic but Not Epigenetic Adaptation in the Invasive Goldenrod _Solidago canadensis_ Despite the Absence of Population Structure</center>
#' pagetitle: RMarkdown document from:&nbsp;Eckert&nbsp;et&nbsp;al.&nbsp;(2022)
#' subtitle: <center>doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.3389/fevo.2022.856453">10.3389/fevo.2022.856453</a></center>
#' author: <center>Eckert, S., Herden, J., Stift, M., Durka, W., van Kleunen, M., & Joshi, J.</center>
#' date: <center>`r Sys.Date()`</center>
#' abstract: <p align="justify">This RMarkdown script belongs
#'   to a series of scripts generated by Silvia Eckert as part of
#'   the statistical analysis for the above-mentioned manuscript.
#'   The data underlying the applied R code can be found in the ZENODO
#'   repository and contains genetic (AFLP) and epigenetic (MSAP) markers
#'   from offspring of 25 _Solidago canadensis_ populations sampled along a
#'   latitudinal gradient in Central Europe. This particular RMarkdown script
#'   is part 03/03 and applies logistic mixed-effects models on AFLP and MSAP 
#'   datasets. <b>Please cite this
#'   script as follows:</b></p><br><p>Eckert, S., Herden, J.,
#'   Stift, M., Durka, W., van Kleunen, M., & Joshi, J. (2022). Data From&colon;
#'   Traces of Genetic but Not Epigenetic Adaptation in the Invasive
#'   Goldenrod _Solidago canadensis_ Despite the Absence of Population
#'   Structure. _Zenodo_. doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.5281/zenodo.6388135">10.5281/zenodo.6388135</a></center></p>
#' geometry: margin=2cm
#' output:
#'   html_document:
#'      code_folding: show
#'      keep_md: FALSE
#'      theme: flatly
#'      highlight: textmate
#'      df_print: paged
#'      toc: true
#'      toc_float: true
#' ---
#' 

#'
#'```{r setup, include = FALSE}
#'knitr::opts_chunk$set(eval=FALSE, cache=FALSE, warning=FALSE)
#'```

#' # Packages
#' <a href="#top">Back to top</a>
#+ project_packages, results='hide', message=FALSE, warning=FALSE
########### packages ...................... ####
# install.packages("name_of_package") # install necessary packages
# install knitr to save this script as html output using RStudio with Ctrl+Shift+K (Windows & Linux) or Command+Shift+K (macOS)
# install.packages("knitr") 
# getwd() # get current working directory
# setwd() # set working directory
# create folder for datasets to be stored to get this RMarkdown script running
dir.create("./data",
           showWarnings=F)
# add necessary libraries
library(lme4)
library(lme4)
library(ggplot2)
library(cowplot)
library(tibble)
library(dplyr)
library(xlsx)
library(ImportExport)
library(sjmisc)
library(ggeffects)
library(ggpubr)
library(PerformanceAnalytics)

#' # Functions
#' <a href="#top">Back to top</a>
#+ project_load.functions
########## functions .......................####
# @param file character string with the path to the file to source.
# @param lines numeric vector of lines to source in \code{file}.
source_lines <- function(file,lines){
  source(textConnection(readLines(file)[lines]))}

#' # Load data
#' <a href="#top">Back to top</a>
#+ project_load.data
########### load data ....................... ####
source_lines("RMarkdown_Eckert_et_al_2022_LogMM_01.R",40:89) # loc58
source_lines("RMarkdown_Eckert_et_al_2022_LogMM_02.R",c(40:209,448:565)) # loc135
# check models
# loc58 (Climate)
summary(logMM.loc58)
# MEMGENE (Autocorr)
summary(logMM.loc135)
# load MEMGENE variables from MEMGENE analysis
MEMGENEs <- tibble(read.table("./data/Data_MEMGENE_AFLP.txt",
                              header=T)); MEMGENEs

#' # Plot models
#' <a href="#top">Back to top</a>
#+ project_plot.models
########### plot models ................... ####
#' ## Loc58
#+ project_plot.models_loc58
########### loc58 ####
# plot
loc58_mod0_predict <- ggpredict(logMM.loc58,
                                c("PC1_scaled[all]","treatment"))
set.seed(123)
loc58_mod0_plot <- ggplot(loc58_mod0_predict,
                          aes(x,predicted)) +
  geom_rug(data=logMM.loc58@frame[logMM.loc58@frame$loc58>0.5,],
           sides="t",
           position=position_jitter(w=0.05,h=0),
           length=unit(0.05,"npc"),
           size=0.1,
           aes(y=loc58,
               x=PC1_scaled,
               color=treatment)) +
  geom_rug(data=logMM.loc58@frame[logMM.loc58@frame$loc58<0.5,],
           sides="b",
           position=position_jitter(w=0.05,h=0),
           length=unit(0.05,"npc"),
           size=0.1,
           aes(y=loc58,
               x=PC1_scaled,
               color=treatment)) +
  geom_line(aes(linetype=group,
                color=group)) +
  geom_ribbon(aes(ymin=conf.low,
                  ymax=conf.high,
                  fill=group),
              alpha=0.15) +
  scale_y_continuous(breaks=c(0,0.5,1),
                     labels=c(0,50,100)) +
  scale_linetype_manual(values=c("longdash","longdash"),
                        guide="none") +
  ggthemes::scale_color_colorblind() +
  ggthemes::scale_fill_colorblind() +
  coord_cartesian(ylim=c(0,1))+
  scale_x_continuous(limits=c(0.7,5),
                     breaks=c(1,2,3,4),
                     labels=c(1,2,3,4),
                     expand=c(0,0)) +
  theme_cowplot() +
  theme(legend.position="top",
        legend.text=element_text(size=8),
        legend.title=element_text(size=8),
        panel.border=element_rect(colour="black",
                                    fill=NA,
                                    size=0.5),
        axis.title=element_text(size=8),
        plot.title=element_text(size=8),
        plot.subtitle=element_text(size=6),
        axis.text=element_text(size=8),
        axis.line=element_blank()) +
  scale_color_manual(labels=c(expression(paste("Main effect significant ("*italic(p)~"< 0.05)")),
                                expression(paste("Interaction significant ("*italic(p)~"< 0.05)"))),
                     values=c("black","#e69f00")) +
  scale_fill_manual(labels=c("Control","Zebularine"),
                    values=c("black","#e69f00"),
                    guide=guide_legend(title="")) +
  guides(color=guide_legend(title="",
                              override.aes=list(linetype=c(2,1),
                                                  color="black")))+
  labs(title="AFLP: loc58",
       subtitle="PC1 **\nPC2 n.s.\nZebularine n.s.\nInteraction with Zebularine n.s.",
       x="Principal component axis 1 (PC1)",
       y="Probability [%]"); loc58_mod0_plot

#' ## loc135
#+ project_plot.models_loc135
########### loc135 ####
# plot
loc135_mod0_predict <- ggpredict(logMM.loc135,
                                 c("MEMG1_rescaled[all]","treatment"))
set.seed(123)
loc135_mod0_plot <- ggplot(loc135_mod0_predict,
                           aes(x,predicted)) +
  geom_rug(data=logMM.loc135@frame[logMM.loc135@frame$loc135>0.5,],
           sides="t",
           position=position_jitter(w=0.05,h=0),
           length=unit(0.05,"npc"),
           size=0.1,
           aes(y=loc135,
               x=MEMG1_rescaled,
               color=treatment)) +
  geom_rug(data=logMM.loc135@frame[logMM.loc135@frame$loc135<0.5,],
           sides="b",
           position=position_jitter(w=0.05,h=0),
           length=unit(0.05,"npc"),
           size=0.1,
           aes(y=loc135,
               x=MEMG1_rescaled,
               color=treatment)) +
  geom_line(aes(linetype=group,
                color=group)) +
  geom_ribbon(aes(ymin=conf.low,
                  ymax=conf.high,
                  fill=group),
              alpha=0.15) +
  scale_y_continuous(breaks=c(0,0.5,1),
                     labels=c(0,50,100)) +
  scale_linetype_manual(values=c("solid","solid"),
                        guide="none") +
  ggthemes::scale_color_colorblind() +
  ggthemes::scale_fill_colorblind() +
  coord_cartesian(ylim=c(0,1)) +
  scale_x_continuous(limits=c(0,3.25),
                     breaks=c(0,1,2,3),
                     labels=c(0,1,2,3),
                     expand=c(0,0)) +
  theme_cowplot() +
  theme(legend.position="top",
        legend.text=element_text(size=8),
        legend.title=element_text(size=8),
        panel.border=element_rect(colour="black",
                                  fill=NA,
                                  size=0.5),
        axis.title=element_text(size=8),
        plot.title=element_text(size=8),
        plot.subtitle=element_text(size=6),
        axis.text=element_text(size=8),
        axis.line=element_blank()) +
  scale_color_manual(labels=c(expression(paste("Main effect significant ("*italic(p)~"< 0.05)")),
                                expression(paste("Interaction significant ("*italic(p)~"< 0.05)"))),
                     values=c("black","#e69f00")) +
  scale_fill_manual(labels=c("Control","Zebularine"),
                    values=c("black","#e69f00"),
                    guide=guide_legend(title="")) +
  guides(color=guide_legend(title="",
                              override.aes=list(linetype=c(2,1),
                                                  color="black")))+
  labs(title="MSAP-n: loc135",
       subtitle="Main factors n.s.\nMEMGENE1 x Zebularine *\nMEMGENE2 x Zebularine n.s.\nMEMGENE3 x Zebularine n.s.",
       x=expression(paste("Spatial genetic neighbourhood (MEMGENE1)")),
       y=""); loc135_mod0_plot

#' # Figure 4
#' <a href="#top">Back to top</a>
#+ project_plot.models_figure4
########## Figure 4 .......................... ####
# combine
logMM_plot_combo <- ggarrange(loc58_mod0_plot,
                              loc135_mod0_plot,
                              ncol=2,
                              nrow=1,
                              labels=c("A","B"),
                              font.label=list(size=10),
                              heights=c(1,1),
                              common.legend=T,
                              legend="none"); logMM_plot_combo
# extract legend
legend_plot_combo <- get_legend(loc135_mod0_plot +
                                  theme(legend.direction="horizontal",
                                        legend.text=element_text(size=6),
                                        legend.justification="center",
                                        legend.box.just="top"))
# add to plots
modplot_combo_with_legend <- plot_grid(logMM_plot_combo,
                                       legend_plot_combo,
                                       ncol=1,
                                       rel_heights=c(1,.05)) +
  theme(plot.margin=unit(c(1,1,1,1),"cm"))
# save as png
ggsave(modplot_combo_with_legend,
       file="./data/Figure4_Eckert_et_al_2022_LogMM.png",
       dpi=300,
       width=6,
       height=4)
# save as tiff
ggsave(modplot_combo_with_legend,
       file="./data/Figure4_Eckert_et_al_2022_LogMM.TIFF",
       dpi=300,
       width=6,
       height=4,
       device=grDevices::tiff)

#' # Figure S3
#' <a href="#top">Back to top</a>
#+ project_plot.correlation_figureS3
########## Figure S3 ....................... ####
df_memgenes <- MEMGENEs; df_memgenes
# save as PNG
png(filename="./data/FigureS3_Eckert_et_al_2022_MEMGENEs_CorrMatrix.png",
    res=300,
    width=14,
    height=14,
    units="cm")
chart.Correlation(df_memgenes,
                  histogram=TRUE,
                  pch=19)
graphics.off()
# save as TIFF
tiff(filename="./data/FigureS3_Eckert_et_al_2022_MEMGENEs_CorrMatrix.TIFF",
     res=300,
     width=14,
     height=14,
     units="cm")
chart.Correlation(df_memgenes,
                  histogram=TRUE,
                  pch=19)
graphics.off()

#' # Session info
#' <a href="#top">Back to top</a>
#+ Session.info
sessionInfo()
#' <a href="#top">Back to top</a>
######## Session info .................. ####