#' ---
#' title: <center><b>Markdown document from&colon;</b><br>Traces of Genetic but Not Epigenetic Adaptation in the Invasive Goldenrod _Solidago canadensis_ Despite the Absence of Population Structure</center>
#' pagetitle: RMarkdown document from:&nbsp;Eckert&nbsp;et&nbsp;al.&nbsp;(2022)
#' subtitle: <center>doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.3389/fevo.2022.856453">10.3389/fevo.2022.856453</a></center>
#' author: <center>Eckert, S., Herden, J., Stift, M., Durka, W., van Kleunen, M., & Joshi, J.</center>
#' date: <center>`r Sys.Date()`</center>
#' abstract: <p align="justify">This RMarkdown script belongs
#'   to a series of scripts generated by Silvia Eckert as part of
#'   the statistical analysis for the above-mentioned manuscript.
#'   The data underlying the applied R code can be found in the ZENODO
#'   repository and contains genetic (AFLP) and epigenetic (MSAP) markers
#'   from offspring of 25 _Solidago canadensis_ populations sampled along a
#'   latitudinal gradient in Central Europe. This particular RMarkdown script
#'   applies the MSAPcalc.R diagnostics procedure from Schulz, Eckstein, &
#'   Durka (2013; doi&colon; <a target="_blank" rel="noopener noreferrer"
#'   href="https://www.doi.org/10.1111/1755-0998.12100">10.1111/1755-0998.12100</a>).
#'   Diagnostics were applied on all siblings regardless of whether they were
#'   present in either of the treatment levels. <b>Please cite this
#'   script as follows:</b></p><br><p>Eckert, S., Herden, J.,
#'   Stift, M., Durka, W., van Kleunen, M., & Joshi, J. (2022). Data From&colon;
#'   Traces of Genetic but Not Epigenetic Adaptation in the Invasive
#'   Goldenrod _Solidago canadensis_ Despite the Absence of Population
#'   Structure. _Zenodo_. doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.5281/zenodo.6388135">10.5281/zenodo.6388135</a></center></p>
#' geometry: margin=2cm
#' output:
#'   html_document:
#'      code_folding: show
#'      keep_md: FALSE
#'      theme: flatly
#'      highlight: textmate
#'      df_print: paged
#'      toc: true
#'      toc_float: true
#' ---
#' 

#'
#'```{r setup, include = FALSE}
#'knitr::opts_chunk$set(eval=FALSE, cache=FALSE, warning=FALSE)
#'```

#' # Packages
#' <a href="#top">Back to top</a>
#+ project_packages, results='hide', message=FALSE, warning=FALSE
########### packages ...................... ####
# install.packages("name_of_package") # install necessary packages
# install knitr to save this script as html output using RStudio with Ctrl+Shift+K (Windows & Linux) or Command+Shift+K (macOS)
# install.packages("knitr") 
# getwd() # get current working directory
# setwd() # set working directory
# create folder for datasets to be stored to get this RMarkdown script running
dir.create("./data",
           showWarnings=F)
# add necessary libraries
library(rstatix)
library(labdsv)
library(stringr)
library(ggpubr)
library(ggthemes)
library(cowplot)
library(reshape2)
library(lme4)

#' # Load data
#' <a href="#top">Back to top</a>
#+ project_load.data
########### load data .......................... ####
# Premise: Usage of MSAPcalc_data.txt and application of "Mixed Scoring 1"
# this was also applied to siblings present in both treatment levels (Figure S5)
# scheme from Schulz, Eckstein, & Durka (2013).
# Input file format needed from function Extract_MSAP_epigenotypes():
# column 1 = populationID
# column 2 = sampleID
# column 3 = restriction_enzyme "H" or "M"
# columns 4 to n = 0/1 for presence/absence of marker bands
# row 1 = table head containing column names (see above)
# rows 2 to 2*N + 1 = data
# --::
# populationID  sampleID  restriction_enzyme  marker_1  marker_2
# 1             1         H                   1         1
# 1             1         M                   0         1
# 1             2         H                   1         0
# 1             2         M                   1         1
# 2             3         H                   0         0
# 2             3         M                   1         1
# 2             4         H                   0         1
# 2             4         M                   1         0
df_epi <- tibble(read.table(paste0(data_path,
                                   "EckertHerdenStiftDurkavanKleunenJoshi_2022_FrontEcolEvol_MSAP_scoring_data_mix1.txt"),
                            header=T)); df_epi
df_descr <- tibble(read.table(paste0(data_path,
                                     "MSAP_msapcalc_Mix1_diagnostics.txt"),
                              header=T,
                              skip=1)); df_descr
# extract both epigenotypes (M = methylated and u = non-methylated)
df_epi.u <- data.frame(df_epi[,c(1:2)],
                       df_epi[,grepl("u",names(df_epi))]); names(df_epi.u)
df_epi.m <- data.frame(df_epi[,c(1:2)],
                       df_epi[,grepl("M",names(df_epi))]); names(df_epi.m)
# split population variable into latitude, populationID and treatemnt
names(df_descr)
df_descrdata <- tibble(data.frame(str_split_fixed(df_descr$PopID, "_", 3),
                                  df_descr[,-1]))
colnames(df_descrdata)[1:3] <- c("lat","treatment","popID"); df_descrdata

#' # t-Tests
#' <a href="#top">Back to top</a>
#+ project_ttest
########### t-tests ............................... ####
# prepare data
MSAPdescr.u <- df_descrdata[,c(1:3,20,22:25)]; names(MSAPdescr.u)
MSAPdescr.m <- df_descrdata[,c(1:3,13,15:18)]; names(MSAPdescr.m)
MSAPdescr.u$epigenetics <- "unmethylated"
MSAPdescr.m$epigenetics <- "methylated"
colnames(MSAPdescr.u)[4:8] <- c("N_markers_pop",
                                "Pc_markers_poly",
                                "Mean_N_1scores",
                                "N_private_markers",
                                "Shannon_diversity"); names(MSAPdescr.u)
colnames(MSAPdescr.m)[4:8] <- c("N_markers_pop",
                                "Pc_markers_poly",
                                "Mean_N_1scores",
                                "N_private_markers",
                                "Shannon_diversity"); names(MSAPdescr.m)
# merged data frames
df <- rbind(MSAPdescr.u, MSAPdescr.m); names(df)
# melt data frame
dfmelt <- melt(df[,c(2:6,8:9)],
               c("popID", "treatment",'epigenetics')); tibble(dfmelt)
# split by treatment
dfmeltC <- dfmelt[dfmelt$treatment == "CON",]
dfmeltZ <- dfmelt[dfmelt$treatment == "ZEB",]
# wrangle data frame
df_diagnostics <- data.frame(dfmeltC[,-c(2,5)], CON = dfmeltC[,5], ZEB = dfmeltZ[,5])
colnames(df_diagnostics)[3] <- "diagnostics"; tibble(df_diagnostics)
# removed population 21 because there is only one individual
dfmelt <- dfmelt[!dfmelt$popID==21,]

#' ## Data
#+ project_ttest.prepare_data
########### data ####
# data
dftibble <- dfmelt
colnames(dftibble)[4] <- 'index_type'
colnames(dftibble)[2] <- 'Treatment'
colnames(dftibble)[5] <- 'Value'
dftibble$Treatment <- factor(dftibble$Treatment,
                             levels=c('CON', 'ZEB'))
dftibble$epigenetics <- as.factor(dftibble$epigenetics)
dftibble$index_type <- as.factor(dftibble$index_type)
levels(dftibble$epigenetics) <- list("MSAP-m"='methylated',
                                     'MSAP-n'='unmethylated')
levels(dftibble$Treatment) <- list("Control"='CON',
                                   'Zebularine'='ZEB')
dftibble <- tibble(dftibble)
dftibble <- split(dftibble, dftibble$index_type)
dftibble
# split
dftibble_a <- rbind(dftibble$N_markers_pop,
                    dftibble$Pc_markers_poly); dftibble_a
dftibble_b <- rbind(dftibble$Mean_N_1scores); dftibble_b
dftibble_c <- rbind(dftibble$Shannon_diversity); dftibble_c
# drop unnecessary levels
dftibble_a$index_type <- droplevels(dftibble_a$index_type)
dftibble_b$index_type <- droplevels(dftibble_b$index_type)
dftibble_c$index_type <- droplevels(dftibble_c$index_type)

#' ## Figure S4
#' <a href="#top">Back to top</a>
#+ project_ttest.figureS4
########### Figure S4 ............................ ####
# labeller
labeller_a <- c(
  `N_markers_pop` = "# Loci per Population",
  `Pc_markers_poly` = "Polymorphic loci [%]")
labeller_b <- c(
  `Mean_N_1scores` = "Average # of present scores")
labeller_c <- c(
  `Shannon_diversity` = "Shannon~diversity~italic(H[S])")
# boxplot
p1 <- ggplot(dftibble_a,
             aes(x=Treatment, y=Value, group=Treatment))+
  geom_boxplot(aes(fill=Treatment), key_glyph = 'rect')+
  scale_y_continuous(limits=c(0,180))+
  labs(y="Population-level values (n = 25)") +
  theme_bw()+
  theme(strip.background.y = element_blank(),
        strip.text.y = element_blank(),
        legend.position = 'top') +
  facet_grid(cols=vars(index_type), rows=vars(epigenetics), scales = 'free_y',
             labeller = labeller(index_type  = as_labeller(labeller_a))) +
  stat_pvalue_manual(stat.test_a, hide.ns=F) +
  scale_fill_colorblind(name=NULL); p1
p2 <- ggplot(dftibble_b,
             aes(x=Treatment, y=Value, group=Treatment))+
  geom_boxplot(aes(fill=Treatment))+
  scale_y_continuous(limits=c(0,4))+
  theme_bw()+
  labs(y=NULL)+
  theme(strip.background.y = element_blank(),
        strip.text.y = element_blank(),
        legend.position = 'top',
        legend.text = element_blank(),
        legend.key = element_blank(),
        legend.title = element_blank()) +
  facet_grid(cols=vars(index_type), rows=vars(epigenetics), scales = 'free_y',
             labeller = labeller(index_type  = as_labeller(labeller_b))) +
  stat_pvalue_manual(stat.test_b, hide.ns=F) +
  scale_fill_colorblind()+
  guides(fill=guide_legend(override.aes=list(size=0,
                                             color='transparent',
                                             fill='transparent'))); p2
p3 <- ggplot(dftibble_c,
             aes(x=Treatment, y=Value, group=Treatment))+
  geom_boxplot(aes(fill=Treatment))+
  scale_y_continuous(limits=c(0,0.8))+
  theme_bw()+
  labs(y=NULL)+
  theme(legend.position = 'top',
        legend.text = element_blank(),
        legend.key = element_blank(),
        legend.title = element_blank()) +
  facet_grid(cols=vars(index_type), rows=vars(epigenetics), scales = 'free_y',
             labeller = labeller(index_type  = as_labeller(labeller_c,
                                                           label_parsed))) +
  stat_pvalue_manual(stat.test_c, hide.ns=F) +
  scale_fill_colorblind()+
  guides(fill=guide_legend(override.aes=list(size=0,
                                             color='transparent',
                                             fill='transparent'))); p3
# combine
box_combi <- plot_grid(p1, p3, nrow=1, rel_widths = c(1.5,1,1),
                       labels=c('A','B')); box_combi
# save as png
ggsave(box_combi,
       file=paste0(figure_path, "MSAP_diagnostics_boxplots.png"),
       dpi=300, width=15, height=14, units="cm")
# save as tiff
ggsave(box_combi,
       file=paste0(figure_path, "MSAP_diagnostics_boxplots.TIFF"),
       dpi=300, width=15, height=14, units="cm",
       device = grDevices::tiff)

#' # Session info
#' <a href="#top">Back to top</a>
#+ Session.info
sessionInfo()
#' <a href="#top">Back to top</a>
######## Session info .................. ####