#' ---
#' title: <center><b>Markdown document from&colon;</b><br>Traces of Genetic but Not Epigenetic Adaptation in the Invasive Goldenrod _Solidago canadensis_ Despite the Absence of Population Structure</center>
#' pagetitle: RMarkdown document from:&nbsp;Eckert&nbsp;et&nbsp;al.&nbsp;(2022)
#' subtitle: <center>doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.3389/fevo.2022.856453">10.3389/fevo.2022.856453</a></center>
#' author: <center>Eckert, S., Herden, J., Stift, M., Durka, W., van Kleunen, M., & Joshi, J.</center>
#' date: <center>`r Sys.Date()`</center>
#' abstract: <p align="justify">This RMarkdown script belongs
#'   to a series of scripts generated by Silvia Eckert as part of
#'   the statistical analysis for the above-mentioned manuscript.
#'   The data underlying the applied R code can be found in the ZENODO
#'   repository and contains genetic (AFLP) and epigenetic (MSAP) markers
#'   from offspring of 25 _Solidago canadensis_ populations sampled along a
#'   latitudinal gradient in Central Europe. This particular RMarkdown script
#'   is part 06/06 and applies the LEA genome-scan approach on the MSAP-n 
#'   dataset. <b>Please cite this
#'   script as follows:</b></p><br><p>Eckert, S., Herden, J.,
#'   Stift, M., Durka, W., van Kleunen, M., & Joshi, J. (2022). Data From&colon;
#'   Traces of Genetic but Not Epigenetic Adaptation in the Invasive
#'   Goldenrod _Solidago canadensis_ Despite the Absence of Population
#'   Structure. _Zenodo_. doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.5281/zenodo.6388135">10.5281/zenodo.6388135</a></center></p>
#' geometry: margin=2cm
#' output:
#'   html_document:
#'      code_folding: show
#'      keep_md: FALSE
#'      theme: flatly
#'      highlight: textmate
#'      df_print: paged
#'      toc: true
#'      toc_float: true
#' ---
#' 

#'
#'```{r setup, include = FALSE}
#'knitr::opts_chunk$set(eval=FALSE, cache=FALSE, warning=FALSE)
#'```

#' # Packages
#' <a href="#top">Back to top</a>
#+ project_packages, results='hide', message=FALSE, warning=FALSE
########### packages ...................... ####
# install.packages("name_of_package") # install necessary packages
# install knitr to save this script as html output using RStudio with Ctrl+Shift+K (Windows & Linux) or Command+Shift+K (macOS)
# install.packages("knitr") 
# getwd() # get current working directory
# setwd() # set working directory
# create folder for datasets to be stored to get this RMarkdown script running
dir.create("./data",
           showWarnings=F)

#' # Load data
#' <a href="#top">Back to top</a>
#+ project_load.data
########### load data ....................... ####
source("RMarkdown_Eckert_et_al_2022_LEA_04.R")
source("RMarkdown_Eckert_et_al_2022_LEA_05.R")

#' # MSAP-u
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPn
########### MSAP-u ......................... ####
#' ## LFMM
#+ project_LEA.MSAPn_lfmm
######## outlier scan ####
# lfmm with latitude
# parameters following Yadav et al (2019)
# doi:  https://doi.org/10.1111/mec.15146
MSAPn_C.envproject = NULL
MSAPn_C.envproject = lfmm(input.file = "./data_LEA/Input_MSAPu_C.lfmm",
                           environment.file = "./data_LEA/Input_MSAPu_C.env",
                           seed=123,
                           all=F, # fits all variables separately
                           K = 1,
                           repetitions = 10,
                           CPU = 4,
                           iterations = 50000,
                           burnin = 5000,
                           project = "new")
# re-load project
# MSAPn_C.envproject = load.lfmmProject("./data_LEA/MSAPu_C.lfmmProject")

#' ## PC1
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPu_PC1
########### PC1 ................................ ####
#' ### q-values
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPu_PC1_qvalues
######## qvalues ####
# adjusted p-values
MSAPn_C.pv_PC1 = lfmm.pvalues(MSAPn_C.envproject,
                               d=1,
                               K = 1); MSAPn_C.pv_PC1
hist(MSAPn_C.pv_PC1$pvalues,
     col = "gainsboro")
# compute q-values
MSAPn_C.qv_PC1 <- qvalue(MSAPn_C.pv_PC1$pvalues,
                          fdr.level=0.05,
                          lambda=MSAPn_C.pv_PC1$GIF); MSAPn_C.qv_PC1$qvalues
# results of LFMM testing
MSAPn_C.res_PC1 <- tibble(data.frame(ID = names(data.frame(MSAPn_C.genind@tab)),
                                      dye = names(data.frame(MSAPn_C.genind@tab)),
                                      LFMMpVal = MSAPn_C.pv_PC1$pvalues,
                                      latitudeFDR = MSAPn_C.qv_PC1$qvalues,
                                      log10qVal = -log10(MSAPn_C.qv_PC1$qvalues)))
# replace FAM_AAC_CCT_* with FAM
MSAPn_C.res_PC1$dye <- stringr::str_replace(MSAPn_C.res_PC1$dye,
                                             "uFAM_AAC_CCT_[0-9|_]+",
                                             "FAM")
# replace VIC_ACG_CAT_* with VIC
MSAPn_C.res_PC1$dye <- stringr::str_replace(MSAPn_C.res_PC1$dye,
                                             "uVIC_ACG_CAT_[0-9|_]+",
                                             "VIC")
# replace NED_ACC_CTG_* with NED
MSAPn_C.res_PC1$dye <- stringr::str_replace(MSAPn_C.res_PC1$dye,
                                             "uNED_ACC_CTG_[0-9|_]+",
                                             "NED")
# replace PET_AGG_CGA_* with PET
MSAPn_C.res_PC1$dye <- stringr::str_replace(MSAPn_C.res_PC1$dye,
                                             "uPET_AGG_CGA_[0-9|_]+",
                                             "PET")
MSAPn_C.res_PC1$dye <- ordered(MSAPn_C.res_PC1$dye,
                                levels=c("FAM", "VIC", "NED", "PET"))
MSAPn_C.res_PC1$dye # check
# replace FAM_AAC_CCT_* with FAM
MSAPn_C.res_PC1$marker <- stringr::str_replace(MSAPn_C.res_PC1$ID,
                                                "uFAM_AAC_CCT_",
                                                "loc")
# replace VIC_ACG_CAT_* with VIC
MSAPn_C.res_PC1$marker <- stringr::str_replace(MSAPn_C.res_PC1$marker,
                                                "uVIC_ACG_CAT_",
                                                "loc")
# replace NED_ACC_CTG_* with NED
MSAPn_C.res_PC1$marker <- stringr::str_replace(MSAPn_C.res_PC1$marker,
                                                "uNED_ACC_CTG_",
                                                "loc")
# replace PET_AGG_CGA_* with PET
MSAPn_C.res_PC1$marker <- stringr::str_replace(MSAPn_C.res_PC1$marker,
                                                "uPET_AGG_CGA_",
                                                "loc")
MSAPn_C.res_PC1$marker # check
# add basepair value
MSAPn_C.res_PC1$basepair <- MSAPn_C.res_PC1$marker
# replace "loc"
MSAPn_C.res_PC1$basepair <- stringr::str_replace(MSAPn_C.res_PC1$basepair,
                                                  "loc", "")
MSAPn_C.res_PC1$basepair <- as.numeric(MSAPn_C.res_PC1$basepair)
MSAPn_C.res_PC1$basepair # check
MSAPn_C.res_PC1$latentFactor <- "PC1"
str(MSAPn_C.res_PC1); MSAPn_C.res_PC1

#' ## Manhattan plot
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPu_PC1_manhattan
######## Manhattan plot ####
# prepare data
MSAPn_C.resmelt_PC1 <- tibble(reshape2::melt(MSAPn_C.res_PC1[,c(1:2,5:7)],
                                              id.vars=c("ID","marker","dye","basepair"),
                                              measure.vars="log10qVal",
                                              variable.name="FDR",
                                              value.name="log10qVal")); MSAPn_C.resmelt_PC1
# signficant loci
MSAPn_C.lfmm.signf.loc_PC1 <- MSAPn_C.resmelt_PC1[MSAPn_C.resmelt_PC1$log10qVal > -log10(0.05),]
MSAPn_C.lfmm.signf.loc_PC1
# plot
set.seed(123)
MSAPn_C.lfmm.manhattanplot_PC1 <- ggplot(MSAPn_C.resmelt_PC1,
                                          aes(x=basepair,
                                              y=log10qVal)) +
  geom_point(alpha=0.5,
             size=2) +
  scale_y_continuous(expand=c(0,0),
                     limits=c(0,4)) +
  labs(title="MSAP-n (Control)",
       subtitle="PC1 (explained variation: 40.3%)") +
  theme_cowplot() +
  theme(panel.border = element_rect(color="black"),
        legend.position = "none") +
  labs(x="Scored loci [basepairs]",
       y=bquote(-log[10]~"("~italic("q-value")~")")) +
  geom_hline(yintercept=-log10(0.05),
             linetype="longdash",
             color="gray60") +
  scale_color_manual(values=c("blue", "green", "red", "black")) +
  geom_text_repel(data = MSAPn_C.lfmm.signf.loc_PC1,
                  aes(x = basepair,
                      y = log10qVal,
                      label = marker,
                      color=dye),
                  size=3,
                  seed=123); MSAPn_C.lfmm.manhattanplot_PC1

#' ## PC2
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPu_PC2
########### PC2 ................................ ####
#' ### q-values
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPu_PC2_qvalues
######## qvalues ####
# adjusted p-values
MSAPn_C.pv_PC2 = lfmm.pvalues(MSAPn_C.envproject,
                               d=2,
                               K = 1); MSAPn_C.pv_PC2
hist(MSAPn_C.pv_PC2$pvalues,
     col = "gainsboro")
# compute q-values
MSAPn_C.qv_PC2 <- qvalue(MSAPn_C.pv_PC2$pvalues,
                          fdr.level=0.05,
                          lambda=MSAPn_C.pv_PC2$GIF); MSAPn_C.qv_PC2$qvalues
# results of LFMM testing
MSAPn_C.res_PC2 <- tibble(data.frame(ID = names(data.frame(MSAPn_C.genind@tab)),
                                      dye = names(data.frame(MSAPn_C.genind@tab)),
                                      LFMMpVal = MSAPn_C.pv_PC2$pvalues,
                                      latitudeFDR = MSAPn_C.qv_PC2$qvalues,
                                      log10qVal = -log10(MSAPn_C.qv_PC2$qvalues)))
# replace FAM_AAC_CCT_* with FAM
MSAPn_C.res_PC2$dye <- stringr::str_replace(MSAPn_C.res_PC2$dye,
                                             "uFAM_AAC_CCT_[0-9|_]+",
                                             "FAM")
# replace VIC_ACG_CAT_* with VIC
MSAPn_C.res_PC2$dye <- stringr::str_replace(MSAPn_C.res_PC2$dye,
                                             "uVIC_ACG_CAT_[0-9|_]+",
                                             "VIC")
# replace NED_ACC_CTG_* with NED
MSAPn_C.res_PC2$dye <- stringr::str_replace(MSAPn_C.res_PC2$dye,
                                             "uNED_ACC_CTG_[0-9|_]+",
                                             "NED")
# replace PET_AGG_CGA_* with PET
MSAPn_C.res_PC2$dye <- stringr::str_replace(MSAPn_C.res_PC2$dye,
                                             "uPET_AGG_CGA_[0-9|_]+",
                                             "PET")
MSAPn_C.res_PC2$dye <- ordered(MSAPn_C.res_PC2$dye,
                                levels=c("FAM", "VIC", "NED", "PET"))
MSAPn_C.res_PC2$dye # check
# replace FAM_AAC_CCT_* with FAM
MSAPn_C.res_PC2$marker <- stringr::str_replace(MSAPn_C.res_PC2$ID,
                                                "uFAM_AAC_CCT_",
                                                "loc")
# replace VIC_ACG_CAT_* with VIC
MSAPn_C.res_PC2$marker <- stringr::str_replace(MSAPn_C.res_PC2$marker,
                                                "uVIC_ACG_CAT_",
                                                "loc")
# replace NED_ACC_CTG_* with NED
MSAPn_C.res_PC2$marker <- stringr::str_replace(MSAPn_C.res_PC2$marker,
                                                "uNED_ACC_CTG_",
                                                "loc")
# replace PET_AGG_CGA_* with PET
MSAPn_C.res_PC2$marker <- stringr::str_replace(MSAPn_C.res_PC2$marker,
                                                "uPET_AGG_CGA_",
                                                "loc")
MSAPn_C.res_PC2$marker # check
# add basepair value
MSAPn_C.res_PC2$basepair <- MSAPn_C.res_PC2$marker
# replace "loc"
MSAPn_C.res_PC2$basepair <- stringr::str_replace(MSAPn_C.res_PC2$basepair,
                                                  "loc", "")
MSAPn_C.res_PC2$basepair <- as.numeric(MSAPn_C.res_PC2$basepair)
MSAPn_C.res_PC2$basepair # check
MSAPn_C.res_PC2$latentFactor <- "PC2"
str(MSAPn_C.res_PC2); MSAPn_C.res_PC2

#' ## Manhattan plot
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPu_PC2_manhattan
######## Manhattan plot ####
# prepare data
MSAPn_C.resmelt_PC2 <- tibble(reshape2::melt(MSAPn_C.res_PC2[,c(1:2,5:7)],
                                              id.vars=c("ID","marker","dye","basepair"),
                                              measure.vars="log10qVal",
                                              variable.name="FDR",
                                              value.name="log10qVal")); MSAPn_C.resmelt_PC2
# signficant loci
MSAPn_C.lfmm.signf.loc_PC2 <- MSAPn_C.resmelt_PC2[MSAPn_C.resmelt_PC2$log10qVal > -log10(0.05),]
MSAPn_C.lfmm.signf.loc_PC2
# plot
set.seed(123)
MSAPn_C.lfmm.manhattanplot_PC2 <- ggplot(MSAPn_C.resmelt_PC2,
                                          aes(x=basepair,
                                              y=log10qVal)) +
  geom_point(alpha=0.5,
             size=2) +
  scale_y_continuous(expand=c(0,0),
                     limits=c(0,4)) +
  labs(title="",
       subtitle="PC2 (explained variation: 32.7%)") +
  theme_cowplot() +
  theme(panel.border = element_rect(color="black"),
    legend.position = "none") +
  labs(x="Scored loci [basepairs]", y="") +
  geom_hline(yintercept=-log10(0.05),
             linetype="longdash",
             color="gray60") +
  scale_color_manual(values=c("green", "red", "black", "blue")) +
  geom_text_repel(data = MSAPn_C.lfmm.signf.loc_PC2,
                  aes(x = basepair,
                      y = log10qVal,
                      label = marker,
                      color=dye),
                  size=3,
                  seed=123); MSAPn_C.lfmm.manhattanplot_PC2

#' ## PC3
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPu_PC3
########### PC3 ................................ ####
#' ### q-values
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPu_PC3_qvalues
######## qvalues ####
# adjusted p-values
MSAPn_C.pv_PC3 = lfmm.pvalues(MSAPn_C.envproject,
                               d=3,
                               K = 1); MSAPn_C.pv_PC3
hist(MSAPn_C.pv_PC3$pvalues,
     col = "gainsboro")
# compute q-values
MSAPn_C.qv_PC3 <- qvalue(MSAPn_C.pv_PC3$pvalues,
                          fdr.level=0.05,
                          lambda=MSAPn_C.pv_PC3$GIF); MSAPn_C.qv_PC3$qvalues
# results of LFMM testing
MSAPn_C.res_PC3 <- tibble(data.frame(ID = names(data.frame(MSAPn_C.genind@tab)),
                                      dye = names(data.frame(MSAPn_C.genind@tab)),
                                      LFMMpVal = MSAPn_C.pv_PC3$pvalues,
                                      latitudeFDR = MSAPn_C.qv_PC3$qvalues,
                                      log10qVal = -log10(MSAPn_C.qv_PC3$qvalues)))
# replace FAM_AAC_CCT_* with FAM
MSAPn_C.res_PC3$dye <- stringr::str_replace(MSAPn_C.res_PC3$dye,
                                             "uFAM_AAC_CCT_[0-9|_]+",
                                             "FAM")
# replace VIC_ACG_CAT_* with VIC
MSAPn_C.res_PC3$dye <- stringr::str_replace(MSAPn_C.res_PC3$dye,
                                             "uVIC_ACG_CAT_[0-9|_]+",
                                             "VIC")
# replace NED_ACC_CTG_* with NED
MSAPn_C.res_PC3$dye <- stringr::str_replace(MSAPn_C.res_PC3$dye,
                                             "uNED_ACC_CTG_[0-9|_]+",
                                             "NED")
# replace PET_AGG_CGA_* with PET
MSAPn_C.res_PC3$dye <- stringr::str_replace(MSAPn_C.res_PC3$dye,
                                             "uPET_AGG_CGA_[0-9|_]+",
                                             "PET")
MSAPn_C.res_PC3$dye <- ordered(MSAPn_C.res_PC3$dye,
                                levels=c("FAM", "VIC", "NED", "PET"))
MSAPn_C.res_PC3$dye # check
# replace FAM_AAC_CCT_* with FAM
MSAPn_C.res_PC3$marker <- stringr::str_replace(MSAPn_C.res_PC3$ID,
                                                "uFAM_AAC_CCT_",
                                                "loc")
# replace VIC_ACG_CAT_* with VIC
MSAPn_C.res_PC3$marker <- stringr::str_replace(MSAPn_C.res_PC3$marker,
                                                "uVIC_ACG_CAT_",
                                                "loc")
# replace NED_ACC_CTG_* with NED
MSAPn_C.res_PC3$marker <- stringr::str_replace(MSAPn_C.res_PC3$marker,
                                                "uNED_ACC_CTG_",
                                                "loc")
# replace PET_AGG_CGA_* with PET
MSAPn_C.res_PC3$marker <- stringr::str_replace(MSAPn_C.res_PC3$marker,
                                                "uPET_AGG_CGA_",
                                                "loc")
MSAPn_C.res_PC3$marker # check
# add basepair value
MSAPn_C.res_PC3$basepair <- MSAPn_C.res_PC3$marker
# replace "loc"
MSAPn_C.res_PC3$basepair <- stringr::str_replace(MSAPn_C.res_PC3$basepair,
                                                  "loc", "")
MSAPn_C.res_PC3$basepair <- as.numeric(MSAPn_C.res_PC3$basepair)
MSAPn_C.res_PC3$basepair # check
MSAPn_C.res_PC3$latentFactor <- "PC3"
str(MSAPn_C.res_PC3); MSAPn_C.res_PC3

#' ## Manhattan plot
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPu_PC3_manhattan
######## Manhattan plot ####
# prepare data
MSAPn_C.resmelt_PC3 <- tibble(reshape2::melt(MSAPn_C.res_PC3[,c(1:2,5:7)],
                                              id.vars=c("ID","marker","dye","basepair"),
                                              measure.vars="log10qVal",
                                              variable.name="FDR",
                                              value.name="log10qVal")); MSAPn_C.resmelt_PC3
# signficant loci
MSAPn_C.lfmm.signf.loc_PC3 <- MSAPn_C.resmelt_PC3[MSAPn_C.resmelt_PC3$log10qVal > -log10(0.05),]
MSAPn_C.lfmm.signf.loc_PC3
# plot
set.seed(123)
MSAPn_C.lfmm.manhattanplot_PC3 <- ggplot(MSAPn_C.resmelt_PC3,
                                          aes(x=basepair,
                                              y=log10qVal)) +
  geom_point(alpha=0.5,
             size=2) +
  scale_y_continuous(expand=c(0,0),
                     limits=c(0,4)) +
  labs(title="",
       subtitle="PC3 (explained variation: 14.4%)") +
  theme_cowplot() +
  theme(panel.border = element_rect(color="black"),
    legend.position = "none") +
  labs(x="Scored loci [basepairs]",
       y="") +
  geom_hline(yintercept=-log10(0.05),
             linetype="longdash",
             color="gray60") +
  scale_color_manual(values=c("red", "blue", "green", "black")) +
  geom_text_repel(data = MSAPn_C.lfmm.signf.loc_PC3,
                  aes(x = basepair,
                      y = log10qVal,
                      label = marker,
                      color=dye),
                  size=3,
                  seed=123); MSAPn_C.lfmm.manhattanplot_PC3

#' ## Figure S13G-I
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAP-u.snmf_figureS13GHI
######## Figure S13GHI ####
# single figure
MSAPn_lfmmCombi <- ggarrange(MSAPn_C.lfmm.manhattanplot_PC1,
                              MSAPn_C.lfmm.manhattanplot_PC2,
                              MSAPn_C.lfmm.manhattanplot_PC3,
                              ncol=3,
                              nrow=1,
                              font.label = list(size = 20),
                              labels=c("A","B","C")) +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm")); MSAPn_lfmmCombi
# save as png
ggsave(MSAPn_lfmmCombi,
       file="./data/FigureS13GHI_Eckert_et_al_2022_LEA_lfmm_MSAPn.png",
       width=12,
       height=5,
       dpi=300)
# save as tiff
ggsave(MSAPn_lfmmCombi,
       file="./data/FigureS13GHI_Eckert_et_al_2022_LEA_lfmm_MSAPn.TIFF",
       dpi=300,
       width=12,
       height=5,
       device = grDevices::tiff)

# combined figure
AFLPMSAP_lfmmCombi <- plot_grid(AFLP_C.lfmm.manhattanplot_PC1,
                                AFLP_C.lfmm.manhattanplot_PC2,
                                AFLP_C.lfmm.manhattanplot_PC3,
                                MSAPm_C.lfmm.manhattanplot_PC1,
                                MSAPm_C.lfmm.manhattanplot_PC2,
                                MSAPm_C.lfmm.manhattanplot_PC3,
                                MSAPn_C.lfmm.manhattanplot_PC1,
                                MSAPn_C.lfmm.manhattanplot_PC2,
                                MSAPn_C.lfmm.manhattanplot_PC3,
                                ncol=3,
                                nrow=3,
                                label_size=18,
                                labels=c('A','B','C','D',
                                         'E','F',"G","H","I")) +
  theme(plot.margin = unit(c(1, 1, 1, 1), "cm"))#; AFLPMSAP_lfmmCombi
# save as png
ggsave(AFLPMSAP_lfmmCombi,
       file="./data/FigureS13_Eckert_et_al_2022_LEA_lfmm.png",
       dpi=150,
       width=12,
       height=12)
# save as tiff
ggsave(AFLPMSAP_lfmmCombi,
       file="./data/FigureS13_Eckert_et_al_2022_LEA_lfmm.TIFF",
       dpi=300,
       width=12,
       height=12,
       device = grDevices::tiff)

#' ## Table S5
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPn.snmf_tableS5
######## Table S5 ####
# prepare data
MSAPn_C.lfmm.signf.loc_all <- tibble(rbind(MSAPn_C.lfmm.signf.loc_PC1,
                                            MSAPn_C.lfmm.signf.loc_PC2,
                                            MSAPn_C.lfmm.signf.loc_PC3)); MSAPn_C.lfmm.signf.loc_all
# save trimmed AFLP marker data
write.table(MSAPn_C.lfmm.signf.loc_all,
            row.names=F,
            file="./data/Data_MSAPn_LFMM_outliers.txt")

#' # Session info
#' <a href="#top">Back to top</a>
#+ Session.info
######## Session info ###
sessionInfo()
#' <a href="#top">Back to top</a>
######## Session info .................. ####