#' ---
#' title: <center><b>Markdown document from&colon;</b><br>Traces of Genetic but Not Epigenetic Adaptation in the Invasive Goldenrod _Solidago canadensis_ Despite the Absence of Population Structure</center>
#' pagetitle: RMarkdown document from:&nbsp;Eckert&nbsp;et&nbsp;al.&nbsp;(2022)
#' subtitle: <center>doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.3389/fevo.2022.856453">10.3389/fevo.2022.856453</a></center>
#' author: <center>Eckert, S., Herden, J., Stift, M., Durka, W., van Kleunen, M., & Joshi, J.</center>
#' date: <center>`r Sys.Date()`</center>
#' abstract: <p align="justify">This RMarkdown script belongs
#'   to a series of scripts generated by Silvia Eckert as part of
#'   the statistical analysis for the above-mentioned manuscript.
#'   The data underlying the applied R code can be found in the ZENODO
#'   repository and contains genetic (AFLP) and epigenetic (MSAP) markers
#'   from offspring of 25 _Solidago canadensis_ populations sampled along a
#'   latitudinal gradient in Central Europe. This particular RMarkdown script
#'   applies part 2/2 of RDA analaysis on both MSAP datasets. <b>Please cite this
#'   script as follows:</b></p><br><p>Eckert, S., Herden, J.,
#'   Stift, M., Durka, W., van Kleunen, M., & Joshi, J. (2022). Data From&colon;
#'   Traces of Genetic but Not Epigenetic Adaptation in the Invasive
#'   Goldenrod _Solidago canadensis_ Despite the Absence of Population
#'   Structure. _Zenodo_. doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.5281/zenodo.6388135">10.5281/zenodo.6388135</a></center></p>
#' geometry: margin=2cm
#' output:
#'   html_document:
#'      code_folding: show
#'      keep_md: FALSE
#'      theme: flatly
#'      highlight: textmate
#'      df_print: paged
#'      toc: true
#'      toc_float: true
#' ---
#' 

#'
#'```{r setup, include = FALSE}
#'knitr::opts_chunk$set(eval=FALSE, cache=FALSE, warning=FALSE)
#'```

#' # Packages
#' <a href="#top">Back to top</a>
#+ project_packages, results='hide', message=FALSE, warning=FALSE
########### packages ...................... ####
# install.packages("name_of_package") # install necessary packages
# install knitr to save this script as html output using RStudio with Ctrl+Shift+K (Windows & Linux) or Command+Shift+K (macOS)
# install.packages("knitr") 
# getwd() # get current working directory
# setwd() # set working directory
# create folder for datasets to be stored to get this RMarkdown script running
dir.create("./data",
           showWarnings=F)
# add necessary libraries
library(vegan)
library(psych)
library(ggplot2)
library(tibble)
library(plyr)
library(dplyr)

#' # Load data
#' <a href="#top">Back to top</a>
#+ project_load.data
########### Load data ..................... ####
# load RDA data
source("RMarkdown_Eckert_et_al_2022_RDA_01.R")

#' # Colours
#' <a href="#top">Back to top</a>
#+ project_project.colours
########### Colours  .......................... ####
#' ## MSAP-m
#' <a href="#top">Back to top</a>
#+ project_project.colours.MSAPm
########### MSAP-m ####
# This is the plotting part of the RDA procedure provided by Forester et al. (2018)
# and in their published tutorial here: https://popgen.nescent.org/2018-03-27_RDA_GEA.html#references
MSAPm_C.sel <- MSAPm_C.candidates$locus
MSAPm_C.col_env <- MSAPm_C.candidates$predictor
MSAPm_C.col_env[MSAPm_C.col_env=="MEMGENE1"] <- '#cc79A7'
MSAPm_C.col_env[MSAPm_C.col_env=="MEMGENE2"] <- '#e69f00'
MSAPm_C.col_env[MSAPm_C.col_env=="MEMGENE3"] <- '#56b4e9'
MSAPm_C.col_env
# color by predictor
# pull the locus names
MSAPm_C.col_pred <- rownames(MSAPm_C.rda$CCA$v); MSAPm_C.col_pred 
# color code candidates
for (i in 1:length(MSAPm_C.sel)) {
  foo <- match(MSAPm_C.sel[i],MSAPm_C.col_pred)
  MSAPm_C.col_pred[foo] <- MSAPm_C.col_env[i]}
MSAPm_C.col_pred
# color code non-candidates
MSAPm_C.col_pred[grep("M",MSAPm_C.col_pred)] <- 'gray80'
MSAPm_C.col_empty <- MSAPm_C.col_pred
MSAPm_C.col_empty[grep("gray80",MSAPm_C.col_empty)] <- rgb(0,1,0,alpha=0) # transparent
MSAPm_C.empty_outline <- ifelse(MSAPm_C.col_empty=="#cc79A7","#e69f00","#56b4e9")
bg <- c("#cc79A7","#e69f00","#56b4e9")
MSAPm_C.col_pred

#' ## MSAP-n
#' <a href="#top">Back to top</a>
#+ project_project.colours.MSAPn
########### MSAP-n ####
MSAPn_C.sel <- MSAPn_C.candidates$locus
MSAPn_C.col_env <- MSAPn_C.candidates$predictor
MSAPn_C.col_env[MSAPn_C.col_env=="MEMGENE1"] <- '#cc79A7'
MSAPn_C.col_env[MSAPn_C.col_env=="MEMGENE2"] <- '#e69f00'
MSAPn_C.col_env[MSAPn_C.col_env=="MEMGENE3"] <- '#56b4e9'
MSAPn_C.col_env
# color by predictor
# pull the locus names
MSAPn_C.col_pred <- rownames(MSAPn_C.rda$CCA$v); MSAPn_C.col_pred 
# color code candidates
for (i in 1:length(MSAPn_C.sel)) {
  foo <- match(MSAPn_C.sel[i],MSAPn_C.col_pred)
  MSAPn_C.col_pred[foo] <- MSAPn_C.col_env[i]}
MSAPn_C.col_pred
# color code non-candidates
MSAPn_C.col_pred[grep("u",MSAPn_C.col_pred)] <- 'gray80'
MSAPn_C.col_empty <- MSAPn_C.col_pred
MSAPn_C.col_empty[grep("gray80",MSAPn_C.col_empty)] <- rgb(0,1,0,alpha=0) # transparent
MSAPn_C.empty_outline <- ifelse(MSAPn_C.col_empty=="#cc79A7","#e69f00","#56b4e9")
bg <- c("#cc79A7","#e69f00","#56b4e9")
MSAPn_C.col_pred

#' # Figure S14
#' <a href="#top">Back to top</a>
#+ project_project.figureS14
########### Figure S14 ..................... ####
#' ## PNG
#' <a href="#top">Back to top</a>
#+ project_project.plot.PNG
########### PNG ####
# save
png("FigureS14_Eckert_et_al_2022_MSAP_RDA_outliers.png",
    width=25,
    height=14,
    units="cm",
    res=300)
# size
par(mfrow=c(2,3),
    mar=c(6,6,3,2))
# MSAP-m: axes 1 & 2
plot(MSAP.m_C.rda,
     type="n",
     scaling=3,
     xlim=c(-1,1),
     ylim=c(-1,1),
     xlab="RDA1 (0.8%)",
     ylab="RDA2 (0.7%)",
     main="\nMSAP-m")
points(MSAP.m_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="gray40",
       bg=alpha(MSAPm_C.col_pred,0.5),
       scaling=3)
points(MSAP.m_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="transparent",
       bg=MSAPm_C.col_empty,
       scaling=3)
text(MSAP.m_C.rda,
     scaling=0,
     display="bp",
     col="black",
     cex=0.7,
     adj=1)
text("A",
     cex=2,
     xpd=T,
     x=-2.2,
     y=1.2)
legend("topleft",
       legend=c("MEMGENE1","MEMGENE2","MEMGENE3"),
       bty="n",
       col="gray40",
       pch=21,
       cex=0.8,
       pt.cex=1.5,
       pt.bg=bg)
# MSAP-m: axes 1 & 3
plot(MSAP.m_C.rda,
     type="n",
     scaling=3,
     xlim=c(-1,1),
     ylim=c(-1,1),
     choices=c(1,3),
     xlab="RDA1 (0.8%)",
     ylab="RDA3 (0.6%)",
     main="\nMSAP-m")
points(MSAP.m_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="gray40",
       bg=alpha(MSAPm_C.col_pred,0.5),
       scaling=3,
       choices=c(1,3))
points(MSAP.m_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="transparent",
       bg=MSAPm_C.col_empty,
       scaling=3,
       choices=c(1,3))
text(MSAP.m_C.rda,
     scaling=3,
     xpd=T,
     display="bp",
     col="black",
     cex=0.7,
     adj=1,
     choices=c(1,3))
text("B",
     cex=2,
     xpd=T,
     x=-2.2,
     y=1.2)
# MSAP-m: axes 2 & 3
plot(MSAP.m_C.rda,
     type="n",
     scaling=3,
     xlim=c(-1,1),
     ylim=c(-1,1),
     choices=c(2,3),
     xlab="RDA2 (0.7%)",
     ylab="RDA3 (0.6%)",
     main="\nMSAP-m")
points(MSAP.m_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="gray40",
       bg=alpha(MSAPm_C.col_pred,0.5),
       scaling=3,
       choices=c(2,3))
points(MSAP.m_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="transparent",
       bg=MSAPm_C.col_empty,
       scaling=3,
       choices=c(2,3))
text(MSAP.m_C.rda,
     scaling=3,
     xpd=T,
     display="bp",
     col="black",
     cex=0.7,
     adj=0,
     choices=c(2,3))
text("C",
     cex=2,
     xpd=T,
     x=-2.2,
     y=1.2)
# MSAP-u: axes 1 & 2
plot(MSAP.u_C.rda,
     type="n",
     scaling=3,
     xlim=c(-1,1),
     ylim=c(-1,1),
     xlab="RDA1 (0.8%)",
     ylab="RDA2 (0.7%)",
     main="\nMSAP-n")
points(MSAP.u_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="gray40",
       bg=alpha(MSAPu_C.col_pred,0.5),
       scaling=3)
points(MSAP.u_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="transparent",
       bg=MSAPu_C.col_empty,
       scaling=3)
text(MSAP.u_C.rda,
     scaling=0,
     display="bp",
     col="black",
     cex=0.7,
     adj=1)
text("D",
     cex=2,
     xpd=T,
     x=-2.2,
     y=1.2)
# MSAP-u: axes 1 & 3
plot(MSAP.u_C.rda,
     type="n",
     scaling=3,
     xlim=c(-1,1),
     ylim=c(-1,1),
     choices=c(1,3),
     xlab="RDA1 (0.8%)",
     ylab="RDA3 (0.5%)",
     main="\nMSAP-n")
points(MSAP.u_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="gray40",
       bg=alpha(MSAPu_C.col_pred,0.5),
       scaling=3,
       choices=c(1,3))
points(MSAP.u_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="transparent",
       bg=MSAPu_C.col_empty,
       scaling=3,
       choices=c(1,3))
text(MSAP.u_C.rda,
     scaling=3,
     xpd=T,
     display="bp",
     col="black",
     cex=0.7,
     adj=1,
     choices=c(1,3))
text("E",
     cex=2,
     xpd=T,
     x=-2.2,
     y=1.2)
# MSAP-u: axes 2 & 3
plot(MSAP.u_C.rda,
     type="n",
     scaling=3,
     xlim=c(-1,1),
     ylim=c(-1,1),
     choices=c(2,3),
     xlab="RDA2 (0.7%)",
     ylab="RDA3 (0.5%)",
     main="\nMSAP-n")
points(MSAP.u_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="gray40",
       bg=alpha(MSAPu_C.col_pred,0.5),
       scaling=3,
       choices=c(2,3))
points(MSAP.u_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="transparent",
       bg=MSAPu_C.col_empty,
       scaling=3,
       choices=c(2,3))
text(MSAP.u_C.rda,
     scaling=3,
     xpd=T,
     display="bp",
     col="black",
     cex=0.7,
     adj=0,
     choices=c(2,3))
text("F",
     cex=2,
     xpd=T,
     x=-2.2,
     y=1.2)
graphics.off()

#' ## TIFF
#' <a href="#top">Back to top</a>
#+ project_project.plot.TIFF
########### TIFF ####
# save
tiff("./data/FigureS14_Eckert_et_al_2022_MSAP_RDA_outliers.TIFF",
     width=25,
     height=14,
     units="cm",
     res=300)
# size
par(mfrow=c(2,3),
    mar=c(6,6,3,2))
# MSAP-m: axes 1 & 2
plot(MSAP.m_C.rda,
     type="n",
     scaling=3,
     xlim=c(-1,1),
     ylim=c(-1,1),
     xlab="RDA1 (0.8%)",
     ylab="RDA2 (0.7%)",
     main="\nMSAP-m")
points(MSAP.m_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="gray40",
       bg=alpha(MSAPm_C.col_pred,0.5),
       scaling=3)
points(MSAP.m_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="transparent",
       bg=MSAPm_C.col_empty,
       scaling=3)
text(MSAP.m_C.rda,
     scaling=0,
     display="bp",
     col="black",
     cex=0.7,
     adj=1)
text("A",
     cex=2,
     xpd=T,
     x=-2.2,
     y=1.2)
legend("topleft",
       legend=c("MEMGENE1","MEMGENE2","MEMGENE3"),
       bty="n",
       col="gray40",
       pch=21,
       cex=0.8,
       pt.cex=1.5,
       pt.bg=bg)
# MSAP-m: axes 1 & 3
plot(MSAP.m_C.rda,
     type="n",
     scaling=3,
     xlim=c(-1,1),
     ylim=c(-1,1),
     choices=c(1,3),
     xlab="RDA1 (0.8%)",
     ylab="RDA3 (0.6%)",
     main="\nMSAP-m")
points(MSAP.m_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="gray40",
       bg=alpha(MSAPm_C.col_pred,0.5),
       scaling=3,
       choices=c(1,3))
points(MSAP.m_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="transparent",
       bg=MSAPm_C.col_empty,
       scaling=3,
       choices=c(1,3))
text(MSAP.m_C.rda,
     scaling=3,
     xpd=T,
     display="bp",
     col="black",
     cex=0.7,
     adj=1,
     choices=c(1,3))
text("B",
     cex=2,
     xpd=T,
     x=-2.2,
     y=1.2)
# MSAP-m: axes 2 & 3
plot(MSAP.m_C.rda,
     type="n",
     scaling=3,
     xlim=c(-1,1),
     ylim=c(-1,1),
     choices=c(2,3),
     xlab="RDA2 (0.7%)",
     ylab="RDA3 (0.6%)",
     main="\nMSAP-m")
points(MSAP.m_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="gray40",
       bg=alpha(MSAPm_C.col_pred,0.5),
       scaling=3,
       choices=c(2,3))
points(MSAP.m_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="transparent",
       bg=MSAPm_C.col_empty,
       scaling=3,
       choices=c(2,3))
text(MSAP.m_C.rda,
     scaling=3,
     xpd=T,
     display="bp",
     col="black",
     cex=0.7,
     adj=0,
     choices=c(2,3))
text("C",
     cex=2,
     xpd=T,
     x=-2.2,
     y=1.2)
# MSAP-u: axes 1 & 2
plot(MSAP.u_C.rda,
     type="n",
     scaling=3,
     xlim=c(-1,1),
     ylim=c(-1,1),
     xlab="RDA1 (0.8%)",
     ylab="RDA2 (0.7%)",
     main="\nMSAP-n")
points(MSAP.u_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="gray40",
       bg=alpha(MSAPu_C.col_pred,0.5),
       scaling=3)
points(MSAP.u_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="transparent",
       bg=MSAPu_C.col_empty,
       scaling=3)
text(MSAP.u_C.rda,
     scaling=0,
     display="bp",
     col="black",
     cex=0.7,
     adj=1)
text("D",
     cex=2,
     xpd=T,
     x=-2.2,
     y=1.2)
# MSAP-u: axes 1 & 3
plot(MSAP.u_C.rda,
     type="n",
     scaling=3,
     xlim=c(-1,1),
     ylim=c(-1,1),
     choices=c(1,3),
     xlab="RDA1 (0.8%)",
     ylab="RDA3 (0.5%)",
     main="\nMSAP-n")
points(MSAP.u_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="gray40",
       bg=alpha(MSAPu_C.col_pred,0.5),
       scaling=3,
       choices=c(1,3))
points(MSAP.u_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="transparent",
       bg=MSAPu_C.col_empty,
       scaling=3,
       choices=c(1,3))
text(MSAP.u_C.rda,
     scaling=3,
     xpd=T,
     display="bp",
     col="black",
     cex=0.7,
     adj=1,
     choices=c(1,3))
text("E",
     cex=2,
     xpd=T,
     x=-2.2,
     y=1.2)
# MSAP-u: axes 2 & 3
plot(MSAP.u_C.rda,
     type="n",
     scaling=3,
     xlim=c(-1,1),
     ylim=c(-1,1),
     choices=c(2,3),
     xlab="RDA2 (0.7%)",
     ylab="RDA3 (0.5%)",
     main="\nMSAP-n")
points(MSAP.u_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="gray40",
       bg=alpha(MSAPu_C.col_pred,0.5),
       scaling=3,
       choices=c(2,3))
points(MSAP.u_C.rda,
       display="species",
       pch=21,
       cex=1,
       col="transparent",
       bg=MSAPu_C.col_empty,
       scaling=3,
       choices=c(2,3))
text(MSAP.u_C.rda,
     scaling=3,
     xpd=T,
     display="bp",
     col="black",
     cex=0.7,
     adj=0,
     choices=c(2,3))
text("F",
     cex=2,
     xpd=T,
     x=-2.2,
     y=1.2)
graphics.off()

#' # Session info
#' <a href="#top">Back to top</a>
#+ Session.info
sessionInfo()
#' <a href="#top">Back to top</a>
######## Session info .................. ####