#' ---
#' title: <center><b>Markdown document from&colon;</b><br>Traces of Genetic but Not Epigenetic Adaptation in the Invasive Goldenrod _Solidago canadensis_ Despite the Absence of Population Structure</center>
#' pagetitle: RMarkdown document from:&nbsp;Eckert&nbsp;et&nbsp;al.&nbsp;(2022)
#' subtitle: <center>doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.3389/fevo.2022.856453">10.3389/fevo.2022.856453</a></center>
#' author: <center>Eckert, S., Herden, J., Stift, M., Durka, W., van Kleunen, M., & Joshi, J.</center>
#' date: <center>`r Sys.Date()`</center>
#' abstract: <p align="justify">This RMarkdown script belongs
#'   to a series of scripts generated by Silvia Eckert as part of
#'   the statistical analysis for the above-mentioned manuscript.
#'   The data underlying the applied R code can be found in the ZENODO
#'   repository and contains genetic (AFLP) and epigenetic (MSAP) markers
#'   from offspring of 25 _Solidago canadensis_ populations sampled along a
#'   latitudinal gradient in Central Europe. This particular RMarkdown script
#'   loads plant trait data from the Dryad repository. <b>Please cite this
#'   script as follows:</b></p><br><p>Eckert, S., Herden, J.,
#'   Stift, M., Durka, W., van Kleunen, M., & Joshi, J. (2022). Data From&colon;
#'   Traces of Genetic but Not Epigenetic Adaptation in the Invasive
#'   Goldenrod _Solidago canadensis_ Despite the Absence of Population
#'   Structure. _Zenodo_. doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.5281/zenodo.6388135">10.5281/zenodo.6388135</a></center></p>
#' geometry: margin=2cm
#' output:
#'   html_document:
#'      code_folding: show
#'      keep_md: FALSE
#'      theme: flatly
#'      highlight: textmate
#'      df_print: paged
#'      toc: true
#'      toc_float: true
#' ---
#' 

#'
#'```{r setup, include = FALSE}
#'knitr::opts_chunk$set(eval=FALSE, cache=FALSE, warning=FALSE)
#'```

#' # Packages
#' <a href="#top">Back to top</a>
#+ project_packages, results='hide', message=FALSE, warning=FALSE
########### packages ...................... ####
# install.packages("name_of_package") # install necessary packages
# install knitr to save this script as html output using RStudio with Ctrl+Shift+K (Windows & Linux) or Command+Shift+K (macOS)
# install.packages("knitr") 
# getwd() # get current working directory
# setwd() # set working directory
# create folder for datasets to be stored to get this RMarkdown script running
dir.create("./data",
           showWarnings=F)
library(rdryad)
library(tibble)
library(tidyverse)

#' # Load data
#' <a href="#top">Back to top</a>
#+ project_load.data
########### Load data ...................... ####
# PREMISE: This trait data has already been analysed and published in the
# Dryad repository (Eckert et al., 2021)
# Extract data for Solidago canadensis based on corresponding doi
dryad_eckert_et_al_2021 <- dryad_download(doi="10.5061/dryad.rr4xgxd6s")
# file path
dryad_zipFile <- dryad_eckert_et_al_2021$`10.5061/dryad.rr4xgxd6s` 
# unzip to data folder
unzip(dryad_zipFile, exdir="./data")
# list files from data folder
dryad_Files <- list.files(path="./data"); dryad_Files
# extract trait data
dryad_TRAITS <- read_table(paste0("./data/",dryad_Files[8])); dryad_TRAITS
# define column classes
dryad_TRAITS <- dryad_TRAITS %>%
  mutate_at(c(1:3,5:7,10:18,21:35), as.factor); dryad_TRAITS
# restrict to Solidago canadensis trait data
TRAITS_all <- dryad_TRAITS[dryad_TRAITS$solidago == "canadensis",]
dim(TRAITS_all); TRAITS_all # 439 x 53
# subset to valid data (no buffer plants, non-damaged plants, et cetera ...)
TRAITS_raw <- subset(TRAITS_all,
                     damaged_in_2015 == 0 &
                       damaged_in_2016 == 0 &
                       slug_damage == 0 &
                       replaced_with_buffer == 0);  dim(TRAITS_raw)
# subset to plants that were (epi)genotyped
TRAITS <- TRAITS_raw %>%
  select(uniqueID,
         common_garden_block,
         block_position,
         treatment,
         lat,
         lon,
         populationID,
         maternal_line,
         valid_Nonflowering2015_analysis,
         valid_Nonflowering2016_analysis,
         valid_for_flowering2015_analysis,
         valid_for_flowering2016_analysis,
         valid_for_height2015_analysis,
         valid_for_height2016_analysis,
         valid_for_totalbiomass2015_analysis,
         valid_for_reprbiomass2015_analysis,
         trait_plantheightCM_2015,
         trait_plantheightCM_2016,
         trait_daystoflowering_2015,
         trait_daystoflowering_2016,
         trait_reprbiomassG_2015,
         trait_totalbiomassG_2015)
# check subset
dim(TRAITS); names(TRAITS); TRAITS

#' ## Check traits
#' <a href="#top">Back to top</a>
#+ project_check.traits
########### Check traits ####
# create reproductive-to-total biomass and remove raw reproductive biomass column
TRAITS$trait_biomass_ratio <- TRAITS$trait_reprbiomassG_2015/TRAITS$trait_totalbiomassG_2015
TRAITS <- TRAITS %>%
  select(-trait_reprbiomassG_2015); names(TRAITS)
# check values for true zeros and NAs
# for flowering 2015
check_flowering2015 <- tibble(flowering = TRAITS$trait_daystoflowering_2015,
                              check = TRAITS$valid_for_flowering2015_analysis); check_flowering2015
data.frame(check_flowering2015[(check_flowering2015$check == 0) |
                                 (is.na(check_flowering2015$check)),])
# for flowering 2016
check_flowering2016 <- tibble(flowering = TRAITS$trait_daystoflowering_2016,
                              check = TRAITS$valid_for_flowering2016_analysis); check_flowering2016
data.frame(check_flowering2016[(check_flowering2016$check == 0) |
                                 (is.na(check_flowering2016$check)),])
# for height 2015
check_height2015 <- tibble(height = TRAITS$trait_plantheightCM_2015,
                           check = TRAITS$valid_for_height2015_analysis); check_height2015
data.frame(check_height2015[(check_height2015$check == 0) |
                              (is.na(check_height2015$check)),])
# for height 2016
check_height2016 <- tibble(height = TRAITS$trait_plantheightCM_2016,
                           check = TRAITS$valid_for_height2016_analysis); check_height2016
data.frame(check_height2016[(check_height2016$check == 0) |
                              (is.na(check_height2016$check)),])
# for total biomass 2015
check_totalbiomass2015 <- tibble(total = TRAITS$trait_totalbiomassG_2015,
                                 check = TRAITS$valid_for_totalbiomass2015_analysis); check_totalbiomass2015
data.frame(check_totalbiomass2015[(check_totalbiomass2015$check == 0) |
                                    (is.na(check_totalbiomass2015$check)),])
# for biomass ratio 2016
check_biomassratio2015 <- tibble(ratio = TRAITS$trait_biomass_ratio,
                                 check = TRAITS$valid_for_reprbiomass2015_analysis); check_biomassratio2015
data.frame(check_biomassratio2015[(check_biomassratio2015$check == 0) |
                                    (is.na(check_biomassratio2015$check)),])
# replace zeros with NAs in rows 4, 120, 249, 318, 320, 324
TRAITS[c(4, 120, 249, 318, 320, 324), 22]
TRAITS[c(4, 120, 249, 318, 320, 324), 22] <- NA
TRAITS[c(4, 120, 249, 318, 320, 324), 22]
# check data
TRAITS

#' ## Subset data
#' <a href="#top">Back to top</a>
#+ project_subset.data
########### Subset data ####
# subset data to control plants only
TRAITS_C <- TRAITS[TRAITS$treatment == "CON",]; dim(TRAITS_C)
# subset data to zebularine plants only
TRAITS_Z <- TRAITS[TRAITS$treatment == "ZEB",]; dim(TRAITS_Z)

#' # Session info
#' <a href="#top">Back to top</a>
#+ Session.info
sessionInfo()
#' <a href="#top">Back to top</a>
######## Session info .................. ####