#' ---
#' title: <center><b>Markdown document from&colon;</b><br>Traces of Genetic but Not Epigenetic Adaptation in the Invasive Goldenrod _Solidago canadensis_ Despite the Absence of Population Structure</center>
#' pagetitle: RMarkdown document from:&nbsp;Eckert&nbsp;et&nbsp;al.&nbsp;(2022)
#' subtitle: <center>doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.3389/fevo.2022.856453">10.3389/fevo.2022.856453</a></center>
#' author: <center>Eckert, S., Herden, J., Stift, M., Durka, W., van Kleunen, M., & Joshi, J.</center>
#' date: <center>`r Sys.Date()`</center>
#' abstract: <p align="justify">This RMarkdown script belongs
#'   to a series of scripts generated by Silvia Eckert as part of
#'   the statistical analysis for the above-mentioned manuscript.
#'   The data underlying the applied R code can be found in the ZENODO
#'   repository and contains genetic (AFLP) and epigenetic (MSAP) markers
#'   from offspring of 25 _Solidago canadensis_ populations sampled along a
#'   latitudinal gradient in Central Europe. This particular RMarkdown script
#'   applies plotting BayeScan genome-scan results. <b>Please cite this
#'   script as follows:</b></p><br><p>Eckert, S., Herden, J.,
#'   Stift, M., Durka, W., van Kleunen, M., & Joshi, J. (2022). Data From&colon;
#'   Traces of Genetic but Not Epigenetic Adaptation in the Invasive
#'   Goldenrod _Solidago canadensis_ Despite the Absence of Population
#'   Structure. _Zenodo_. doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.5281/zenodo.6388135">10.5281/zenodo.6388135</a></center></p>
#' geometry: margin=2cm
#' output:
#'   html_document:
#'      code_folding: show
#'      keep_md: FALSE
#'      theme: flatly
#'      highlight: textmate
#'      df_print: paged
#'      toc: true
#'      toc_float: true
#' ---
#' 

#'
#'```{r setup, include = FALSE}
#'knitr::opts_chunk$set(eval=FALSE, cache=FALSE, warning=FALSE)
#'```

#' # Packages
#' <a href="#top">Back to top</a>
#+ project_packages, results='hide', message=FALSE, warning=FALSE
########### packages ...................... ####
# install.packages("name_of_package") # install necessary packages
# install knitr to save this script as html output using RStudio with Ctrl+Shift+K (Windows & Linux) or Command+Shift+K (macOS)
# install.packages("knitr") 
# getwd() # get current working directory
# setwd() # set working directory
# create folder for datasets to be stored to get this RMarkdown script running
dir.create("./data",
           showWarnings=F)
# add necessary libraries
library(tibble)
# remotes::install_github("romunov/zvau")
library(zvau)
library(adegenet)
library(ggplot2)
library(cowplot)
library(coda)

#' # Load data
#' <a href="#top">Back to top</a>
#+ project_load.data
########### load data ....................... ####
#' ## AFLP
#+ project_load.AFLP
######## AFLP ####
# transform to genind object
# presence/absence data (@type: PA)
AFLP.genind <- df2genind(AFLP[,-c(1:8)],
                         sep=",",
                         pop=AFLP$populationID,
                         ind=AFLP$uniqueID,
                         strata=AFLP[,c(1:8)],
                         ploidy=2,
                         type=c("PA")); AFLP.genind
# subset data to control plants
AFLP_C <- AFLP[AFLP$treatment=="CON",]; dim(AFLP_C)
# presence/absence data (@type: PA)
AFLP_C.genind <- df2genind(AFLP_C[,-c(1:8)],
                           sep=",",
                           pop=AFLP_C$populationID,
                           ind=AFLP_C$uniqueID,
                           strata=AFLP_C[,c(1:8)],
                           ploidy=2,
                           type=c("PA")); AFLP_C.genind
tibble(strata(AFLP_C.genind)) # strata

#' ## MSAP-n
#' <a href="#top">Back to top</a>
#+ project_load.MSAPn
######## MSAP-n ####
# transform to genind object
MSAPn.genind <- df2genind(MSAPn[,-c(1:8)],
                           sep=",",
                           pop=MSAPn$populationID,
                           ind=MSAPn$uniqueID,
                           strata=MSAPn[,c(1:8)],
                           ploidy=2,
                           type=c("PA")); MSAPn.genind
# subset to control plants (for later LEA analyses)
MSAPn_C <- MSAPn[MSAPn$treatment=="CON",]; dim(MSAPn_C)
MSAPn_C.genind <- df2genind(MSAPn_C[,-c(1:8)],
                             sep=",",
                             pop=MSAPn_C$populationID,
                             ind=MSAPn_C$uniqueID,
                             strata=MSAPn_C[,c(1:8)],
                             ploidy=2,
                             type=c("PA")); MSAPn_C.genind
tibble(strata(MSAPn_C.genind)) # strata

#' ## MSAP-m
#' <a href="#top">Back to top</a>
#+ project_load.MSAPm
######## MSAP-m ####
# transform to genind object
MSAPm.genind <- df2genind(MSAPm[,-c(1:8)],
                           sep=",",
                           pop=MSAPm$populationID,
                           ind=MSAPm$uniqueID,
                           strata=MSAPm[,c(1:8)],
                           ploidy=2,
                           type=c("PA")); MSAPm.genind
# subset to control plants (for later LEA analyses)
MSAPm_C <- MSAPm[MSAPm$treatment=="CON",]; dim(MSAPm_C)
MSAPm_C.genind <- df2genind(MSAPm_C[,-c(1:8)],
                             sep=",",
                             pop=MSAPm_C$populationID,
                             ind=MSAPm_C$uniqueID,
                             strata=MSAPm_C[,c(1:8)],
                             ploidy=2,
                             type=c("PA")); MSAPm_C.genind
tibble(strata(MSAPm_C.genind)) # strata

#' # BayeScan
#' <a href="#top">Back to top</a>
#+ project_bayescan
######## BAYESCAN ................... ####
#' ## AFLP
#' <a href="#top">Back to top</a>
#+ project_bayescan.aflp
######## AFLP ####
# load BayeScan data (Fst table)
AFLP_BayeScan.data <- tibble(read.table("Data_BayeScan_AFLP_fst.txt",
                                        header=T)); AFLP_BayeScan.data
AFLP_BayeScan.data$ID <- names(AFLP_C)[-c(1:8)]
# add locus IDs (dye from multiplexing and base-pair position)
AFLP_BayeScan.data$marker <- names(AFLP_C)[-c(1:8)]
# replace FAM_AAC_CCT_* with FAM
AFLP_BayeScan.data$marker <- stringr::str_replace(AFLP_BayeScan.data$marker,
                                                  "FAM_AAC_CCT_",
                                                  "AACCCT_")
# replace VIC_ACG_CAT_* with VIC
AFLP_BayeScan.data$marker <- stringr::str_replace(AFLP_BayeScan.data$marker,
                                                  "VIC_ACG_CAT_",
                                                  "ACGCAT_")
# replace NED_ACC_CTG_* with NED
AFLP_BayeScan.data$marker <- stringr::str_replace(AFLP_BayeScan.data$marker,
                                                  "NED_ACC_CTG_",
                                                  "ACCCTG_")
# replace PET_AGG_CGA_* with PET
AFLP_BayeScan.data$marker <- stringr::str_replace(AFLP_BayeScan.data$marker,
                                                  "PET_AGG_CGA_",
                                                  "AGGCGA_")
AFLP_BayeScan.data$marker # check
# negative logarithm on the basis of 10
AFLP_BayeScan.data$log10.qVal <- -log10(AFLP_BayeScan.data$qval)
# add dye
AFLP_BayeScan.data$dye <- AFLP_BayeScan.data$marker
AFLP_BayeScan.data$dye <- stringr::str_replace(AFLP_BayeScan.data$dye,
                                               "AACCCT[0-9|_]+",
                                               "FAM")
AFLP_BayeScan.data$dye <- stringr::str_replace(AFLP_BayeScan.data$dye,
                                               "ACGCAT[0-9|_]+",
                                               "VIC")
AFLP_BayeScan.data$dye <- stringr::str_replace(AFLP_BayeScan.data$dye,
                                               "ACCCTG[0-9|_]+",
                                               "NED")
AFLP_BayeScan.data$dye <- stringr::str_replace(AFLP_BayeScan.data$dye,
                                               "AGGCGA[0-9|_]+",
                                               "PET")
AFLP_BayeScan.data$dye # check
AFLP_BayeScan.data
# subset to the significant ones (-log10 of p-value is > or < 1.301)
AFLP_signf.loc <- AFLP_BayeScan.data[(AFLP_BayeScan.data$log10.PO. > 1.3 |
                                        AFLP_BayeScan.data$log10.PO.<-1.3),]
AFLP_signf.loc
# save trimmed marker data
write.table(AFLP_signf.loc,
            row.names=F,
            file="./data/Data_BayeScan_AFLP_outliers.txt")
# and plot
AFLP_signf.loc$plot_label <- "loc185"; AFLP_signf.loc
set.seed(123)
AFLP_BayeScan.plot <- ggplot(AFLP_BayeScan.data,
                             aes(x=log10.PO.,
                                 y=fst)) +
  geom_point(alpha=0.3,
             size=2) +
  coord_cartesian(ylim=c(0,0.2),
                  xlim=c(-1.5,2.5)) +
  labs(title="AFLP",
       x=expression(paste(-log[10]*"("*italic(PO)*")")),
       y=expression(paste(italic(F)[ST]))) +
  geom_vline(xintercept=-log10(0.05),
             linetype="longdash",
             color="gray") +
  theme_cowplot() +
  theme(axis.line.y.right=element_line(color="transparent"),
        axis.ticks.y.right=element_blank(),
        axis.text.y.right=element_text(color="transparent"),
        panel.border=element_rect(color="black"),
        legend.position="none") +
  scale_color_manual(values=c("blue","black","red","green3")) +
  ggrepel::geom_text_repel(data=AFLP_signf.loc,
                           aes(x=log10.qVal,
                               y=fst,
                               label=plot_label),
                           color="green3"); AFLP_BayeScan.plot

#' ## MSAP-n
#' <a href="#top">Back to top</a>
#+ project_bayescan.MSAPn
######## MSAP-n ####
# load BayeScan data (Fst table)
MSAPn_BayeScan.data <- tibble(read.table("./data/Data_BayeScan_MSAPn_fst.txt",
                                          header=T)); MSAPn_BayeScan.data
MSAPn_BayeScan.data$ID <- names(data.frame(MSAPn.genind@tab))
# add locus IDs (dye from multiplexing and base-pair position)
MSAPn_BayeScan.data$marker <- names(data.frame(MSAPn.genind@tab))
# replace FAM_AAC_CCT_* with FAM
MSAPn_BayeScan.data$marker <- stringr::str_replace(MSAPn_BayeScan.data$marker,
                                                    "uFAM_AAC_CCT_",
                                                    "AACCCT_")
MSAPn_BayeScan.data$marker <- stringr::str_replace(MSAPn_BayeScan.data$marker,
                                                    "uVIC_ACG_CAT_",
                                                    "ACGCAT_")
MSAPn_BayeScan.data$marker <- stringr::str_replace(MSAPn_BayeScan.data$marker,
                                                    "uNED_ACC_CTG_",
                                                    "ACCCTG_")
MSAPn_BayeScan.data$marker <- stringr::str_replace(MSAPn_BayeScan.data$marker,
                                                    "uPET_AGG_CGA_",
                                                    "AGGCGA_")
MSAPn_BayeScan.data$marker # check
# negative logarithm on the basis of 10
MSAPn_BayeScan.data$log10.qVal <- -log10(MSAPn_BayeScan.data$qval)
# add dye
MSAPn_BayeScan.data$dye <- MSAPn_BayeScan.data$marker
MSAPn_BayeScan.data$dye <- stringr::str_replace(MSAPn_BayeScan.data$dye,
                                                 "AACCCT[0-9|_]+",
                                                 "FAM")
MSAPn_BayeScan.data$dye <- stringr::str_replace(MSAPn_BayeScan.data$dye,
                                                 "ACGCAT[0-9|_]+",
                                                 "VIC")
MSAPn_BayeScan.data$dye <- stringr::str_replace(MSAPn_BayeScan.data$dye,
                                                 "ACCCTG[0-9|_]+",
                                                 "NED")
MSAPn_BayeScan.data$dye <- stringr::str_replace(MSAPn_BayeScan.data$dye,
                                                 "AGGCGA[0-9|_]+",
                                                 "PET")
MSAPn_BayeScan.data$dye # check
MSAPn_BayeScan.data
# subset to the significant ones (-log10 of p-value is > or < 1.301)
MSAPn_signf.loc <- MSAPn_BayeScan.data[(MSAPn_BayeScan.data$log10.PO.>1.3 |
                                            MSAPn_BayeScan.data$log10.PO.<-1.3),]
MSAPn_signf.loc
# save trimmed marker data
write.table(MSAPn_signf.loc,
            row.names=F,
            file="./data/Data_BayeScan_MSAPn_outliers.txt")
# and plot
set.seed(123)
MSAPn_BayeScan.plot <- ggplot(MSAPn_BayeScan.data,
                              aes(x=log10.PO.,
                                  y=fst)) +
  geom_point(alpha=0.3,
             size=2) +
  coord_cartesian(ylim=c(0,0.2),
                  xlim=c(-1.5,2.5)) +
  labs(title="MSAP-n",
       x=expression(paste(-log[10]*"("*italic(PO)*")")),
       y="") +
  geom_vline(xintercept=-log10(0.05),
             linetype="longdash",
             color="gray") +
  theme_cowplot() +
  theme(axis.line.y.right=element_line(color="transparent"),
        axis.ticks.y.right=element_blank(),
        axis.text.y.right=element_text(color="transparent"),
        panel.border=element_rect(color="black"),
        legend.position="none") +
  scale_color_manual(values=c("blue","black","red","green")) +
  ggrepel::geom_text_repel(data=MSAPn_signf.loc,
                           aes(x=log10.qVal,
                               y=fst,
                               label=marker)); MSAPn_BayeScan.plot

#' ## MSAP-m
#' <a href="#top">Back to top</a>
#+ project_bayescan.MSAPm
######## MSAP-m ####
# load BayeScan data (Fst table)
MSAPm_BayeScan.data <- tibble(read.table("./data/Data_BayeScan_MSAPm_fst.txt",
                                          header=T)); MSAPm_BayeScan.data
MSAPm_BayeScan.data$ID <- names(data.frame(MSAPm.genind@tab))
# add locus IDs (dye from multiplexing and base-pair position)
MSAPm_BayeScan.data$marker <- names(data.frame(MSAPm.genind@tab))
# replace FAM_AAC_CCT_* with FAM
MSAPm_BayeScan.data$marker <- stringr::str_replace(MSAPm_BayeScan.data$marker,
                                                    "MFAM_AAC_CCT_",
                                                    "AACCCT_")
# replace VIC_ACG_CAT_* with VIC
MSAPm_BayeScan.data$marker <- stringr::str_replace(MSAPm_BayeScan.data$marker,
                                                    "MVIC_ACG_CAT_",
                                                    "ACGCAT_")
# replace NED_ACC_CTG_* with NED
MSAPm_BayeScan.data$marker <- stringr::str_replace(MSAPm_BayeScan.data$marker,
                                                    "MNED_ACC_CTG_",
                                                    "ACCCTG_")
# replace PET_AGG_CGA_* with PET
MSAPm_BayeScan.data$marker <- stringr::str_replace(MSAPm_BayeScan.data$marker,
                                                    "MPET_AGG_CGA_",
                                                    "AGGCGA_")
MSAPm_BayeScan.data$marker # check
# negative logarithm on the basis of 10
MSAPm_BayeScan.data$log10.qVal <- -log10(MSAPm_BayeScan.data$qval)
# add dye
MSAPm_BayeScan.data$dye <- MSAPm_BayeScan.data$marker
MSAPm_BayeScan.data$dye <- stringr::str_replace(MSAPm_BayeScan.data$dye,
                                                 "AACCCT[0-9|_]+",
                                                 "FAM")
MSAPm_BayeScan.data$dye <- stringr::str_replace(MSAPm_BayeScan.data$dye,
                                                 "ACGCAT[0-9|_]+",
                                                 "VIC")
MSAPm_BayeScan.data$dye <- stringr::str_replace(MSAPm_BayeScan.data$dye,
                                                 "ACCCTG[0-9|_]+",
                                                 "NED")
MSAPm_BayeScan.data$dye <- stringr::str_replace(MSAPm_BayeScan.data$dye,
                                                 "AGGCGA[0-9|_]+",
                                                 "PET")
MSAPm_BayeScan.data$dye # check
MSAPm_BayeScan.data
# subset to the significant ones (-log10 of p-value is > or < 1.301)
MSAPm_signf.loc <- MSAPm_BayeScan.data[(MSAPm_BayeScan.data$log10.PO.>1.3 |
                                            MSAPm_BayeScan.data$log10.PO.<-1.3),]
MSAPm_signf.loc
# save trimmed marker data
write.table(MSAPm_signf.loc,
            row.names=F,
            file="./data/Data_BayeScan_MSAPm_outliers.txt")
# and plot
set.seed(123)
MSAPm_BayeScan.plot <- ggplot(MSAPm_BayeScan.data,
                              aes(x=log10.PO.,
                                  y=fst)) +
  geom_point(alpha=0.3,
             size=2) +
  coord_cartesian(ylim=c(0,0.2),
                  xlim=c(-1.5,2.5))+
  labs(title="MSAP-m",
       x=expression(paste(-log[10]*"("*italic(PO)*")")),
       y="") +
  geom_vline(xintercept=-log10(0.05),
             linetype="longdash",
             color="gray") +
  theme_cowplot() +
  theme(axis.line.y.right=element_line(color="transparent"),
        axis.ticks.y.right=element_blank(),
        axis.text.y.right=element_text(color="transparent"),
        panel.border=element_rect(color="black"),
        legend.position="none") +
  scale_color_manual(values=c("blue","black","red","green")) +
  ggrepel::geom_text_repel(data=MSAPm_signf.loc,
                           aes(x=log10.qVal,
                               y=fst,
                               label=marker)); MSAPm_BayeScan.plot

#' # BayeScan chain convergence
#' <a href="#top">Back to top</a>
#+ project_bayescan.convergence
######## MCMC convergence ..... ####
#' ## AFLP
#+ project_bayescan.convergence_AFLP, fig.dim = c(10,8)
######## AFLP ####
# read chains
AFLP_chain <- read.table("./data/Data_BayeScan_AFLP.sel",
                         header=TRUE)
# create MCMC with correct thinning interval
AFLP_chain_thinned <- mcmc(AFLP_chain,
                           thin=10)
# plot chains
plot(AFLP_chain_thinned)
# summary statistics
summary(AFLP_chain_thinned)
# check sample size
autocorr.diag(AFLP_chain_thinned)
# effective sample size
effectiveSize(AFLP_chain_thinned)
# Geweke's convergence diagnostic
geweke.diag(AFLP_chain_thinned,
            frac1=0.1,
            frac2=0.5)
# plot Geweke's convergence diagnostic
# at p = 0.05, the critical values of z are - 1.96 and +1.96
# i.e. H0 (equality of means => convergence) is rejected if z < -1.96 or z > +1.96
geweke.plot(AFLP_chain_thinned,
            frac1=0.1,
            frac2=0.5,
            nbins=20,
            pvalue=0.05,
            auto.layout=T,
            ask=F)

#' ## MSAP-m
#' <a href="#top">Back to top</a>
#+ project_bayescan.convergence_MSAPm, fig.dim = c(10,8)
######## MSAP-m ####
# read chains
MSAPm_chain <- read.table("./data/Data_BayeScan_MSAPm.sel",
                           header=TRUE)
# create MCMC with correct thinning interval
MSAPm_chain_thinned <- mcmc(MSAPm_chain,
                             thin=10)
# plot chains
plot(MSAPm_chain_thinned)
# summary statistics
summary(MSAPm_chain_thinned)
# check sample size
autocorr.diag(MSAPm_chain_thinned)
# effective sample size
effectiveSize(MSAPm_chain_thinned)
# Geweke's convergence diagnostic
geweke.diag(MSAPm_chain_thinned,
            frac1=0.1,
            frac2=0.5)
# plot Geweke's convergence diagnostic
# at p = 0.05, the critical values of z are - 1.96 and +1.96
# i.e. H0 (equality of means => convergence) is rejected if z < -1.96 or z > +1.96
geweke.plot(MSAPm_chain_thinned,
            frac1=0.1,
            frac2=0.5,
            nbins=20,
            pvalue=0.05,
            auto.layout=T,
            ask=F)

#' ## MSAP-n
#' <a href="#top">Back to top</a>
#+ project_bayescan.convergence_MSAPn, fig.dim = c(10,8)
######## MSAP-n ####
# read chains
MSAPn_chain <- read.table("./data/Data_BayeScan_MSAPn.sel",
                           header=TRUE)
# create MCMC with correct thinning interval
MSAPn_chain_thinned <- mcmc(MSAPn_chain,
                             thin=10)
# plot chains
plot(MSAPn_chain_thinned)
# summary statistics
summary(MSAPn_chain_thinned)
# check sample size
autocorr.diag(MSAPn_chain_thinned)
# effective sample size
effectiveSize(MSAPn_chain_thinned)
# Geweke's convergence diagnostic
geweke.diag(MSAPn_chain_thinned,
            frac1=0.1,
            frac2=0.5)
# plot Geweke's convergence diagnostic
# at p = 0.05, the critical values of z are - 1.96 and +1.96
# i.e. H0 (equality of means => convergence) is rejected if z < -1.96 or z > +1.96
geweke.plot(MSAPn_chain_thinned,
            frac1=0.1,
            frac2=0.5,
            nbins=20,
            pvalue=0.05,
            auto.layout=T,
            ask=F)

#' # Figure S7
#' <a href="#top">Back to top</a>
#+ project_figureS7, fig.dim = c(10,6)
######## Figure S7 ......................... ####
# combine plots
BayeScan_combi <- plot_grid(AFLP_BayeScan.plot,
                            MSAPm_BayeScan.plot,
                            MSAPn_BayeScan.plot,
                            ncol=3,
                            rel_widths=c(1,1,1),
                            label_size=18,
                            labels=c("A","B","C")) +
  theme(plot.margin=unit(c(1,1,1,1),"cm")); BayeScan_combi
# save as png
ggsave(BayeScan_combi,
       file="./data/FigureS7_Eckert_et_al_2022_BayeScan_OutlierScan.png",
       dpi=300,
       width=12,
       height=5)
# save as tiff
ggsave(BayeScan_combi,
       file="./data/FigureS7_Eckert_et_al_2022_BayeScan_OutlierScan.TIFF",
       dpi=300,
       width=12,
       height=5,
       device=grDevices::tiff)

#' <a href="#top">Back to top</a>
#+ Session.info
sessionInfo()
#' <a href="#top">Back to top</a>
######## Session info ................ ####