#' ---
#' title: <center><b>Markdown document from&colon;</b><br>Traces of Genetic but Not Epigenetic Adaptation in the Invasive Goldenrod _Solidago canadensis_ Despite the Absence of Population Structure</center>
#' pagetitle: RMarkdown document from:&nbsp;Eckert&nbsp;et&nbsp;al.&nbsp;(2022)
#' subtitle: <center>doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.3389/fevo.2022.856453">10.3389/fevo.2022.856453</a></center>
#' author: <center>Eckert, S., Herden, J., Stift, M., Durka, W., van Kleunen, M., & Joshi, J.</center>
#' date: <center>`r Sys.Date()`</center>
#' abstract: <p align="justify">This RMarkdown script belongs
#'   to a series of scripts generated by Silvia Eckert as part of
#'   the statistical analysis for the above-mentioned manuscript.
#'   The data underlying the applied R code can be found in the ZENODO
#'   repository and contains genetic (AFLP) and epigenetic (MSAP) markers
#'   from offspring of 25 _Solidago canadensis_ populations sampled along a
#'   latitudinal gradient in Central Europe. This particular RMarkdown script
#'   applies principal components analysis on WorldClim 2.0 climate data at 
#'   the source population sites. <b>Please cite this
#'   script as follows:</b></p><br><p>Eckert, S., Herden, J.,
#'   Stift, M., Durka, W., van Kleunen, M., & Joshi, J. (2022). Data From&colon;
#'   Traces of Genetic but Not Epigenetic Adaptation in the Invasive
#'   Goldenrod _Solidago canadensis_ Despite the Absence of Population
#'   Structure. _Zenodo_. doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.5281/zenodo.6388135">10.5281/zenodo.6388135</a></center></p>
#' geometry: margin=2cm
#' output:
#'   html_document:
#'      code_folding: show
#'      keep_md: FALSE
#'      theme: flatly
#'      highlight: textmate
#'      df_print: paged
#'      toc: true
#'      toc_float: true
#' ---
#' 

#'
#'```{r setup, include = FALSE}
#'knitr::opts_chunk$set(eval=FALSE, cache=FALSE, warning=FALSE)
#'```

#' # Packages
#' <a href="#top">Back to top</a>
#+ project_packages, results='hide', message=FALSE, warning=FALSE
########### packages ...................... ####
# install.packages("name_of_package") # install necessary packages
# install knitr to save this script as html output using RStudio with Ctrl+Shift+K (Windows & Linux) or Command+Shift+K (macOS)
# install.packages("knitr") 
# getwd() # get current working directory
# setwd() # set working directory
# create folder for datasets to be stored to get this RMarkdown script running
dir.create("./data",
           showWarnings=F)
# add necessary libraries
library(vegan)
library(BiodiversityR)
library(VIM)
library("PerformanceAnalytics")
library(raster)
library(sp)
library(ggplot2)
library(ggfortify)
library(ggrepel)
library(cowplot)
library(tibble)
#install.packages("remotes")
#remotes::install_github("grasshoppermouse/hagenutils")
library(hagenutils)
library(factoextra)
library(cowplot)

#' ## Functions
#' <a href="#top">Back to top</a>
#+ project_functions
########## functions ####
# modified function pca_loadings_plot() from package hagenutils
pca_loadings_plot2 <- function (obj, components = 1:3, sortby = 1) {
  require(dplyr)
  pca_summ <- summary(obj)
  comp_nms <- colnames(pca_summ$importance)
  varprop <- pca_summ$importance[2, components]
  nms <- comp_nms[components]
  varprop <- paste0(nms, " (", round(varprop * 100, 1),
                    "%)")
  names(varprop) <- nms
  loadings <- obj$rotation[, components, drop = F]
  loadings %>% data.frame %>% dplyr::mutate(Variable = forcats::fct_reorder(rownames(.),
                                                                            loadings[, sortby])) %>% tidyr::gather(key = PC, value = Loading,
                                                                                                                   -Variable) %>% dplyr::mutate(PC = varprop[PC]) %>% ggplot2::ggplot() +    ggalt::geom_lollipop(ggplot2::aes(Loading, Variable,
                                      colour = Loading), size = 1, horizontal = T) + ggplot2::scale_color_gradient2(low = "gray50",
                                                                                                                    mid = "gray50", high = "gray50") + ggplot2::geom_vline(color="gray20", xintercept = 0) +
    ggplot2::facet_wrap(~PC) + ggplot2::theme_bw(15)
  }
# modified function evplot() from https://www.mohanwugupta.com/post/broken_stick/
bstick_plot = function(ev) {
  # Broken stick model (MacArthur 1957)
  n = length(ev)  
  bsm = data.frame(j=seq(1:n), p=0)  
  bsm$p[1] = 1/n
  for (i in 2:n) bsm$p[i] = bsm$p[i-1] + (1/(n + 1 - i))  
  bsm$p = 100*bsm$p/n
  # Plot eigenvalues and % of variation for each axis  
  op = par(mfrow=c(2,1),omi=c(0.1,0.2,0.1,0.1), mar=c(1, 4.5, 1, 1))  
  barplot(ev, #main="Eigenvalues",
          col=c(rep("gray50",3), rep("gray80", length(ev))),
          ylab="Eigenvalue", las=2)  
  abline(h=mean(ev), col="black")
  mtext(side=3, line=0, at=-8.2, cex=1.5,
        text=expression(paste(bold("A"))))
  legend("topright", "Average eigenvalue", lwd=1,
         col="black", bty="n")  
  barplot(t(cbind(100*ev/sum(ev), bsm$p[n:1])), beside=TRUE,   
          #main="% variation",
          ylab="Explained variance [%]",
          col=c("gray80","gray20"), las=2)  
  legend("topright", c("% eigenvalue", "Broken stick model"),   
         pch=15, col=c("gray80","gray20"), bty="n")
  mtext(side=3, line=0, at=-20, cex=1.5,
        text=expression(paste(bold("B"))))
  par(op)
  }

#' # Load data
#' <a href="#top">Back to top</a>
#+ project_load.data
########### Load data ...................... ####
source("RMarkdown_Eckert_et_al_2022_loadWorldclimData.R")
ClimData <- tibble(read.table("./data/Data_wc2_PopulationData.txt",
                             header=T,
                             row.names=1)); ClimData

#' # PCA
#' <a href="#top">Back to top</a>
#+ project_PCA
########## PCA ............................... ####
# principal components analysis (PCA) based on correlation matrix
SCclim.pca <- prcomp(ClimData[,c(4:25)],
                     retx=TRUE,
                     center=TRUE,
                     scale=TRUE)
length(colnames(SCclim.pca$rotation)) # number of axes returned: 21
# scree plot and broken-stick model
SCclim.pca_df <- tibble(data.frame(eigenvalue=SCclim.pca$sdev^2,
                                   position=c(1:length(SCclim.pca$sdev^2))))
SCclim.pca_df
# average loading
p1a <- ggplot(data=SCclim.pca_df[1:10,],
              aes(y=eigenvalue,
                  x=position)) +
  geom_bar(stat="identity",
           fill=c(rep("gray50",3),rep("gray80",10-3)),
           color="gray20") +
  labs(y="Eigenvalue\n",
       x="") +
  scale_x_continuous(expand=c(0.01,0.01)) +
  geom_hline(yintercept=mean(SCclim.pca_df$eigenvalue),
             linetype=2) +
  annotate(geom="text",
           x=5,
           y=1.5,
           hjust=0,
           vjust=1,
           label="Average eigenvalue") +
  theme_cowplot() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        panel.border=element_rect(color="black", fill=NA)); p1a
# Broken-stick model
n <- length(SCclim.pca$sdev^2); n # the number of features  
bsm <- data.frame(j=seq(1:n),p=0); bsm # calculate model
bsm$p[1] = 1/n
for (i in 2:n) bsm$p[i] = bsm$p[i-1]+(1/(n+1-i))  
bsm$p = 100*bsm$p/n
eig_bsm_df <- tibble(eig_var = 100*SCclim.pca$sdev^2/sum(SCclim.pca$sdev^2),
                     bsm = bsm$p[n:1])
eig_bsm_df$groupvar <- letters[1:length(eig_bsm_df$eig_var)]; eig_bsm_df
eig_bsm_df_melted <- tibble(reshape2::melt(eig_bsm_df,
                                           by=list(eig_bsm_df$groupvar)))
eig_bsm_df_melted$groupvar <- as.factor(eig_bsm_df_melted$groupvar)
eig_bsm_df_melted <- eig_bsm_df_melted[order(eig_bsm_df_melted$groupvar),]
eig_bsm_df_melted
# plot model
p1b <- ggplot(data=eig_bsm_df_melted[1:20,],
              aes(y=value,
                  x=groupvar,
                  fill=variable)) +
  geom_bar(stat="identity",
           position="dodge",
           color="gray20") +
  labs(y="Eigenvalue [%]",
       x="") +
  scale_fill_manual("legend",
                    labels=c("% eigenvalue","Broken-stick model"),
                    values=c("eig_var"="gray80",
                             "bsm"="gray20")) +
  theme_cowplot() +
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        legend.title=element_blank(),
        legend.position=c(.3,.9),
        panel.border=element_rect(color="black",
                                  fill=NA)); p1b
# combine
p1_combined <- plot_grid(p1a,
                         p1b,
                         ncol=2,
                         nrow=1,
                         rel_heights=c(.8,1))
p1 <- ggdraw(add_sub(p1_combined,
                     "Principal components (PC)",
                     vpadding=grid::unit(0,"lines"),
                     y=6.2,
                     x=0.5,
                     vjust=4.5)); p1

# adjust abbreviation of loadings and use as row names (if necessary!)
names(ClimData[,c(4:22,24:25)]) # extract the climate variable names
ClimVar <- data.frame(label=c("T[A]","T[D-range]","T[iso]","T[season]",
                              "T[M-warmest]","T[M-coldest]","T[A-range]",
                              "T[Q-wettest]","T[Q-dryest]","T[Q-warmest]",
                              "T[Q-coldest]", "P[A]", "P[M-wettest]",
                              "P[M-dryest]", "P[season]", "P[Q-wettest]",
                              "P[Q-dryest]","P[Q-warmest]", "P[Q-coldest]",
                              "Radiation[solar]", "Wind[speed]"),
                      explanation=c("BIO1 = Annual Mean Temperature",
                                    "BIO2 = Mean Diurnal Range (Mean of monthly (max temp - min temp))",
                                    "BIO3 = Isothermality (BIO2/BIO7) (* 100)",
                                    "BIO4 = Temperature Seasonality (standard deviation *100)",
                                    "BIO5 = Max Temperature of Warmest Month (°C*10)",
                                    "BIO6 = Min Temperature of Coldest Month (°C*10)",
                                    "BIO7 = Temperature Annual Range (BIO5-BIO6)",
                                    "BIO8 = Mean Temperature of Wettest Quarter (°C*10)",
                                    "BIO9 = Mean Temperature of Driest Quarter (°C*10)",
                                    "BIO10 = Mean Temperature of Warmest Quarter (°C*10)",
                                    "BIO11 = Mean Temperature of Coldest Quarter (°C*10)",
                                    "BIO12 = Annual Precipitation (mm)",
                                    "BIO13 = Precipitation of Wettest Month (mm)",
                                    "BIO14 = Precipitation of Driest Month (mm)",
                                    "BIO15 = Precipitation Seasonality (Coefficient of Variation)",
                                    "BIO16 = Precipitation of Wettest Quarter (mm)",
                                    "BIO17 = Precipitation of Driest Quarter (mm)",
                                    "BIO18 = Precipitation of Warmest Quarter (mm)",
                                    "BIO19 = Precipitation of Coldest Quarter (mm)",
                                    "CV solar radiation (kJ m-2 day-1)",
                                    "Average wind speed (m s-1)")); ClimVar

#' ## Biplot
#' <a href="#top">Back to top</a>
#+ project_PCA_biplot
########## biplot ####
# PCA axis 1 and 2
set.seed(123)
p2a <- fviz_pca_biplot(SCclim.pca,
                       repel=T,
                       label="all",
                       col.var="gray20",
                       col.ind="gray40",
                       pointsize = 4) +
  labs(title=NULL,
       x="PC1 (40.3 %)",
       y="PC2 (32.7 %)") +
  theme_cowplot() +
  theme(panel.border=element_rect(colour="black",
                                  fill=NA,
                                  size=1),
        panel.grid.major = element_line(colour="gainsboro"),
        panel.grid.minor = element_line(colour="gainsboro")); p2a
# axis 1 and 2
set.seed(123)
p2b <- fviz_pca_biplot(SCclim.pca,
                       repel=T,
                       label="all",
                       axes=c(2,3),
                       col.var="gray20",
                       col.ind="gray40",
                       pointsize=4) +
  labs(title=NULL,
       x="PC2 (32.7 %)",
       y="PC3 (14.4 %)") +
  theme_cowplot() +
  theme(panel.border=element_rect(colour="black",
                                  fill=NA,
                                  size=1),
        panel.grid.major=element_line(colour="gainsboro"),
        panel.grid.minor = element_line(colour="gainsboro")); p2b

#' ## Loadings
#' <a href="#top">Back to top</a>
#+ project_PCA_loadings
########## loadings ####
# barplots showing above average contribution (red dashed line in contribution plot)
1/length(ClimData[,c(4:22,24:25)]) * 100
# PC1
p.PC1 <- fviz_contrib(SCclim.pca,
                      "var",
                      axes=1,
                      fill="gray80",
                      title="PC1",
                      top=12)+
  labs(y="Contribution [%]",
       x="")+
  theme_cowplot()+
  theme(axis.text.x=element_text(angle=45,
                                 hjust=1,
                                 size=10),
        panel.border=element_rect(colour="black",
                                  fill=NA,
                                  size=1)); p.PC1
# PC1 contribution
p.PC1$data
# PC2
p.PC2 <- fviz_contrib(SCclim.pca,
                      "var",
                      axes=2,
                      fill="gray80",
                      title="PC2",
                      top=12) +
  labs(y="",
       x=" \n ") +
  theme_cowplot() +
  theme(axis.text.x=element_text(angle=45,
                                 hjust=1,
                                 size=10),
        panel.border=element_rect(colour="black",
                                  fill=NA,
                                  size=1)); p.PC2
# PC2 contribution
p.PC2$data
# PC3
p.PC3 <- fviz_contrib(SCclim.pca,
                      "var",
                      axes=3,
                      fill="gray80",
                      title="PC3",
                      top=12) +
  labs(y="",
       x=" \n ") +
  theme_cowplot()+
  theme(axis.text.x=element_text(angle=45,
                                 hjust=1,
                                 size=10),
        panel.border=element_rect(colour="black",
                                  fill=NA,
                                  size=1)); p.PC3
# PC3 contribution
p.PC3$data
# combine
p3 <- plot_grid(p.PC1,
                p.PC2,
                p.PC3,
                ncol=3,
                nrow=1,
                label_size=20); p3
# lollipop plots
p4 <- pca_loadings_plot2(SCclim.pca,
                         components=c(1,2)) +
  labs(title="PCA - Loadings",
       y=NULL) +
  theme_cowplot() +
  theme(panel.border=element_rect(colour="black",
                                  fill=NA,
                                  size=1),
        panel.grid.major=element_line(colour="gainsboro"),
        panel.grid.minor=element_line(colour="gainsboro"),
        legend.position="none",
        panel.spacing=unit(2,"lines"),
        strip.background=element_rect(fill="transparent"),
        strip.text=element_text(face="bold")); p4

#' # Figure S8
#' <a href="#top">Back to top</a>
#+ project_FigureS8
########## Figure S8 ....................... ####
# combine p2a and p2b
p2 <- plot_grid(p2a,
                p2b); p2
# combine with other plots
PCA.p <- plot_grid(p2,
                   p1,
                   p3,
                   nrow=3,
                   ncol=1,
                   labels=LETTERS[1:3],
                   label_size=26,
                   label_x=-0.02) +
  theme(plot.margin=unit(c(1,1,1,1),"cm")); PCA.p
# save as png
ggsave(PCA.p,
       file="./data/FigureS8_Eckert_et_al_2022_PCA_WorldClim.png",
       dpi=300,
       width=10,
       height=15)
# save as tiff
ggsave(PCA.p,
       file="./data/FigureS8_Eckert_et_al_2022_PCA_WorldClim.TIFF",
       dpi=300,
       width=10,
       height=15,
       device=grDevices::tiff)

# save data
scores = as.data.frame(SCclim.pca$x[,1:3]); tibble(scores)
scores$lat <- ClimData$Latitude
scores$lon <- ClimData$Longitude
tibble(scores)
# write PC axes to table
write.table(scores,
            row.names=F,
            file="./data/Data_PCA_WorldClim.txt")

#' # Session info
#' <a href="#top">Back to top</a>
#+ Session.info
sessionInfo()
#' <a href="#top">Back to top</a>
######## Session info .................. ####