#' ---
#' title: <center><b>Markdown document from&colon;</b><br>Traces of Genetic but Not Epigenetic Adaptation in the Invasive Goldenrod _Solidago canadensis_ Despite the Absence of Population Structure</center>
#' pagetitle: RMarkdown document from:&nbsp;Eckert&nbsp;et&nbsp;al.&nbsp;(2022)
#' subtitle: <center>doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.3389/fevo.2022.856453">10.3389/fevo.2022.856453</a></center>
#' author: <center>Eckert, S., Herden, J., Stift, M., Durka, W., van Kleunen, M., & Joshi, J.</center>
#' date: <center>`r Sys.Date()`</center>
#' abstract: <p align="justify">This RMarkdown script belongs
#'   to a series of scripts generated by Silvia Eckert as part of
#'   the statistical analysis for the above-mentioned manuscript.
#'   The data underlying the applied R code can be found in the ZENODO
#'   repository and contains genetic (AFLP) and epigenetic (MSAP) markers
#'   from offspring of 25 _Solidago canadensis_ populations sampled along a
#'   latitudinal gradient in Central Europe. This particular RMarkdown script
#'   applies principal coordinates analysis on AFLP and MSAP datasets. <b>Please cite this
#'   script as follows:</b></p><br><p>Eckert, S., Herden, J.,
#'   Stift, M., Durka, W., van Kleunen, M., & Joshi, J. (2022). Data From&colon;
#'   Traces of Genetic but Not Epigenetic Adaptation in the Invasive
#'   Goldenrod _Solidago canadensis_ Despite the Absence of Population
#'   Structure. _Zenodo_. doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.5281/zenodo.6388135">10.5281/zenodo.6388135</a></center></p>
#' geometry: margin=2cm
#' output:
#'   html_document:
#'      code_folding: show
#'      keep_md: FALSE
#'      theme: flatly
#'      highlight: textmate
#'      df_print: paged
#'      toc: true
#'      toc_float: true
#' ---
#' 

#'
#'```{r setup, include = FALSE}
#'knitr::opts_chunk$set(eval=FALSE, cache=FALSE, warning=FALSE)
#'```

#' # Packages
#' <a href="#top">Back to top</a>
#+ project_packages, results='hide', message=FALSE, warning=FALSE
########### packages ...................... ####
# install.packages("name_of_package") # install necessary packages
# install knitr to save this script as html output using RStudio with Ctrl+Shift+K (Windows & Linux) or Command+Shift+K (macOS)
# install.packages("knitr") 
# getwd() # get current working directory
# setwd() # set working directory
# create folder for datasets to be stored to get this RMarkdown script running
dir.create("./data",
           showWarnings=F)
# add necessary libraries
library(RColorBrewer)
library(tibble)
library(adegenet)
library(poppr)
library(ggplot2)
library(cowplot) 
library(ggthemes)
library(scales)
library(ggpubr)
library(vegan)
# remotes::install_github("cmartin/ggConvexHull")
library(ggConvexHull)

#' # Load data
#' <a href="#top">Back to top</a>
#+ project_load.data
########### Load data ...................... ####
#' ## AFLP
#+ project_load.AFLP
######## AFLP ####
# load AFLP/MSAP data
source("RMarkdown_Eckert_et_al_2022_loadMolecularData.R")
# transform to genind object
# CON/C = control plants; ZEB/C = zebularine-treated plants
# presence/absence data (@type: PA)
AFLP.genind <- df2genind(AFLP[,-c(1:8)],
                         sep=",",
                         pop=AFLP$populationID,
                         ind=AFLP$uniqueID,
                         strata=AFLP[,c(1:8)],
                         ploidy=2,
                         type=c("PA")); AFLP.genind
# subset to control plants
# presence/absence data (@type: PA)
AFLP_C <- AFLP[AFLP$treatment=='CON',]
AFLP_C.genind <- df2genind(AFLP_C[,-c(1:8)],
                           sep=",",
                           pop=AFLP_C$populationID,
                           ind.names=AFLP_C$uniqueID,
                           strata=AFLP_C[,c(1:8)],
                           ploidy=2,
                           type=c("PA")); AFLP_C.genind
# write marker names to data folder for later use
write.table(colnames(AFLP_C.genind$tab),
            row.names=F,
            file="./data/Data_AFLP_genind_marker.txt")

#' ## MSAP-n
#' <a href="#top">Back to top</a>
#+ project_load.MSAPn
######## MSAP-n ####
# transform to genind object
MSAPn.genind <- df2genind(MSAPn[,-c(1:8)],
                          sep=",",
                          pop=MSAPn$populationID,
                          ind=MSAPn$uniqueID,
                          strata=MSAPn[,c(1:8)],
                          ploidy=2,
                          type=c("PA")); MSAPn.genind
# subset to control plants
# presence/absence data (@type: PA)
MSAPn_C <- MSAPn[MSAPn$treatment=='CON',]
MSAPn_C.genind <- df2genind(MSAPn_C[,-c(1:8)],
                            sep=",",
                            pop=MSAPn_C$populationID,
                            ind=MSAPn_C$uniqueID,
                            strata=MSAPn_C[,c(1:8)],
                            ploidy=2,
                            type=c("PA")); MSAPn_C.genind
# write marker names to data folder for later use
write.table(colnames(MSAPn_C.genind$tab),
            row.names=F,
            file="./data/Data_MSAPn_genind_marker.txt")

#' ## MSAP-m
#' <a href="#top">Back to top</a>
#+ project_load.MSAPm
######## MSAP-m ####
# transform to genind object
MSAPm.genind <- df2genind(MSAPm[,-c(1:8)],
                          sep=",",
                          pop=MSAPm$populationID,
                          ind=MSAPm$uniqueID,
                          strata=MSAPm[,c(1:8)],
                          ploidy=2,
                          type=c("PA")); MSAPm.genind
# subset to control plants
# presence/absence data (@type: PA)
MSAPm_C <- MSAPm[MSAPm$treatment=='CON',]
MSAPm_C.genind <- df2genind(MSAPm_C[,-c(1:8)],
                            sep=",",
                            pop=MSAPm_C$populationID,
                            ind=MSAPm_C$uniqueID,
                            strata=MSAPm_C[,c(1:8)],
                            ploidy=2,
                            type=c("PA")); MSAPm_C.genind
# write marker names to data folder
write.table(colnames(MSAPm_C.genind$tab),
            row.names=F,
            file="./data/Data_MSAPm_genind_marker.txt")

#' # AMOVA
#' <a href="#top">Back to top</a>
#+ project_amova
######## AMOVA .......................... ####
#' ## AFLP
#+ project_amova.AFLP
######## AFLP ####
# Analysis of molecular variance (AMOVA) for genetic data (AFLP)
# convert from genind to geneclone object to work with poppr.amova() function
AFLP_C.geneclone <- as.genclone(AFLP_C.genind,
                                strata=populationID)
table(strata(AFLP_C.geneclone,~populationID))
# AMOVA based on treatment and population within treatment
set.seed(123)
AFLP_C.amova <- poppr.amova(AFLP_C.geneclone,
                            hier=~populationID,
                            method='ade4',
                            nperm=9999); AFLP_C.amova
# Test for significance
set.seed(123)
AFLP_C.amovastats <- randtest(AFLP_C.amova,
                              nrepet=9999)
AFLP_C.amovastats; plot(AFLP_C.amovastats)

#' ## MSAP-n
#' <a href="#top">Back to top</a>
#+ project_amova.MSAPu
########## MSAP-n ####
# AMOVA for epigenetic data (MSAPn)
# convert from genind to geneclone object
MSAPn_C.geneclone <- as.genclone(MSAPn_C.genind,
                                  strata=populationID)
table(strata(MSAPn_C.geneclone,~populationID))
# AMOVA based on treatment and population within treatment
set.seed(123)
MSAPn_C.amova <- poppr.amova(MSAPn_C.geneclone,
                              hier=~populationID,
                              nperm=9999); MSAPn_C.amova
# Test for significance
set.seed(123)
MSAPn_C.amovastats <- randtest(MSAPn_C.amova,
                                nrepet=9999)
MSAPn_C.amovastats; plot(MSAPn_C.amovastats)

#' ## MSAP-m
#' <a href="#top">Back to top</a>
#+ project_amova.MSAPm
########## MSAP-m ####
# AMOVA for epigenetic data (MSAPm)
# convert from genind to geneclone object
MSAPm_C.geneclone <- as.genclone(MSAPm_C.genind,
                                  strata=populationID)
table(strata(MSAPm_C.geneclone,~populationID))
# AMOVA based on treatment and population within treatment
set.seed(123)
MSAPm_C.amova <- poppr.amova(MSAPm_C.geneclone,
                              hier=~populationID,
                              nperm=9999); MSAPm_C.amova
# Test for significance
set.seed(123)
MSAPm_C.amovastats <- randtest(MSAPm_C.amova,
                               nrepet=9999)
MSAPm_C.amovastats; plot(MSAPm_C.amovastats)

#' # Betadisper
#' <a href="#top">Back to top</a>
#+ project_betadisper
######## Betadisper ................... ####
# principal coordinates analysis with k=10 axes
#' ## AFLP
#+ project_pcoa.AFLP
######## AFLP ####
# generate distance matrix from the simple matching coefficient
# and calculate betadisper analysis
AFLP.bd <- betadisper(dist.binary(AFLP.genind$tab,
                                  method=5),
                      AFLP.genind$strata$treatment)
# significance via permutation test
set.seed(123)
AFLP.bd_res <- permutest(AFLP.bd,
                         permutations=9999)
AFLP.bd_res; plot(AFLP.bd)

#' ## MSAP-n
#' <a href="#top">Back to top</a>
#+ project_pcoa.MSAPu
######## MSAP-n ####
# generate distance matrix from the simple matching coefficient
# and calculate betadisper analysis
MSAPn.bd <- betadisper(dist.binary(MSAPn.genind$tab,
                                    method=5),
                        MSAPn.genind$strata$treatment)
# significance via permutation test
set.seed(123)
MSAPn.bd_res <- permutest(MSAPn.bd,
                           permutations=9999)
MSAPn.bd_res; plot(MSAPn.bd)

#' ## MSAP-m
#' <a href="#top">Back to top</a>
#+ project_pcoa.MSAPm
######## MSAP-m ####
# generate distance matrix from the simple matching coefficient
# and calculate betadisper analysis
MSAPm.bd <- betadisper(dist.binary(MSAPm.genind$tab,
                                    method=5),
                        MSAPm.genind$strata$treatment)
# significance via permutation test
set.seed(123)
MSAPm.bd_res <- permutest(MSAPm.bd,
                           permutations=9999)
MSAPm.bd_res; plot(MSAPm.bd)

#' # Figures 2A-C
#' <a href="#top">Back to top</a>
#+ project_pcoa.figures2ABC
########### Figures 2ABC ............... ####
#' ## AFLP
#+ project_pcoa.figures.AFLP
######## AFLP ####
# calculate percentage of explained variance
# format(df.pco$eig[1]/sum(df.pco$eig)*100,digits=3)
# PCoA 1: 
format(AFLP.bd$eig[1]/sum(AFLP.bd$eig)*100,digits=3)
# PCoA 2:
format(AFLP.bd$eig[2]/sum(AFLP.bd$eig)*100,digits=3)
# update data frame
AFLP.pcodata <- data.frame(treatment=strata(AFLP.genind)$treatment,
                           pop=strata(AFLP.genind)$lat,
                           ind=row.names(strata(AFLP.genind)),
                           AFLP.bd$vectors[,1:2]); tibble(AFLP.pcodata)
colnames(AFLP.pcodata) <- c("treatment","pop","ID","PCoA1","PCoA2")
# centroids
AFLP.pco_centroids <- data.frame(AFLP.bd$centroids[,1:2],
                                 treatment=c("C","Z")); AFLP.pco_centroids
# add values to data
AFLP.pcodata$oPCoA1 <- ifelse(AFLP.pcodata$treatment == "CON",
                              AFLP.pco_centroids$PCoA1[1],
                              AFLP.pco_centroids$PCoA1[2])
AFLP.pcodata$oPCoA2 <- ifelse(AFLP.pcodata$treatment == "ZEB",
                              AFLP.pco_centroids$PCoA2[1],
                              AFLP.pco_centroids$PCoA2[2])
tibble(AFLP.pcodata)
# and plot
AFLP.pco_plot <- ggplot(AFLP.pcodata,
                        aes(x=PCoA1,
                            y=PCoA2,
                            colour=treatment)) +
  geom_point(alpha=0.5) +
  geom_segment(aes(xend=oPCoA1,
                   yend=oPCoA2,
                   color=treatment),
               alpha=0.2) +
  coord_fixed(xlim=c(-0.3,0.3),
              ylim=c(-0.3,0.3),
              ratio=1) +
  geom_convexhull(fill="transparent") +
  annotate(geom='text',
           hjust=0,
           x=-0.3,
           y=c(-0.24,-0.29),
           parse=T,
           label=c(paste("'betadisper:'"),
                   paste("~italic(F['1, 2']) == ",
                         round(AFLP.bd_res$tab[1,4],2),
                         "~';'~italic(p) == ",
                         round(AFLP.bd_res$tab[1,6],3),
                         "~';'~italic(n)[permutations] == ",
                         AFLP.bd_res$tab[1,5]))) +
  labs(title="AFLP",
       x=paste("Dim1 ",
                 paste0("(",format(AFLP.bd$eig[1]/
                                     sum(AFLP.bd$eig)*100,
                                   digits=3),"%)")),
       y=paste("Dim2 ",
                 paste0("(",format(AFLP.bd$eig[2]/
                                     sum(AFLP.bd$eig)*100,
                                   digits=3),"%)"))) +
  geom_point(x=AFLP.pco_centroids$PCoA1[1],
             y=AFLP.pco_centroids$PCoA2[1],
             size=5,
             fill="#e69f0050",
             color="#e69f00",
             alpha=0.2,
             shape=21) +
  geom_point(x=AFLP.pco_centroids$PCoA1[2],
             y=AFLP.pco_centroids$PCoA2[2],
             size=5,
             fill="gray20",
             color="black",
             alpha=0.2,
             shape=21) +
  theme_cowplot() +
  geom_vline(xintercept=0,
             linetype="dashed",
             color="gray40",
             alpha=0.3)+
  geom_hline(yintercept=0,
             linetype="dashed",
             color="gray40",
             alpha=0.3)+
  theme(panel.border=element_rect(colour="gray70",
                                    fill=NA,
                                    size=1.2),
        legend.position=c(.12,.93),
        legend.title=element_blank(),
        legend.key=element_rect(color="transparent"),
        legend.key.size=unit(0,"line")) +
  guides(colour=guide_legend(override.aes=list(size=5,
                                                   linetype=0))) +
  scale_color_colorblind(labels=c("Control",
                                  "Zebularine")); AFLP.pco_plot

#' ## MSAP-n
#' <a href="#top">Back to top</a>
#+ project_pcoa.figures.MSAPu
######## MSAP-n ####
# calculate percentage of explained variance
# format(df.pco$eig[1]/sum(df.pco$eig)*100,digits=3)
# PCoA 1: 
format(MSAPn.bd$eig[1]/sum(MSAPn.bd$eig)*100,digits=3)
# PCoA 2:
format(MSAPn.bd$eig[2]/sum(MSAPn.bd$eig)*100,digits=3)
# update data frame
MSAPn.pcodata <- data.frame(treatment=strata(MSAPn.genind)$treatment,
                             pop=strata(MSAPn.genind)$lat,
                             ind=row.names(strata(MSAPn.genind)),
                             MSAPn.bd$vectors[,1:2]); tibble(MSAPn.pcodata)
colnames(MSAPn.pcodata) <- c("treatment","pop","ID","PCoA1","PCoA2")
# centroids
MSAPn.pco_centroids <- data.frame(MSAPn.bd$centroids[,1:2],
                                   treatment=c("C","Z")); MSAPn.pco_centroids
# add values to data
MSAPn.pcodata$oPCoA1 <- ifelse(MSAPn.pcodata$treatment == "CON",
                                MSAPn.pco_centroids$PCoA1[1],
                                MSAPn.pco_centroids$PCoA1[2])
MSAPn.pcodata$oPCoA2 <- ifelse(MSAPn.pcodata$treatment == "ZEB",
                                MSAPn.pco_centroids$PCoA2[1],
                                MSAPn.pco_centroids$PCoA2[2])
tibble(MSAPn.pcodata)
# and plot
MSAPn.pco_plot <- ggplot(MSAPn.pcodata,
                          aes(x=PCoA1,
                              y=PCoA2,
                              colour=treatment)) +
  geom_point(alpha=0.5) +
  geom_segment(aes(xend=oPCoA1,
                   yend=oPCoA2,
                   color=treatment),
               alpha=0.2) +
  coord_fixed(xlim=c(-0.3,0.3),
              ylim=c(-0.3,0.3),
              ratio=1) +
  geom_convexhull(fill="transparent") +
  annotate(geom='text',
           hjust=0,
           x=-0.3,
           y=c(-0.24,-0.29),
           parse=T,
           label=c(paste("'betadisper:'"),
                   paste("~italic(F['1, 2']) == ",
                         round(MSAPn.bd_res$tab[1,4],2),
                         "~';'~italic(p) == ",
                         round(MSAPn.bd_res$tab[1,6],3),
                         "~';'~italic(n)[permutations] == ",
                         MSAPn.bd_res$tab[1,5]))) +
  labs(title="MSAP-n",
       x=paste("Dim1 ",
                 paste0("(",format(MSAPn.bd$eig[1]/
                                     sum(MSAPn.bd$eig)*100,
                                   digits=3),"%)")),
       y=paste("Dim2 ",
                 paste0("(",format(MSAPn.bd$eig[2]/
                                     sum(MSAPn.bd$eig)*100,
                                   digits=3),"%)"))) +
  geom_point(x=MSAPn.pco_centroids$PCoA1[1],
             y=MSAPn.pco_centroids$PCoA2[1],
             size=5,
             fill="#e69f0050",
             color="#e69f00",
             alpha=0.2,
             shape=21) +
  geom_point(x=MSAPn.pco_centroids$PCoA1[2],
             y=MSAPn.pco_centroids$PCoA2[2],
             size=5,
             fill="gray20",
             color="black",
             alpha=0.2,
             shape=21) +
  theme_cowplot() +
  geom_vline(xintercept=0,
             linetype="dashed",
             color="gray40",
             alpha=0.3)+
  geom_hline(yintercept=0,
             linetype="dashed",
             color="gray40",
             alpha=0.3)+
  theme(panel.border=element_rect(colour="gray70",
                                    fill=NA,
                                    size=1.2),
        legend.position="none") +
  guides(colour=guide_legend(override.aes=list(size=5,
                                                   linetype=0))) +
  scale_color_colorblind(labels=c("Control",
                                  "Zebularine")); MSAPn.pco_plot

#' ## MSAP-m
#' <a href="#top">Back to top</a>
#+ project_pcoa.figures.MSAPm
######## MSAP-m ####
# calculate percentage of explained variance
# format(df.pco$eig[1]/sum(df.pco$eig)*100,digits=3)
# PCoA 1: 
format(MSAPm.bd$eig[1]/sum(MSAPm.bd$eig)*100,digits=3)
# PCoA 2:
format(MSAPm.bd$eig[2]/sum(MSAPm.bd$eig)*100,digits=3)
# update data frame
MSAPm.pcodata <- data.frame(treatment=strata(MSAPm.genind)$treatment,
                             pop=strata(MSAPm.genind)$lat,
                             ind=row.names(strata(MSAPm.genind)),
                             MSAPm.bd$vectors[,1:2]); tibble(MSAPm.pcodata)
colnames(MSAPm.pcodata) <- c("treatment","pop","ID","PCoA1","PCoA2")
# centroids
MSAPm.pco_centroids <- data.frame(MSAPm.bd$centroids[,1:2],
                                   treatment=c("C","Z")); MSAPm.pco_centroids
# add values to data
MSAPm.pcodata$oPCoA1 <- ifelse(MSAPm.pcodata$treatment == "CON",
                                MSAPm.pco_centroids$PCoA1[1],
                                MSAPm.pco_centroids$PCoA1[2])
MSAPm.pcodata$oPCoA2 <- ifelse(MSAPm.pcodata$treatment == "ZEB",
                                MSAPm.pco_centroids$PCoA2[1],
                                MSAPm.pco_centroids$PCoA2[2])
tibble(MSAPm.pcodata)
# and plot
MSAPm.pco_plot <- ggplot(MSAPm.pcodata,
                          aes(x=PCoA1,
                              y=PCoA2,
                              colour=treatment)) +
  geom_point(alpha=0.5) +
  geom_segment(aes(xend=oPCoA1,
                   yend=oPCoA2,
                   color=treatment),
               alpha=0.2) +
  coord_fixed(xlim=c(-0.3,0.3),
              ylim=c(-0.3,0.3),
              ratio=1) +
  geom_convexhull(fill="transparent") +
  annotate(geom='text',
           hjust=0,
           x=-0.3,
           y=c(-0.24,-0.29),
           parse=T,
           label=c(paste("'betadisper:'"),
                   paste("~italic(F['1, 2']) == ",
                         round(MSAPm.bd_res$tab[1,4],2),
                         "~';'~italic(p) == ",
                         round(MSAPm.bd_res$tab[1,6],3),
                         "~';'~italic(n)[permutations] == ",
                         MSAPm.bd_res$tab[1,5]))) +
  labs(title="MSAP-m",
       x=paste("Dim1 ",
                 paste0("(",format(MSAPm.bd$eig[1]/
                                     sum(MSAPm.bd$eig)*100,
                                   digits=3),"%)")),
       y=paste("Dim2 ",
                 paste0("(",format(MSAPm.bd$eig[2]/
                                     sum(MSAPm.bd$eig)*100,
                                   digits=3),"%)"))) +
  geom_point(x=MSAPm.pco_centroids$PCoA1[1],
             y=MSAPm.pco_centroids$PCoA2[1],
             size=5,
             fill="#e69f0050",
             color="#e69f00",
             alpha=0.2,
             shape=21) +
  geom_point(x=MSAPm.pco_centroids$PCoA1[2],
             y=MSAPm.pco_centroids$PCoA2[2],
             size=5,
             fill="gray20",
             color="black",
             alpha=0.2,
             shape=21) +
  theme_cowplot() +
  geom_vline(xintercept=0,
             linetype="dashed",
             color="gray40",
             alpha=0.3)+
  geom_hline(yintercept=0,
             linetype="dashed",
             color="gray40",
             alpha=0.3)+
  theme(panel.border=element_rect(colour="gray70",
                                    fill=NA,
                                    size=1.2),
        legend.position="none") +
  guides(colour=guide_legend(override.aes=list(size=5,
                                                   linetype=0))) +
  scale_color_colorblind(labels=c("Control",
                                  "Zebularine")); MSAPm.pco_plot

#' ## Figure 2
#' <a href="#top">Back to top</a>
#+ project_figure2
######## Figure 2 ####
# combine plots
PCOcombi <- plot_grid(AFLP.pco_plot,
                      MSAPm.pco_plot,
                      MSAPn.pco_plot,
                      nrow=1,
                      vjust=0,
                      rel_widths=c(1,1,1),
                      label_size=26,
                      labels=c("A","B","C")) +
  theme(plot.margin=unit(c(2,1,1,1),"cm"))
# save as png
ggsave(PCOcombi,
       file="./data/Figure2_Eckert_et_al_2022_PCoA.png",
       dpi=300,
       width=16,
       height=6)
# save as tiff
ggsave(PCOcombi,
       file="./data/Figure2_Eckert_et_al_2022_PCoA.TIFF",
       dpi=300,
       width=16,
       height=6,
       device=grDevices::tiff)

#' # Session info
#' <a href="#top">Back to top</a>
#+ Session.info
sessionInfo()
#' <a href="#top">Back to top</a>
######## Session info .................. ####