#' ---
#' title: <center><b>Markdown document from&colon;</b><br>Traces of Genetic but Not Epigenetic Adaptation in the Invasive Goldenrod _Solidago canadensis_ Despite the Absence of Population Structure</center>
#' pagetitle: RMarkdown document from:&nbsp;Eckert&nbsp;et&nbsp;al.&nbsp;(2022)
#' subtitle: <center>doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.3389/fevo.2022.856453">10.3389/fevo.2022.856453</a></center>
#' author: <center>Eckert, S., Herden, J., Stift, M., Durka, W., van Kleunen, M., & Joshi, J.</center>
#' date: <center>`r Sys.Date()`</center>
#' abstract: <p align="justify">This RMarkdown script belongs
#'   to a series of scripts generated by Silvia Eckert as part of
#'   the statistical analysis for the above-mentioned manuscript.
#'   The data underlying the applied R code can be found in the ZENODO
#'   repository and contains genetic (AFLP) and epigenetic (MSAP) markers
#'   from offspring of 25 _Solidago canadensis_ populations sampled along a
#'   latitudinal gradient in Central Europe. This particular RMarkdown script
#'   is part 05/06 and applies the LEA genome-scan approach on the MSAP-m 
#'   dataset. <b>Please cite this
#'   script as follows:</b></p><br><p>Eckert, S., Herden, J.,
#'   Stift, M., Durka, W., van Kleunen, M., & Joshi, J. (2022). Data From&colon;
#'   Traces of Genetic but Not Epigenetic Adaptation in the Invasive
#'   Goldenrod _Solidago canadensis_ Despite the Absence of Population
#'   Structure. _Zenodo_. doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.5281/zenodo.6388135">10.5281/zenodo.6388135</a></center></p>
#' geometry: margin=2cm
#' output:
#'   html_document:
#'      code_folding: show
#'      keep_md: FALSE
#'      theme: flatly
#'      highlight: textmate
#'      df_print: paged
#'      toc: true
#'      toc_float: true
#' ---
#' 

#'
#'```{r setup, include = FALSE}
#'knitr::opts_chunk$set(eval=FALSE, cache=FALSE, warning=FALSE)
#'```

#' # Packages
#' <a href="#top">Back to top</a>
#+ project_packages, results='hide', message=FALSE, warning=FALSE
########### packages ...................... ####
# install.packages("name_of_package") # install necessary packages
# install knitr to save this script as html output using RStudio with Ctrl+Shift+K (Windows & Linux) or Command+Shift+K (macOS)
# install.packages("knitr") 
# getwd() # get current working directory
# setwd() # set working directory
# create folder for datasets to be stored to get this RMarkdown script running
dir.create("./data",
           showWarnings=F)

#' # Load data
#' <a href="#top">Back to top</a>
#+ project_load.data
########### load data ....................... ####
source("RMarkdown_Eckert_et_al_2022_LEA_01.R")

#' # MSAP-m
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPm
########### MSAP-m ........................ ####
#' ## LFMM
#+ project_LEA.MSAPm_lfmm
######## outlier scan ####
# lfmm with latitude
# parameters following Yadav et al (2019)
# doi:  https://doi.org/10.1111/mec.15146
MSAPm_C.envproject = NULL
MSAPm_C.envproject = lfmm(input.file="RawData_LEA/MSAPm_C.lfmm",
                           environment.file="RawData_LEA/MSAPm_C.env",
                           seed=123,
                           all=F, # fits all variables separately
                           K=1,
                           repetitions=10,
                           CPU=4,
                           iterations=50000,
                           burnin=5000,
                           project="new")
# re-load project
# MSAPm_C.envproject = load.lfmmProject("RawData_LEA/MSAPm_C_MSAPm_C.lfmmProject")

#' ## PC1
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPm_PC1
########### PC1 ................................ ####
#' ### q-values
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPm_PC1_qvalues
######## qvalues ####
# adjusted p-values
MSAPm_C.pv_PC1 = lfmm.pvalues(MSAPm_C.envproject,
                               d=1,
                               K=1); MSAPm_C.pv_PC1
hist(MSAPm_C.pv_PC1$pvalues,
     col="gainsboro")
# compute q-values
MSAPm_C.qv_PC1 <- qvalue(MSAPm_C.pv_PC1$pvalues,
                          fdr.level=0.05,
                          lambda=MSAPm_C.pv_PC1$GIF); MSAPm_C.qv_PC1$qvalues
# results of LFMM testing
MSAPm_C.res_PC1 <- tibble(data.frame(ID=names(data.frame(MSAPm_C.genind@tab)),
                                      dye=names(data.frame(MSAPm_C.genind@tab)),
                                      LFMMpVal=MSAPm_C.pv_PC1$pvalues,
                                      latitudeFDR=MSAPm_C.qv_PC1$qvalues,
                                      log10qVal=-log10(MSAPm_C.qv_PC1$qvalues)))
# replace FAM_AAC_CCT_* with FAM
MSAPm_C.res_PC1$dye <- stringr::str_replace(MSAPm_C.res_PC1$dye,
                                             "MFAM_AAC_CCT_[0-9|_]+",
                                             "FAM")
# replace VIC_ACG_CAT_* with VIC
MSAPm_C.res_PC1$dye <- stringr::str_replace(MSAPm_C.res_PC1$dye,
                                             "MVIC_ACG_CAT_[0-9|_]+",
                                             "VIC")
# replace NED_ACC_CTG_* with NED
MSAPm_C.res_PC1$dye <- stringr::str_replace(MSAPm_C.res_PC1$dye,
                                             "MNED_ACC_CTG_[0-9|_]+",
                                             "NED")
# replace PET_AGG_CGA_* with PET
MSAPm_C.res_PC1$dye <- stringr::str_replace(MSAPm_C.res_PC1$dye,
                                             "MPET_AGG_CGA_[0-9|_]+",
                                             "PET")
MSAPm_C.res_PC1$dye <- ordered(MSAPm_C.res_PC1$dye,
                                levels=c("FAM","VIC","NED","PET"))
MSAPm_C.res_PC1$dye # check
# replace FAM_AAC_CCT_* with FAM
MSAPm_C.res_PC1$marker <- stringr::str_replace(MSAPm_C.res_PC1$ID,
                                                "MFAM_AAC_CCT_",
                                                "loc")
# replace VIC_ACG_CAT_* with VIC
MSAPm_C.res_PC1$marker <- stringr::str_replace(MSAPm_C.res_PC1$marker,
                                                "MVIC_ACG_CAT_",
                                                "loc")
# replace NED_ACC_CTG_* with NED
MSAPm_C.res_PC1$marker <- stringr::str_replace(MSAPm_C.res_PC1$marker,
                                                "MNED_ACC_CTG_",
                                                "loc")
# replace PET_AGG_CGA_* with PET
MSAPm_C.res_PC1$marker <- stringr::str_replace(MSAPm_C.res_PC1$marker,
                                                "MPET_AGG_CGA_",
                                                "loc")
MSAPm_C.res_PC1$marker # check
# add basepair value
MSAPm_C.res_PC1$basepair <- MSAPm_C.res_PC1$marker
# replace loc
MSAPm_C.res_PC1$basepair <- stringr::str_replace(MSAPm_C.res_PC1$basepair,
                                                  "loc","")
MSAPm_C.res_PC1$basepair <- as.numeric(MSAPm_C.res_PC1$basepair)
MSAPm_C.res_PC1$basepair # check
MSAPm_C.res_PC1$latentFactor <- "PC1"
str(MSAPm_C.res_PC1); MSAPm_C.res_PC1

#' ## Manhattan plot
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPm_PC1_manhattan
######## Manhattan plot ####
# prepare data
MSAPm_C.resmelt_PC1 <- tibble(reshape2::melt(MSAPm_C.res_PC1[,c(1:2,5:7)],
                                              id.vars=c("ID","marker","dye","basepair"),
                                              measure.vars="log10qVal",
                                              variable.name="FDR",
                                              value.name="log10qVal")); MSAPm_C.resmelt_PC1
# signf loc
MSAPm_C.lfmm.signf.loc_PC1 <- MSAPm_C.resmelt_PC1[MSAPm_C.resmelt_PC1$log10qVal > -log10(0.05),]
MSAPm_C.lfmm.signf.loc_PC1
# plot
# FAM = blue; VIC = green; NED = black (yellow); PET = red
set.seed(123)
MSAPm_C.lfmm.manhattanplot_PC1 <- ggplot(MSAPm_C.resmelt_PC1,
                                          aes(x=basepair,
                                              y=log10qVal)) +
  geom_point(alpha=0.5,
             size=2) +
  scale_y_continuous(expand=c(0,0),
                     limits=c(0,7.5)) +
  labs(title="MSAP-m (Control)",
       subtitle="PC1 (explained variation: 40.3%)") +
  theme_cowplot() +
  theme(panel.border=element_rect(color="black"),
    legend.position="none") +
  labs(x="",
       y=bquote(-log[10]~"("~italic("q-value")~")")) +
  geom_hline(yintercept=-log10(0.05),
             linetype="longdash",
             color="gray60") +
  scale_color_manual(values=c("green","red","black","blue")) +
  geom_text_repel(data=MSAPm_C.lfmm.signf.loc_PC1,
                  aes(x=basepair,
                      y=log10qVal,
                      label=marker,
                      color=dye),
                  size=3,
                  seed=123); MSAPm_C.lfmm.manhattanplot_PC1

#' ## PC2
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPm_PC2
########### PC2 ................................ ####
#' ### q-values
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPm_PC2_qvalues
######## qvalues ####
# adjusted p-values
MSAPm_C.pv_PC2 = lfmm.pvalues(MSAPm_C.envproject,
                               d=2,
                               K=1); MSAPm_C.pv_PC2
hist(MSAPm_C.pv_PC2$pvalues,
     col="gainsboro")
# compute q-values
MSAPm_C.qv_PC2 <- qvalue(MSAPm_C.pv_PC2$pvalues,
                          fdr.level=0.05,
                          lambda=MSAPm_C.pv_PC2$GIF); MSAPm_C.qv_PC2$qvalues
# results of LFMM testing
MSAPm_C.res_PC2 <- tibble(data.frame(ID=names(data.frame(MSAPm_C.genind@tab)),
                                      dye=names(data.frame(MSAPm_C.genind@tab)),
                                      LFMMpVal=MSAPm_C.pv_PC2$pvalues,
                                      latitudeFDR=MSAPm_C.qv_PC2$qvalues,
                                      log10qVal=-log10(MSAPm_C.qv_PC2$qvalues)))
# replace FAM_AAC_CCT_* with FAM
MSAPm_C.res_PC2$dye <- stringr::str_replace(MSAPm_C.res_PC2$dye,
                                             "MFAM_AAC_CCT_[0-9|_]+",
                                             "FAM")
# replace VIC_ACG_CAT_* with VIC
MSAPm_C.res_PC2$dye <- stringr::str_replace(MSAPm_C.res_PC2$dye,
                                             "MVIC_ACG_CAT_[0-9|_]+",
                                             "VIC")
# replace NED_ACC_CTG_* with NED
MSAPm_C.res_PC2$dye <- stringr::str_replace(MSAPm_C.res_PC2$dye,
                                             "MNED_ACC_CTG_[0-9|_]+",
                                             "NED")
# replace PET_AGG_CGA_* with PET
MSAPm_C.res_PC2$dye <- stringr::str_replace(MSAPm_C.res_PC2$dye,
                                             "MPET_AGG_CGA_[0-9|_]+",
                                             "PET")
MSAPm_C.res_PC2$dye <- ordered(MSAPm_C.res_PC2$dye,
                                levels=c("FAM","VIC","NED","PET"))
MSAPm_C.res_PC2$dye # check
# replace FAM_AAC_CCT_* with FAM
MSAPm_C.res_PC2$marker <- stringr::str_replace(MSAPm_C.res_PC2$ID,
                                                "MFAM_AAC_CCT_",
                                                "loc")
# replace VIC_ACG_CAT_* with VIC
MSAPm_C.res_PC2$marker <- stringr::str_replace(MSAPm_C.res_PC2$marker,
                                                "MVIC_ACG_CAT_",
                                                "loc")
# replace NED_ACC_CTG_* with NED
MSAPm_C.res_PC2$marker <- stringr::str_replace(MSAPm_C.res_PC2$marker,
                                                "MNED_ACC_CTG_",
                                                "loc")
# replace PET_AGG_CGA_* with PET
MSAPm_C.res_PC2$marker <- stringr::str_replace(MSAPm_C.res_PC2$marker,
                                                "MPET_AGG_CGA_",
                                                "loc")
MSAPm_C.res_PC2$marker # check
# add basepair value
MSAPm_C.res_PC2$basepair <- MSAPm_C.res_PC2$marker
# replace loc
MSAPm_C.res_PC2$basepair <- stringr::str_replace(MSAPm_C.res_PC2$basepair,
                                                  "loc","")
MSAPm_C.res_PC2$basepair <- as.numeric(MSAPm_C.res_PC2$basepair)
MSAPm_C.res_PC2$basepair # check
MSAPm_C.res_PC2$latentFactor <- "PC2"
str(MSAPm_C.res_PC2); MSAPm_C.res_PC2

#' ## Manhattan plot
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPm_PC2_manhattan
######## Manhattan plot ####
# prepare data
MSAPm_C.resmelt_PC2 <- tibble(reshape2::melt(MSAPm_C.res_PC2[,c(1:2,5:7)],
                                              id.vars=c("ID","marker","dye","basepair"),
                                              measure.vars="log10qVal",
                                              variable.name="FDR",
                                              value.name="log10qVal")); MSAPm_C.resmelt_PC2
# signficant loci
MSAPm_C.lfmm.signf.loc_PC2 <- MSAPm_C.resmelt_PC2[MSAPm_C.resmelt_PC2$log10qVal > -log10(0.05),]
MSAPm_C.lfmm.signf.loc_PC2
# plot
set.seed(123)
MSAPm_C.lfmm.manhattanplot_PC2 <- ggplot(MSAPm_C.resmelt_PC2,
                                          aes(x=basepair,
                                              y=log10qVal)) +
  geom_point(alpha=0.5,
             size=2) +
  scale_y_continuous(expand=c(0,0),
                     limits=c(0,7.5)) +
  labs(title="",
       subtitle="PC2 (explained variation: 32.7%)") +
  theme_cowplot() +
  theme(panel.border=element_rect(color="black"),
        legend.position="none") +
  labs(x="",
       y="") +
  geom_hline(yintercept=-log10(0.05),
             linetype="longdash",
             color="gray60") +
  scale_color_manual(values=c("blue","green","red","black")) +
  geom_text_repel(data=MSAPm_C.lfmm.signf.loc_PC2,
                  aes(x=basepair,
                      y=log10qVal,
                      label=marker,
                      color=dye),
                  size=3,
                  seed=123); MSAPm_C.lfmm.manhattanplot_PC2

#' ## PC3
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPm_PC3
########### PC3 ................................ ####
#' ### q-values
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPm_PC3_qvalues
######## qvalues ####
# adjusted p-values
MSAPm_C.pv_PC3 = lfmm.pvalues(MSAPm_C.envproject,
                               d=3,
                               K=1); MSAPm_C.pv_PC3
hist(MSAPm_C.pv_PC3$pvalues,
     col="gainsboro")
# compute q-values
MSAPm_C.qv_PC3 <- qvalue(MSAPm_C.pv_PC3$pvalues,
                          fdr.level=0.05,
                          lambda=MSAPm_C.pv_PC3$GIF); MSAPm_C.qv_PC3$qvalues
# results of LFMM testing
MSAPm_C.res_PC3 <- tibble(data.frame(ID=names(data.frame(MSAPm_C.genind@tab)),
                                      dye=names(data.frame(MSAPm_C.genind@tab)),
                                      LFMMpVal=MSAPm_C.pv_PC3$pvalues,
                                      latitudeFDR=MSAPm_C.qv_PC3$qvalues,
                                      log10qVal=-log10(MSAPm_C.qv_PC3$qvalues)))
# replace FAM_AAC_CCT_* with FAM
MSAPm_C.res_PC3$dye <- stringr::str_replace(MSAPm_C.res_PC3$dye,
                                             "MFAM_AAC_CCT_[0-9|_]+",
                                             "FAM")
# replace VIC_ACG_CAT_* with VIC
MSAPm_C.res_PC3$dye <- stringr::str_replace(MSAPm_C.res_PC3$dye,
                                             "MVIC_ACG_CAT_[0-9|_]+",
                                             "VIC")
# replace NED_ACC_CTG_* with NED
MSAPm_C.res_PC3$dye <- stringr::str_replace(MSAPm_C.res_PC3$dye,
                                             "MNED_ACC_CTG_[0-9|_]+",
                                             "NED")
# replace PET_AGG_CGA_* with PET
MSAPm_C.res_PC3$dye <- stringr::str_replace(MSAPm_C.res_PC3$dye,
                                             "MPET_AGG_CGA_[0-9|_]+",
                                             "PET")
MSAPm_C.res_PC3$dye <- ordered(MSAPm_C.res_PC3$dye,
                                levels=c("FAM","VIC","NED","PET"))
MSAPm_C.res_PC3$dye # check
# replace FAM_AAC_CCT_* with FAM
MSAPm_C.res_PC3$marker <- stringr::str_replace(MSAPm_C.res_PC3$ID,
                                                "MFAM_AAC_CCT_",
                                                "loc")
# replace VIC_ACG_CAT_* with VIC
MSAPm_C.res_PC3$marker <- stringr::str_replace(MSAPm_C.res_PC3$marker,
                                                "MVIC_ACG_CAT_",
                                                "loc")
# replace NED_ACC_CTG_* with NED
MSAPm_C.res_PC3$marker <- stringr::str_replace(MSAPm_C.res_PC3$marker,
                                                "MNED_ACC_CTG_",
                                                "loc")
# replace PET_AGG_CGA_* with PET
MSAPm_C.res_PC3$marker <- stringr::str_replace(MSAPm_C.res_PC3$marker,
                                                "MPET_AGG_CGA_",
                                                "loc")
MSAPm_C.res_PC3$marker # check
# add basepair value
MSAPm_C.res_PC3$basepair <- MSAPm_C.res_PC3$marker
# replace loc
MSAPm_C.res_PC3$basepair <- stringr::str_replace(MSAPm_C.res_PC3$basepair,
                                                  "loc","")
MSAPm_C.res_PC3$basepair <- as.numeric(MSAPm_C.res_PC3$basepair)
MSAPm_C.res_PC3$basepair # check
MSAPm_C.res_PC3$latentFactor <- "PC3"
str(MSAPm_C.res_PC3); MSAPm_C.res_PC3

#' ## Manhattan plot
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPm_PC3_manhattan
######## Manhattan plot ####
# prepare data
MSAPm_C.resmelt_PC3 <- tibble(reshape2::melt(MSAPm_C.res_PC3[,c(1:2,5:7)],
                                              id.vars=c("ID","marker","dye","basepair"),
                                              measure.vars="log10qVal",
                                              variable.name="FDR",
                                              value.name="log10qVal")); MSAPm_C.resmelt_PC3
# signficant loci
MSAPm_C.lfmm.signf.loc_PC3 <- MSAPm_C.resmelt_PC3[MSAPm_C.resmelt_PC3$log10qVal > -log10(0.05),]
MSAPm_C.lfmm.signf.loc_PC3
# plot
set.seed(123)
MSAPm_C.lfmm.manhattanplot_PC3 <- ggplot(MSAPm_C.resmelt_PC3,
                                          aes(x=basepair,
                                              y=log10qVal)) +
  geom_point(alpha=0.5,
             size=2) +
  scale_y_continuous(expand=c(0,0),
                     limits=c(0,7.5)) +
  labs(title="",
       subtitle="PC3 (explained variation: 14.4%)") +
  theme_cowplot() +
  theme(panel.border=element_rect(color="black"),
    legend.position="none") +
  labs(x="",
       y="")+
  geom_hline(yintercept=-log10(0.05),
             linetype="longdash",
             color="gray60") +
  scale_color_manual(values=c("blue","green","red"," black")) +
  geom_text_repel(data=MSAPm_C.lfmm.signf.loc_PC3,
                  aes(x=basepair,
                      y=log10qVal,
                      label=marker,
                      color=dye),
                  size=3,
                  seed=123); MSAPm_C.lfmm.manhattanplot_PC3

#' ## Figure S13D-F
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAP-m.snmf_figureS13D-F
######## Figure S13D-F ####
MSAPm_lfmmCombi <- ggarrange(MSAPm_C.lfmm.manhattanplot_PC1,
                              MSAPm_C.lfmm.manhattanplot_PC2,
                              MSAPm_C.lfmm.manhattanplot_PC3,
                              ncol=3,
                              nrow=1,
                              font.label=list(size=20),
                              labels=c("A","B","C")) +
  theme(plot.margin=unit(c(1,1,1,1),"cm")); MSAPm_lfmmCombi
# save as png
ggsave(MSAPm_lfmmCombi,
       file="./data/FigureS13DEF_Eckert_et_al_2022_LEA_lfmm_MSAPm.png",
       width=12,
       height=5,
       dpi=300)
# save as tiff
ggsave(MSAPm_lfmmCombi,
       file="./data/FigureS13DEF_Eckert_et_al_2022_LEA_lfmm_MSAPm.TIFF",
       dpi=300,
       width=12,
       height=5,
       device=grDevices::tiff)

#' ## Table S5
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAP-m.snmf_tableS5
######## Table S5 ####
# prepare data
MSAPm_C.lfmm.signf.loc_all <- tibble(rbind(MSAPm_C.lfmm.signf.loc_PC1,
                                            MSAPm_C.lfmm.signf.loc_PC2,
                                            MSAPm_C.lfmm.signf.loc_PC3)); MSAPm_C.lfmm.signf.loc_all
# save trimmed AFLP marker data
write.table(MSAPm_C.lfmm.signf.loc_all,
            row.names=F,
            file="./data/Data_MSAPm_LFMM_outliers.txt")

#' # Session info
#' <a href="#top">Back to top</a>
#+ Session.info
######## Session info ###
sessionInfo()
#' <a href="#top">Back to top</a>
######## Session info .................. ####