#' ---
#' title: <center><b>Markdown document from&colon;</b><br>Traces of Genetic but Not Epigenetic Adaptation in the Invasive Goldenrod _Solidago canadensis_ Despite the Absence of Population Structure</center>
#' pagetitle: RMarkdown document from:&nbsp;Eckert&nbsp;et&nbsp;al.&nbsp;(2022)
#' subtitle: <center>doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.3389/fevo.2022.856453">10.3389/fevo.2022.856453</a></center>
#' author: <center>Eckert, S., Herden, J., Stift, M., Durka, W., van Kleunen, M., & Joshi, J.</center>
#' date: <center>`r Sys.Date()`</center>
#' abstract: <p align="justify">This RMarkdown script belongs
#'   to a series of scripts generated by Silvia Eckert as part of
#'   the statistical analysis for the above-mentioned manuscript.
#'   The data underlying the applied R code can be found in the ZENODO
#'   repository and contains genetic (AFLP) and epigenetic (MSAP) markers
#'   from offspring of 25 _Solidago canadensis_ populations sampled along a
#'   latitudinal gradient in Central Europe. This particular RMarkdown script
#'   provides functions and a pipeline to extract WorldClim 2.1 data (same as
#'   WorldClim 2.0 but with two more variables available, elevation and water
#'   vapor pressure). <b>Please cite this
#'   script as follows:</b></p><br><p>Eckert, S., Herden, J.,
#'   Stift, M., Durka, W., van Kleunen, M., & Joshi, J. (2022). Data From&colon;
#'   Traces of Genetic but Not Epigenetic Adaptation in the Invasive
#'   Goldenrod _Solidago canadensis_ Despite the Absence of Population
#'   Structure. _Zenodo_. doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.5281/zenodo.6388135">10.5281/zenodo.6388135</a></center></p>
#' geometry: margin=2cm
#' output:
#'   html_document:
#'      code_folding: show
#'      keep_md: FALSE
#'      theme: flatly
#'      highlight: textmate
#'      df_print: paged
#'      toc: true
#'      toc_float: true
#' ---
#' 

#'
#'```{r setup, include = FALSE}
#'knitr::opts_chunk$set(eval=FALSE, cache=FALSE, warning=FALSE)
#'```

#' # Packages
#' <a href="#top">Back to top</a>
#+ project_packages, results='hide', message=FALSE, warning=FALSE
########### packages ...................... ####
# install.packages("name_of_package") # install necessary packages
# install knitr to save this script as html output using RStudio with Ctrl+Shift+K (Windows & Linux) or Command+Shift+K (macOS)
# install.packages("knitr") 
# getwd() # get current working directory
# setwd() # set working directory
# create folder for datasets to be stored to get this RMarkdown script running
dir.create("./data",
           showWarnings=F)
library(rdryad)
library(tibble)
library(tidyverse)
library(goeveg)

#' # Functions
#' <a href="#top">Back to top</a>
#+ project_functions
########## Functions ####
# Modified function download_worldclim2() from package "edmaps"
# (use this code if you don't want to install the entire package)
# (or install package with remotes::install_github("jscamac/edmaps"))
download_wc2.1_var <- function(outfile,variable,resolution) {
  # outfile = Character. Name of the output file
  # variable = Character. Name of the WorldClim 2.1 variable
  # resolution = Character. One of "10m", "5m", "2.5m" or "30s"
  variable <- match.arg(variable, c("bio",
                                    "tmin", 
                                    "tmax",
                                    "tavg",
                                    "srad",
                                    "wind", 
                                    "vapr"))
  resolution <- match.arg(resolution, c("10m",
                                        "5m", 
                                        "2.5m",
                                        "30s"))
  if (!dir.exists(dirname(outfile)))
    dir.create(dirname(outfile))
  base_url <- "https://biogeo.ucdavis.edu/data/worldclim/v2.1/base/wc2.1"
  url <- sprintf("%s_%s_%s.zip",base_url,resolution,variable)
  download.file(url,outfile,mode="wb")
}
# function written to create RasterLayer objects from downloaded Worldclim tif files
rasterize_wc2.1_var <- function(var,res) {
  # var = Character. Worldclim variable, one of "bio[1:19]", "srad", "tavg", "tmin", "tmax", "prec", "wind", "vapr", "elev
  # res = Character. Resolution, one of "10m", "5m", "2.5m", "30s"
  vars_list=list()
  i=1
  for(i in 1:12) {
    vars_list[[length(vars_list)+1]] <- raster(paste0("wc2.1_",res,"_",var,"_",sprintf("%02d",i),".tif"))
    i=i+1
  }
  message("Created RasterLayer objects from given WorldClim 2.1 tif files.")
  return(vars_list) # list of RasterLayer objects per monthly tif file
}
# function written to extract data for given locations (site labels + coordinates)
extract_wc2.1_vars <- function(vars_list, coords) {
  # vars_list = List. RasterLayer objects returned from function rasterize_wc2.1_vars().
  # coords = Data frame. Labels of sites as row names, longitude in first column, latitude in second column, coordinates formatted in decimal degrees.
  vars_df = data.frame(sites = row.names(coords)) # sites
  vars_df$lon = coords[,1] # lon
  vars_df$lat = coords[,2] # lat
  vars_df
  i = 1
  for(i in 1:12) {
    vars_df[,as.character(i)] <- extract(vars_list[[i]], coords)
    i=i+1
  }
  message("Created monthly values for the given locations.")
  return(vars_df) # list of tables with monthly values for each bioclimatic variable
}
# function written to create averaged annual values from Worldclim variables
annualize_worldclim_v2.1_vars <- function(vars_dfs, list_labels) {
  # vars_dfs = List. Concatenated data frames returned from function extract_wc2.1_vars()
  # list_labels = List. Concatenated labels of WorldClim variables to annualize.
  vars_annual <- vars_dfs[[1]][,1:3]
  i=1
  j=1
  for(i in 1:length(vars_dfs)) {
    vars_annual[,list_labels[j]] <- apply(vars_dfs[[i]][,-c(1:3)], 1, function(x) mean(x[1:12]))
    i=i+1
    j=j+1
  }
  message("Created averaged annual values of Worldclim 2.1 variables.")
  return(vars_annual) # data frame of mean annual values
}

#' # Load data
#' <a href="#top">Back to top</a>
#+ project_load.data
########### Load data ...................... ####
# load AFLP/MSAP data
source("RMarkdown_Eckert_et_al_2022_loadMolecularData.R")

# load MEMGENE results table from AFLP dataset (to extract coordinates)
AFLP_memgene <- tibble(read.table(paste0(data_path,"MEMGENE_AFLP.txt"),
                                  header=T)); AFLP_memgene
# reduce to coordinates
xy_coords <- data.frame(lon=AFLP_memgene$longitude,
                        lat=AFLP_memgene$latitude); xy_coords
# sort by latitude
xy_coords <- xy_coords[order(xy_coords$lat,decreasing=F),] 
# download WorldClim v2.1 bioclimatic variables
# IMPORTANT: These files are big thus will take very long to download!
# BIO[1:19]
download_wc2.1_var('bio_30s.zip','bio','30s')
# solar radiation
download_wc2.1_var('srad_30s.zip','srad','30s')
# wind speed
download_wc2.1_var('wind_30s.zip','wind','30s')
# unzip downloaded .zip files
unzip("./data/bio_30s.zip")
unzip("./data/srad_30s.zip")
unzip("./data/wind_30s.zip")

#' ## Rasterize data
#' <a href="#top">Back to top</a>
#+ project_rasterize.data
########### Rasterize ####
# rasterize variables into RasterLayer objects
rasterized_bio1 <- rasterize_wc2.1_var("bio1","30s")
rasterized_bio2 <- rasterize_wc2.1_var("bio2","30s")
rasterized_bio3 <- rasterize_wc2.1_var("bio3","30s")
rasterized_bio4 <- rasterize_wc2.1_var("bio4","30s")
rasterized_bio5 <- rasterize_wc2.1_var("bio5","30s")
rasterized_bio6 <- rasterize_wc2.1_var("bio6","30s")
rasterized_bio7 <- rasterize_wc2.1_var("bio7","30s")
rasterized_bio8 <- rasterize_wc2.1_var("bio8","30s")
rasterized_bio9 <- rasterize_wc2.1_var("bio9","30s")
rasterized_bio10 <- rasterize_wc2.1_var("bio10","30s")
rasterized_bio11 <- rasterize_wc2.1_var("bio11","30s")
rasterized_bio12 <- rasterize_wc2.1_var("bio12","30s")
rasterized_bio13 <- rasterize_wc2.1_var("bio13","30s")
rasterized_bio14 <- rasterize_wc2.1_var("bio14","30s")
rasterized_bio15 <- rasterize_wc2.1_var("bio15","30s")
rasterized_bio16 <- rasterize_wc2.1_var("bio16","30s")
rasterized_bio17 <- rasterize_wc2.1_var("bio17","30s")
rasterized_bio18 <- rasterize_wc2.1_var("bio18","30s")
rasterized_bio19 <- rasterize_wc2.1_var("bio19","30s")
rasterized_srad <- rasterize_wc2.1_var("srad","30s")
rasterized_wind <- rasterize_wc2.1_var("wind","30s")

#' ## Extract locations
#' <a href="#top">Back to top</a>
#+ project_extract.data
########### Extract ####
extracted_vars <- extract_wc2.1_vars(c(rasterized_bio1,
                                       rasterized_bio2,
                                       rasterized_bio3,
                                       rasterized_bio4,
                                       rasterized_bio5,
                                       rasterized_bio6,
                                       rasterized_bio7,
                                       rasterized_bio8,
                                       rasterized_bio9,
                                       rasterized_bio10,
                                       rasterized_bio11,
                                       rasterized_bio12,
                                       rasterized_bio13,
                                       rasterized_bio14,
                                       rasterized_bio15,
                                       rasterized_bio16,
                                       rasterized_bio17,
                                       rasterized_bio18,
                                       rasterized_bio19,
                                       rasterized_wind),
                                     coords=xy_coords); extracted_vars

#' ## Annualize data
#' <a href="#top">Back to top</a>
#+ project_annualize.data
########### Annualize ####
wc2.1_labels <- c("BIO1",
                  "BIO2",
                  "BIO3",
                  "BIO4",
                  "BIO5",
                  "BIO6",
                  "BIO7",
                  "BIO8",
                  "BIO9",
                  "BIO10",
                  "BIO11",
                  "BIO12",
                  "BIO13",
                  "BIO14",
                  "BIO15",
                  "BIO16",
                  "BIO17",
                  "BIO18",
                  "BIO19",
                  "Wind Speed"); wc2.1_labels
annualized_vars <- annualize_worldclim_v2.1_vars(extracted_vars,
                                                 wc2.1_labels); annualized_vars

#' ## Solar radiation
#' <a href="#top">Back to top</a>
#+ project_cv.srad
########### CV srad ####
# calculate coefficent of variation for solar radiation
extracted_srad <- extract_wc2.1_vars(rasterized_srad,
                                     coords=xy_coords); extracted_srad # list of 1
srad_cv <- apply(extracted_srad[[1]][,-c(1:3)],1,cv); srad_cv
# add to annualized-variables table
annualized_vars$'Solar Radiation' <- srad_cv
# change order, rename annualized-variables table and coordinate columns
annualized_vars <- annualized_vars[,c(1:23,25,24)]
colnames(annualized_vars)[1:2] <- c("Longitude","Latitude")
ClimData <- tibble(annualized_vars[,c(1:2)],
                   populationID = as.integer(1:25),
                   annualized_vars[,-c(1:2)],
                   AFLP_memgene[,1:3]); ClimData

#' # Save
#' <a href="#top">Back to top</a>
#+ project_save
########### Save ####
write.table(ClimData,
            "Data_wc2_PopulationData.txt",
            row.names=F)

#' # Session info
#' <a href="#top">Back to top</a>
#+ Session.info
sessionInfo()
#' <a href="#top">Back to top</a>
######## Session info .................. ####