#' ---
#' title: <center><b>Markdown document from&colon;</b><br>Traces of Genetic but Not Epigenetic Adaptation in the Invasive Goldenrod _Solidago canadensis_ Despite the Absence of Population Structure</center>
#' pagetitle: RMarkdown document from:&nbsp;Eckert&nbsp;et&nbsp;al.&nbsp;(2022)
#' subtitle: <center>doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.3389/fevo.2022.856453">10.3389/fevo.2022.856453</a></center>
#' author: <center>Eckert, S., Herden, J., Stift, M., Durka, W., van Kleunen, M., & Joshi, J.</center>
#' date: <center>`r Sys.Date()`</center>
#' abstract: <p align="justify">This RMarkdown script belongs
#'   to a series of scripts generated by Silvia Eckert as part of
#'   the statistical analysis for the above-mentioned manuscript.
#'   The data underlying the applied R code can be found in the ZENODO
#'   repository and contains genetic (AFLP) and epigenetic (MSAP) markers
#'   from offspring of 25 _Solidago canadensis_ populations sampled along a
#'   latitudinal gradient in Central Europe. This particular RMarkdown script
#'   applies the Mantel test on plant traits, AFLP and MSAP datasets. <b>Please cite this
#'   script as follows:</b></p><br><p>Eckert, S., Herden, J.,
#'   Stift, M., Durka, W., van Kleunen, M., & Joshi, J. (2022). Data From&colon;
#'   Traces of Genetic but Not Epigenetic Adaptation in the Invasive
#'   Goldenrod _Solidago canadensis_ Despite the Absence of Population
#'   Structure. _Zenodo_. doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.5281/zenodo.6388135">10.5281/zenodo.6388135</a></center></p>
#' geometry: margin=2cm
#' output:
#'   html_document:
#'      code_folding: show
#'      keep_md: FALSE
#'      theme: flatly
#'      highlight: textmate
#'      df_print: paged
#'      toc: true
#'      toc_float: true
#' ---
#' 

#'
#'```{r setup, include = FALSE}
#'knitr::opts_chunk$set(eval=FALSE, cache=FALSE, warning=FALSE)
#'```

#' # Packages
#' <a href="#top">Back to top</a>
#+ project_packages, results='hide', message=FALSE, warning=FALSE
########### packages ...................... ####
# install.packages("name_of_package") # install necessary packages
# install knitr to save this script as html output using RStudio with Ctrl+Shift+K (Windows & Linux) or Command+Shift+K (macOS)
# install.packages("knitr") 
# getwd() # get current working directory
# setwd() # set working directory
# create folder for datasets to be stored to get this RMarkdown script running
dir.create("./data",
           showWarnings=F)
# add necessary libraries
library(ade4)
library(tibble)
library(vegan)
library(ggplot2)
library(cowplot)

#' # Functions
#' <a href="#top">Back to top</a>
#+ functions
########## functions ####
# Function written to calculate the empirical quantile dispersion coefficient
eqdc <- function(x){
  IQR(x,
      na.rm=T,
      type=7)/median(x,
                     na.rm=T)}

#' # Load data
#' <a href="#top">Back to top</a>
#+ project_load.data
########### Load data ...................... ####
# load AFLP/MSAP data
source("RMarkdown_Eckert_et_al_2022_loadMolecularData.R")

#' ## AFLP
#+ project_load.AFLP
######## AFLP ####
# split by treatment (C/CON = Control; Z/ZEB = zebularine-treated)
AFLP_C <- AFLP[AFLP$treatment=='CON',]; AFLP_C; dim(AFLP_C)
AFLP_Z <- AFLP[AFLP$treatment=='ZEB',]; AFLP_Z; dim(AFLP_Z)

#' ## MSAP-n
#' <a href="#top">Back to top</a>
#+ project_load.MSAPu
######## MSAP-n ####
# split by treatment
MSAPn_C <- MSAPn[MSAPn$treatment=='CON',]; MSAPn_C; dim(MSAPn_C)
MSAPn_Z <- MSAPn[MSAPn$treatment=='ZEB',]; MSAPn_Z;  dim(MSAPn_Z)

#' ## MSAP-m
#' <a href="#top">Back to top</a>
#+ project_load.MSAPm
######## MSAP-m ####
# split by treatment
MSAPm_C <- MSAPm[MSAPm$treatment=='CON',]; MSAPm_C; dim(MSAPm_C)
MSAPm_Z <- MSAPm[MSAPm$treatment=='ZEB',]; MSAPm_Z; dim(MSAPm_Z)

#' ## TRAITS
#' <a href="#top">Back to top</a>
#+ project_TRAITS
######## plant traits ####
# load trait data
source("RMarkdown_Eckert_et_al_2022_loadTraitData.R")

#' ## Intersection
#' <a href="#top">Back to top</a>
#+ project_intersection.samples
######## intersection ####
# calculate intersection of all tables, so only samples are analyzed for which
# traits were measured and AFLP/MSAP genotyping was applied successfully
# CON
common_C_TRAITS_MSAPm <- intersect(TRAITS_C$uniqueID,
                                   MSAPm_C$uniqueID); common_C_TRAITS_MSAPm
common_C <- intersect(common_C_TRAITS_MSAPm,
                      AFLP_C$uniqueID); common_C
# intersect
dim(AFLP_C_intersection <- AFLP_C[AFLP_C$uniqueID %in% common_C,])
dim(MSAPm_C_intersection <- MSAPm_C[MSAPm_C$uniqueID %in% common_C,])
dim(MSAPn_C_intersection <- MSAPn_C[MSAPn_C$uniqueID %in% common_C,])
dim(TRAITS_C_intersection <- TRAITS_C[TRAITS_C$uniqueID %in% common_C,])
# combined table
dim(Manteldata_C <- Reduce(merge,
                           list(AFLP_C_intersection,
                                MSAPm_C_intersection,
                                MSAPn_C_intersection,
                                TRAITS_C_intersection)))
# save
write.table(Manteldata_C,
            file="./data/Data_MantelTest_CON_intersection.txt",
            row.names=F)
# ZEB
common_Z_TRAITS_MSAPm <- intersect(TRAITS_Z$uniqueID,
                                   MSAPm_Z$uniqueID); common_Z_TRAITS_MSAPm
common_Z <- intersect(common_Z_TRAITS_MSAPm,
                      AFLP_Z$uniqueID); common_Z
# intersect
dim(AFLP_Z_intersection <- AFLP_Z[AFLP_Z$uniqueID %in% common_Z,])
dim(MSAPm_Z_intersection <- MSAPm_Z[MSAPm_Z$uniqueID %in% common_Z,])
dim(MSAPn_Z_intersection <- MSAPn_Z[MSAPn_Z$uniqueID %in% common_Z,])
dim(TRAITS_Z_intersection <- TRAITS_Z[TRAITS_Z$uniqueID %in% common_Z,])
# combined table
dim(Manteldata_Z <- Reduce(merge,
                           list(AFLP_Z_intersection,
                                MSAPm_Z_intersection,
                                MSAPn_Z_intersection,
                                TRAITS_Z_intersection)))
# save
write.table(Manteldata_Z,
            file="./data/Data_MantelTest_ZEB_intersection.txt",
            row.names=F)

#' # Distance matrices
#' <a href="#top">Back to top</a>
#+ project_distances
######## distance matrices ......... ####
#' ## AFLP
#' <a href="#top">Back to top</a>
#+ project_distances.AFLP
######## AFLP ####
# NOTE: calculation might take a bit longer!
# CON
system.time(AFLP_C.neifst <- hierfstat::pairwise.neifst(Manteldata_C[,c(7,9:369)],
                                                        diploid=T))
# clamp all negative vlaues to zero
AFLP_C.neifst_clamped <- pmax(AFLP_C.neifst,0)
AFLP_C.neifst_clamped.dist <- as.dist(AFLP_C.neifst_clamped)
AFLP_C.neifst_clamped.dist
# ZEB
AFLP_Z.neifst <- hierfstat::pairwise.neifst(Manteldata_Z[,c(7,9:369)],
                                            diploid=T)
# clamp all negative vlaues to zero
AFLP_Z.neifst_clamped <- pmax(AFLP_Z.neifst,0)
AFLP_Z.neifst_clamped.dist <- as.dist(AFLP_Z.neifst_clamped)
AFLP_Z.neifst_clamped.dist

#' ## MSAP-m
#' <a href="#top">Back to top</a>
#+ project_distances.MSAPm
######## MSAP-m ####
# CON
MSAPm_C.neifst <- hierfstat::pairwise.neifst(Manteldata_C[,c(7,370:556)],
                                              diploid=T)
# clamp all negative vlaues to zero
MSAPm_C.neifst_clamped <- pmax(MSAPm_C.neifst,0)
MSAPm_C.neifst_clamped.dist <- as.dist(MSAPm_C.neifst_clamped)
MSAPm_C.neifst_clamped.dist
# ZEB
MSAPm_Z.neifst <- hierfstat::pairwise.neifst(Manteldata_Z[,c(7,370:556)],
                                              diploid=T)
# clamp all negative vlaues to zero
MSAPm_Z.neifst_clamped <- pmax(MSAPm_Z.neifst,0)
MSAPm_Z.neifst_clamped.dist <- as.dist(MSAPm_Z.neifst_clamped)
MSAPm_Z.neifst_clamped.dist

#' ## MSAP-n
#' <a href="#top">Back to top</a>
#+ project_distances.MSAPu
######## MSAP-n ####
# CON
MSAPn_C.neifst <- hierfstat::pairwise.neifst(Manteldata_C[,c(7,557:738)],
                                              diploid=T)
# clamp all negative values to zero
MSAPn_C.neifst_clamped <- pmax(MSAPn_C.neifst,0)
MSAPn_C.neifst_clamped.dist <- as.dist(MSAPn_C.neifst_clamped)
MSAPn_C.neifst_clamped.dist
# ZEB
MSAPn_Z.neifst <- hierfstat::pairwise.neifst(Manteldata_Z[,c(7,557:738)],
                                              diploid=T)
# clamp all negative vlaues to zero
MSAPn_Z.neifst_clamped <- pmax(MSAPn_Z.neifst,0)
MSAPn_Z.neifst_clamped.dist <- as.dist(MSAPn_Z.neifst_clamped)
MSAPn_Z.neifst_clamped.dist

#' ## Traits
#' <a href="#top">Back to top</a>
#+ project_distances.Traits
######## plant traits ####
# aggregate each trait by population-level
# using the empirical quantile dispersion coefficient
# CON
TRAITS_C.pop <- aggregate(TRAITS_C[,17:22], # the number of ramets was not used
                          list(TRAITS_C$populationID),
                          FUN=eqdc)
colnames(TRAITS_C.pop) <- c("popID",
                            "eqdc_plantheight2015",
                            "eqdc_plantheight2016",
                            "eqdc_flowering2015",
                            "eqdc_flowering2016",
                            "eqdc_totalbiomass2015",
                            "eqdc_bioratio2015"); tibble(TRAITS_C.pop)
# distance matrix
TRAITS_C.dist <- dist(TRAITS_C.pop[,-1]); TRAITS_C.dist # euclidean distance
# ZEB
# aggregate using the empirical quantile dispersion coefficient
TRAITS_Z.pop <- aggregate(TRAITS_Z[,17:22],
                          list(TRAITS_Z$populationID),
                          FUN=eqdc)
colnames(TRAITS_Z.pop) <- c("popID",
                            "eqdc_plantheight2015",
                            "eqdc_plantheight2016",
                            "eqdc_flowering2015",
                            "eqdc_flowering2016",
                            "eqdc_totalbiomass2015",
                            "eqdc_bioratio2015"); tibble(TRAITS_Z.pop)
# distance matrix
TRAITS_Z.dist <- dist(TRAITS_Z.pop[,-1]); TRAITS_Z.dist

#' ## MEMGENEs
#' <a href="#top">Back to top</a>
#+ project_distances.memgenes
######## MEMGENEs ####
MEMGENEs <- tibble(read.table("./data/Data_MEMGENE_AFLP.txt",
                              header=T)); MEMGENEs
# distance for MEMGENE1
MEMGENE1.dist <- dist(MEMGENEs$MEMGENE1); MEMGENE1.dist
# distance for MEMGENE2
MEMGENE2.dist <- dist(MEMGENEs$MEMGENE2); MEMGENE2.dist
# distance for MEMGENE3
MEMGENE3.dist <- dist(MEMGENEs$MEMGENE3); MEMGENE3.dist

#' # Mantel tests
#' <a href="#top">Back to top</a>
#+ project_Mantel
######## Mantel tests .................. ####
#' ## CON
#' <a href="#top">Back to top</a>
#+ project_Mantel.CON
######## CON ####
#' ### MSAP-m
#' <a href="#top">Back to top</a>
#+ project_Mantel.CON.MSAPm
######## MSAP-m ####
# AFLP vs Traits
set.seed(123)
mantel_C_A.vs.T <- mantel(TRAITS_C.dist,
                          AFLP_C.neifst_clamped.dist,
                          permutations=9999); mantel_C_A.vs.T
# AFLP vs MSAP-n
set.seed(123)
mantel_C_A.vs.Mm <- mantel(MSAPm_C.neifst_clamped.dist,
                           AFLP_C.neifst_clamped.dist,
                           permutations=9999); mantel_C_A.vs.Mm
# Traits vs. MSAP-m (no correction)
set.seed(123)
mantel_C_T.vs.Mm <- mantel(MSAPm_C.neifst_clamped.dist,
                           TRAITS_C.dist,
                           permutations=9999); mantel_C_T.vs.Mm
# Traits vs. MSAP-m (AFLP)
set.seed(123)
mantel_C_T.vs.Mm_A <- mantel.partial(MSAPm_C.neifst_clamped.dist,
                                     TRAITS_C.dist,
                                     zdis=AFLP_C.neifst_clamped.dist,
                                     permutations=9999); mantel_C_T.vs.Mm_A
# Traits vs. MSAP-m (MEMGENE1)
set.seed(123)
mantel_C_T.vs.Mm_M1 <- mantel.partial(MSAPm_C.neifst_clamped.dist,
                                      TRAITS_C.dist,
                                      zdis=MEMGENE1.dist,
                                      permutations=9999); mantel_C_T.vs.Mm_M1
# Traits vs. MSAP-m (MEMGENE2)
set.seed(123)
mantel_C_T.vs.Mm_M2 <- mantel.partial(MSAPm_C.neifst_clamped.dist,
                                      TRAITS_C.dist,
                                      zdis=MEMGENE2.dist,
                                      permutations=9999); mantel_C_T.vs.Mm_M2
# Traits vs. MSAP-m (MEMGENE3)
set.seed(123)
mantel_C_T.vs.Mm_M3 <- mantel.partial(MSAPm_C.neifst_clamped.dist,
                                      TRAITS_C.dist,
                                      zdis=MEMGENE3.dist,
                                      permutations=9999); mantel_C_T.vs.Mm_M3

#' ### MSAP-n
#' <a href="#top">Back to top</a>
#+ project_Mantel.CON.MSAPu
######## MSAP-n ####
# AFLP vs MSAP-n
set.seed(123)
mantel_C_A.vs.Mu <- mantel(MSAPn_C.neifst_clamped.dist,
                           AFLP_C.neifst_clamped.dist,
                           permutations=9999); mantel_C_A.vs.Mu
# Traits vs. MSAP-m (no correction)
set.seed(123)
mantel_C_T.vs.Mu <- mantel(MSAPn_C.neifst_clamped.dist,
                           TRAITS_C.dist,
                           permutations=9999); mantel_C_T.vs.Mu
# Traits vs. MSAP-m (AFLP)
set.seed(123)
mantel_C_T.vs.Mu_A <- mantel.partial(MSAPn_C.neifst_clamped.dist,
                                     TRAITS_C.dist,
                                     zdis=AFLP_C.neifst_clamped.dist,
                                     permutations=9999); mantel_C_T.vs.Mu_A
# Traits vs. MSAP-m (MEMGENE1)
set.seed(123)
mantel_C_T.vs.Mu_M1 <- mantel.partial(MSAPn_C.neifst_clamped.dist,
                                      TRAITS_C.dist,
                                      zdis=MEMGENE1.dist,
                                      permutations=9999); mantel_C_T.vs.Mu_M1
# Traits vs. MSAP-m (MEMGENE2)
set.seed(123)
mantel_C_T.vs.Mu_M2 <- mantel.partial(MSAPn_C.neifst_clamped.dist,
                                      TRAITS_C.dist,
                                      zdis=MEMGENE2.dist,
                                      permutations=9999); mantel_C_T.vs.Mu_M2
# Traits vs. MSAP-m (MEMGENE3)
set.seed(123)
mantel_C_T.vs.Mu_M3 <- mantel.partial(MSAPn_C.neifst_clamped.dist,
                                      TRAITS_C.dist,
                                      zdis=MEMGENE3.dist,
                                      permutations=9999); mantel_C_T.vs.Mu_M3

#' ## ZEB
#' <a href="#top">Back to top</a>
#+ project_Mantel.ZEB
######## ZEB ####
#' ### MSAP-m
#' <a href="#top">Back to top</a>
#+ project_Mantel.ZEB.MSAPm
######## MSAP-m ####
# AFLP vs Traits
set.seed(123)
mantel_Z_A.vs.T <- mantel(TRAITS_Z.dist,
                          AFLP_Z.neifst_clamped.dist,
                          permutations=9999); mantel_Z_A.vs.T
# AFLP vs MSAP-n
set.seed(123)
mantel_Z_A.vs.Mm <- mantel(MSAPm_Z.neifst_clamped.dist,
                           AFLP_Z.neifst_clamped.dist,
                           permutations=9999); mantel_Z_A.vs.Mm
# Traits vs. MSAP-m (no correction)
set.seed(123)
mantel_Z_T.vs.Mm <- mantel(MSAPm_Z.neifst_clamped.dist,
                           TRAITS_Z.dist,
                           permutations=9999); mantel_Z_T.vs.Mm
# Traits vs. MSAP-m (AFLP)
set.seed(123)
mantel_Z_T.vs.Mm_A <- mantel.partial(MSAPm_Z.neifst_clamped.dist,
                                     TRAITS_Z.dist,
                                     zdis=AFLP_Z.neifst_clamped.dist,
                                     permutations=9999); mantel_Z_T.vs.Mm_A
# Traits vs. MSAP-m (MEMGENE1)
set.seed(123)
mantel_Z_T.vs.Mm_M1 <- mantel.partial(MSAPm_Z.neifst_clamped.dist,
                                      TRAITS_Z.dist,
                                      zdis=MEMGENE1.dist,
                                      permutations=9999); mantel_Z_T.vs.Mm_M1
# Traits vs. MSAP-m (MEMGENE2)
set.seed(123)
mantel_Z_T.vs.Mm_M2 <- mantel.partial(MSAPm_Z.neifst_clamped.dist,
                                      TRAITS_Z.dist,
                                      zdis=MEMGENE2.dist,
                                      permutations=9999); mantel_Z_T.vs.Mm_M2
# Traits vs. MSAP-m (MEMGENE3)
set.seed(123)
mantel_Z_T.vs.Mm_M3 <- mantel.partial(MSAPm_Z.neifst_clamped.dist,
                                      TRAITS_Z.dist,
                                      zdis=MEMGENE3.dist,
                                      permutations=9999); mantel_Z_T.vs.Mm_M3

#' ### MSAP-n
#' <a href="#top">Back to top</a>
#+ project_Mantel.ZEB.MSAPu
######## MSAP-n ####
# AFLP vs MSAP-n
set.seed(123)
mantel_Z_A.vs.Mu <- mantel(MSAPn_Z.neifst_clamped.dist,
                           AFLP_Z.neifst_clamped.dist,
                           permutations=9999); mantel_Z_A.vs.Mu
# Traits vs. MSAP-m (no correction)
set.seed(123)
mantel_Z_T.vs.Mu <- mantel(MSAPn_Z.neifst_clamped.dist,
                           TRAITS_Z.dist,
                           permutations=9999); mantel_Z_T.vs.Mu
# Traits vs. MSAP-m (AFLP)
set.seed(123)
mantel_Z_T.vs.Mu_A <- mantel.partial(MSAPn_Z.neifst_clamped.dist,
                                     TRAITS_Z.dist,
                                     zdis=AFLP_Z.neifst_clamped.dist,
                                     permutations=9999); mantel_Z_T.vs.Mu_A
# Traits vs. MSAP-m (MEMGENE1)
set.seed(123)
mantel_Z_T.vs.Mu_M1 <- mantel.partial(MSAPn_Z.neifst_clamped.dist,
                                      TRAITS_Z.dist,
                                      zdis=MEMGENE1.dist,
                                      permutations=9999); mantel_Z_T.vs.Mu_M1
# Traits vs. MSAP-m (MEMGENE2)
set.seed(123)
mantel_Z_T.vs.Mu_M2 <- mantel.partial(MSAPn_Z.neifst_clamped.dist,
                                      TRAITS_Z.dist,
                                      zdis=MEMGENE2.dist,
                                      permutations=9999); mantel_Z_T.vs.Mu_M2
# Traits vs. MSAP-m (MEMGENE3)
set.seed(123)
mantel_Z_T.vs.Mu_M3 <- mantel.partial(MSAPn_Z.neifst_clamped.dist,
                                      TRAITS_Z.dist,
                                      zdis=MEMGENE3.dist,
                                      permutations=9999); mantel_Z_T.vs.Mu_M3

#' ## Table 2
#' <a href="#top">Back to top</a>
#+ project_Mantel.table2
######## Table 2 ........................... ####
# collect all values in one table
Mantel_results <- tibble(treatment=c(rep("CON",7),
                                       rep("ZEB",7),
                                       rep("CON",6),
                                       rep("ZEB",6)),
                         # first distance matrix
                         dist_x=c("TRAITS",
                                    rep("MSAP_m",6),
                                    "TRAITS",
                                    rep("MSAP_m",6),
                                    rep(rep("MSAP_u",6),2)),
                         # second distance matrix
                         dist_y=c(rep(c(rep("AFLP",2),
                                          rep("TRAITS",5)),2),
                                    rep(c(rep("AFLP",1),
                                          rep("TRAITS",5)),2)),
                         # third distance matrix (if applicable; for partial mantel test)
                         dist_z=c(rep("NA",3),
                                    "AFLP",
                                    "MEMGENE1",
                                    "MEMGENE2",
                                    "MEMGENE3",
                                    rep("NA",3),
                                    "AFLP",
                                    "MEMGENE1",
                                    "MEMGENE2",
                                    "MEMGENE3",
                                    rep("NA",2),
                                    "AFLP",
                                    "MEMGENE1",
                                    "MEMGENE2",
                                    "MEMGENE3",
                                    rep("NA",2),
                                    "AFLP",
                                    "MEMGENE1",
                                    "MEMGENE2",
                                    "MEMGENE3"),
                         # Mantel test value
                         Mantel_r=c(mantel_C_A.vs.T$statistic,
                                      mantel_C_A.vs.Mm$statistic,
                                      mantel_C_T.vs.Mm$statistic,
                                      mantel_C_T.vs.Mm_A$statistic,
                                      mantel_C_T.vs.Mm_M1$statistic,
                                      mantel_C_T.vs.Mm_M2$statistic,
                                      mantel_C_T.vs.Mm_M3$statistic,
                                      mantel_Z_A.vs.T$statistic,
                                      mantel_Z_A.vs.Mm$statistic,
                                      mantel_Z_T.vs.Mm$statistic,
                                      mantel_Z_T.vs.Mm_A$statistic,
                                      mantel_Z_T.vs.Mm_M1$statistic,
                                      mantel_Z_T.vs.Mm_M2$statistic,
                                      mantel_Z_T.vs.Mm_M3$statistic,
                                      mantel_C_A.vs.Mu$statistic,
                                      mantel_C_T.vs.Mu$statistic,
                                      mantel_C_T.vs.Mu_A$statistic,
                                      mantel_C_T.vs.Mu_M1$statistic,
                                      mantel_C_T.vs.Mu_M2$statistic,
                                      mantel_C_T.vs.Mu_M3$statistic,
                                      mantel_Z_A.vs.Mu$statistic,
                                      mantel_Z_T.vs.Mu$statistic,
                                      mantel_Z_T.vs.Mu_A$statistic,
                                      mantel_Z_T.vs.Mu_M1$statistic,
                                      mantel_Z_T.vs.Mu_M2$statistic,
                                      mantel_Z_T.vs.Mu_M3$statistic),
                         # Mantel p value
                         p_value=c(mantel_C_A.vs.T$signif,
                                     mantel_C_A.vs.Mm$signif,
                                     mantel_C_T.vs.Mm$signif,
                                     mantel_C_T.vs.Mm_A$signif,
                                     mantel_C_T.vs.Mm_M1$signif,
                                     mantel_C_T.vs.Mm_M2$signif,
                                     mantel_C_T.vs.Mm_M3$signif,
                                     mantel_Z_A.vs.T$signif,
                                     mantel_Z_A.vs.Mm$signif,
                                     mantel_Z_T.vs.Mm$signif,
                                     mantel_Z_T.vs.Mm_A$signif,
                                     mantel_Z_T.vs.Mm_M1$signif,
                                     mantel_Z_T.vs.Mm_M2$signif,
                                     mantel_Z_T.vs.Mm_M3$signif,
                                     mantel_C_A.vs.Mu$signif,
                                     mantel_C_T.vs.Mu$signif,
                                     mantel_C_T.vs.Mu_A$signif,
                                     mantel_C_T.vs.Mu_M1$signif,
                                     mantel_C_T.vs.Mu_M2$signif,
                                     mantel_C_T.vs.Mu_M3$signif,
                                     mantel_Z_A.vs.Mu$signif,
                                     mantel_Z_T.vs.Mu$signif,
                                     mantel_Z_T.vs.Mu_A$signif,
                                     mantel_Z_T.vs.Mu_M1$signif,
                                     mantel_Z_T.vs.Mu_M2$signif,
                                     mantel_Z_T.vs.Mu_M3$signif))
# add corrected p-values
Mantel_results$FDR <- c(p.adjust(Mantel_results$p_value[c(1:7)],
                                 method="BH"),
                        p.adjust(Mantel_results$p_value[c(8:14)],
                                 method="BH"),
                        p.adjust(Mantel_results$p_value[c(15:20)],
                                 method="BH"),
                        p.adjust(Mantel_results$p_value[c(21:26)],
                                 method="BH"))
tibble(Mantel_results)
# save
write.table(Mantel_results,
            file="./data/Table2_Eckert_et_al_2022_Mantel_results.txt",
            row.names=F)

#' # Session info
#' <a href="#top">Back to top</a>
#+ Session.info
sessionInfo()
#' <a href="#top">Back to top</a>
######## Session info .................. ####