#' ---
#' title: <center><b>Markdown document from&colon;</b><br>Traces of Genetic but Not Epigenetic Adaptation in the Invasive Goldenrod _Solidago canadensis_ Despite the Absence of Population Structure</center>
#' pagetitle: RMarkdown document from:&nbsp;Eckert&nbsp;et&nbsp;al.&nbsp;(2022)
#' subtitle: <center>doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.3389/fevo.2022.856453">10.3389/fevo.2022.856453</a></center>
#' author: <center>Eckert, S., Herden, J., Stift, M., Durka, W., van Kleunen, M., & Joshi, J.</center>
#' date: <center>`r Sys.Date()`</center>
#' abstract: <p align="justify">This RMarkdown script belongs
#'   to a series of scripts generated by Silvia Eckert as part of
#'   the statistical analysis for the above-mentioned manuscript.
#'   The data underlying the applied R code can be found in the ZENODO
#'   repository and contains genetic (AFLP) and epigenetic (MSAP) markers
#'   from offspring of 25 _Solidago canadensis_ populations sampled along a
#'   latitudinal gradient in Central Europe. This particular RMarkdown script
#'   applies the MEMGENE and IBD analysis and creates corresponding plots. <b>Please cite this
#'   script as follows:</b></p><br><p>Eckert, S., Herden, J.,
#'   Stift, M., Durka, W., van Kleunen, M., & Joshi, J. (2022). Data From&colon;
#'   Traces of Genetic but Not Epigenetic Adaptation in the Invasive
#'   Goldenrod _Solidago canadensis_ Despite the Absence of Population
#'   Structure. _Zenodo_. doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.5281/zenodo.6388135">10.5281/zenodo.6388135</a></center></p>
#' geometry: margin=2cm
#' output:
#'   html_document:
#'      code_folding: show
#'      keep_md: FALSE
#'      theme: flatly
#'      highlight: textmate
#'      df_print: paged
#'      toc: true
#'      toc_float: true
#' ---
#' 

#'
#'```{r setup, include = FALSE}
#'knitr::opts_chunk$set(eval=FALSE, cache=FALSE, warning=FALSE)
#'```

#' # Packages
#' <a href="#top">Back to top</a>
#+ project_packages, results='hide', message=FALSE, warning=FALSE
########### packages ...................... ####
# install.packages("name_of_package") # install necessary packages
# install knitr to save this script as html output using RStudio with Ctrl+Shift+K (Windows & Linux) or Command+Shift+K (macOS)
# install.packages("knitr") 
# getwd() # get current working directory
# setwd() # set working directory
# create folder for datasets to be stored to get this RMarkdown script running
dir.create("./data",
           showWarnings=F)
# add necessary libraries
library(tibble)
library(tidyverse)

#' # Load data
#' <a href="#top">Back to top</a>
#+ project_load.data
########### load data ....................... ####
# load AFLP/MSAP data
source("RMarkdown_AFLPMSAP_loadMolecularData.R")
# split by treatment level (CON/C = control; ZEB/Z = zebularine-treated)
# AFLP
AFLP_C <- AFLP[AFLP$treatment=='CON',]
AFLP_Z <- AFLP[AFLP$treatment=='ZEB',]
# MSAP-n (non-methylated loci)
MSAPn_C <- MSAPn[MSAPn$treatment=='CON',]; MSAPn_C; dim(MSAPn_C)
MSAPn_Z <- MSAPn[MSAPn$treatment=='ZEB',]; MSAPn_Z;  dim(MSAPn_Z)
# MSAP-m (methylated loci)
MSAPm_C <- MSAPm[MSAPm$treatment=='CON',]; MSAPm_C; dim(MSAPm_C)
MSAPm_Z <- MSAPm[MSAPm$treatment=='ZEB',]; MSAPm_Z; dim(MSAPm_Z)

#' # MEMGENE analysis
#' <a href="#top">Back to top</a>
#+ project_memgene
########### memgene ....................... ####
#' ## AFLP
#+ project_memgene.AFLP
########### AFLP ####
# coordinates
AFLP_C.coords <- data.frame(AFLP_C$lon,
                            AFLP_C$lat,
                            row.names=AFLP_C$uniqueID); AFLP_C.coords 
# AFLP
AFLP_C.memdata <- data.frame(AFLP_C[,-c(1:8)],
                             row.names=AFLP_C$uniqueID); AFLP_C.memdata
# Nei distance
AFLP_C.dist <- read.table("./data/GenAlEx_AFLP_unbiasedNei.txt",
                          row.names=1,
                          header=T)
AFLP_C.dist <- as.dist(AFLP_C.dist); AFLP_C.dist
# sort coords
AFLP_C.coords_sorted <- unique(AFLP_C.coords[order(AFLP_C.coords$AFLP_C.lat),])
AFLP_C.coords <- data.frame(row.names=c(1:25),
                            AFLP_C.coords_sorted); AFLP_C.coords
# attributes
AFLP_C.matrix <- as.matrix(AFLP_C.dist)
AFLP_C.attr <- list(sprintf("%02d",1:25),
                    sprintf("%02d",1:25))
attr(AFLP_C.matrix,"dimnames") <- AFLP_C.attr; attr(AFLP_C.matrix,"dimnames")
AFLP_C.matrix
# MEMGENE analysis
set.seed(123)
AFLP_C.memgene <- mgQuick(genD=AFLP_C.matrix,
                          coords=AFLP_C.coords,
                          forwardAlpha=0.05,
                          longlat=T,
                          forwardPerm=1000,
                          finalPerm=1000,
                          doPlot=2,
                          verbose=T); AFLP_C.memgene
tibble(AFLP_C.memgene$memSelected)
AFLP_C.memgene$RsqAdj
## find proportional variation explained by each MEMGENE variable
AFLP_C.prop <- round(AFLP_C.memgene$sdev/sum(AFLP_C.memgene$sdev),2); AFLP_C.prop
## print proportions for the first three MEMGENE variables
format(signif(AFLP_C.prop,3)[1:5],scientific=F)

#' ## MSAP-m
#' <a href="#top">Back to top</a>
#+ project_memgene.MSAPm
########### MSAP-m ####
# coordinates
MSAPm_C.coords <- data.frame(MSAPm_C$lon,
                              MSAPm_C$lat,
                              row.names=MSAPm_C$uniqueID); MSAPm_C.coords 
# MSAPm
MSAPm_C.memdata <- data.frame(MSAPm_C[,-c(1:8)],
                               row.names=MSAPm_C$uniqueID); MSAPm_C.memdata
# unbiased Nei distance
MSAPm_C.dist <- read.table("./data/GenalEx_MSAPm_unbiasedNei.txt",
                            row.names=1,header=T)
MSAPm_C.dist <- as.dist(MSAPm_C.dist); MSAPm_C.dist
# sort coords
MSAPm_C.coords_sorted <- unique(MSAPm_C.coords[order(MSAPm_C.coords$MSAPm_C.lat),])
MSAPm_C.coords <- data.frame(row.names=c(1:25),
                              MSAPm_C.coords_sorted); MSAPm_C.coords
# attributes
MSAPm_C.matrix <- as.matrix(MSAPm_C.dist)
MSAPm_C.attr <- list(sprintf("%02d",1:25),
                      sprintf("%02d",1:25))
attr(MSAPm_C.matrix,"dimnames") <- MSAPm_C.attr; attr(MSAPm_C.matrix,"dimnames")
MSAPm_C.matrix
# memgene
MSAPm_C.memgene <- mgQuick(genD=MSAPm_C.matrix,
                           coords=MSAPm_C.coords,
                           forwardAlpha=0.05,
                           longlat=T,
                           forwardPerm=1000,
                           finalPerm=1000,
                           doPlot=2,
                           verbose=T); MSAPm_C.memgene
MSAPm_C.memgene$memSelected
MSAPm_C.memgene$error

#' ## MSAP-n
#' <a href="#top">Back to top</a>
#+ project_memgene.MSAPn
########### MSAP-n ####
# coordinates
MSAPn_C.coords <- data.frame(MSAP.n_C$lon,
                              MSAP.n_C$lat,
                              row.names=MSAPn_C$uniqueID); MSAPn_C.coords 
# MSAPn
MSAPn_C.memdata <- data.frame(MSAPn_C[,-c(1:8)],
                               row.names=MSAPn_C$uniqueID); MSAPn_C.memdata
# unbiased Nei distance
MSAPn_C.dist <- read.table("./data/GenAlEx_MSAPn_unbiasedNei.txt",
                            row.names=1,header=T)
MSAPn_C.dist <- as.dist(MSAPn_C.dist); MSAPn_C.dist
# sort coords
MSAPn_C.coords_sorted <- unique(MSAPn_C.coords[order(MSAPn_C.coords$MSAPn_C.lat),])
MSAPn_C.coords <- data.frame(row.names=c(1:25),MSAPn_C.coords_sorted); MSAPn_C.coords
# attributes
MSAPn_C.matrix <- as.matrix(MSAPn_C.dist)
MSAPn_C.attr <- list(sprintf("%02d",1:25),
                     sprintf("%02d",1:25))
attr(MSAPn_C.matrix,"dimnames") <- MSAPn_C.attr; attr(MSAPn_C.matrix,"dimnames")
MSAPn_C.matrix
# memgene
MSAPn_C.memgene <- mgQuick(genD=MSAPn_C.matrix,
                           coords=MSAPn_C.coords,
                           forwardAlpha=0.05,
                           longlat=T,
                           forwardPerm=1000,
                           finalPerm=1000,
                           doPlot=2,
                           verbose=T); MSAPn_C.memgene
MSAPn_C.memgene$memSelected
MSAPn_C.memgene$error

#' # Plots
#' <a href="#top">Back to top</a>
#+ project_memgene_plots
########### plots ............................... ####
#' ## Population maps
#+ project_memgene_pop_maps
########### Population map ####
# prepare data
global <- map_data("world") # extract world map for plotting
SC.coords <- data.frame(Population=c(1:25),
                        Latitude=AFLP_C.coords$AFLP_C.lat,
                        Longitude=AFLP_C.coords$AFLP_C.lon); tibble(SC.coords)
# map
set.seed(124)
SC_map <- ggplot() +
  geom_polygon(data=global,
               aes(x=long,
                   y=lat,
                   group=group),
               fill="transparent",
               color="gray60") +
  coord_fixed(1.3,
              xlim=c(5,16),
              ylim=c(45,57)) +
  theme_bw() +
  labs(y=expression(paste("Latitude [",degree*N,']')),
       x=expression(paste("Longitude [",degree*E,']')),
       title=" \nSolidago canadensis") +
  theme(panel.background=element_rect(fill="transparent",
                                      color=NA),
        plot.background=element_rect(fill="transparent",
                                     colour=NA),
        panel.grid=element_blank(),
        plot.title=element_text(face="italic"),
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=16),
        axis.text.x=element_text(size=12,
                                 color="gray10"),
        axis.text.y=element_text(size=12,
                                 color="gray10")) +
  geom_point(data=SC.coords,
             aes(x=Longitude,
                 y=Latitude),
             color="white",
             fill="gray60",
             shape=21,
             size=3) +
  geom_text_repel(data=SC.coords,
                  aes(x=Longitude,
                      y=Latitude,
                      label=row.names(SC.coords)),
                  segment.color="gray60",
                  size=4,
                  nudge_x=18,
                  direction="y") +
  north(data=NULL,
        x.min=4,
        x.max=14,
        y.min=55.5,
        y.max=61,
        "bottomleft",
        scale=0.3,
        symbol=3) +
  scale_bar(lon=8,
            lat=45.3,
            distance_lon=100,
            distance_lat=15,
            distance_legend=-30,
            legend_colour="gray40",
            legend_size=2.5,
            rec2_fill="gray40",
            rec_colour="gray40",
            rec2_colour="gray40",
            dist_unit="km",
            orientation=F); SC_map

#' ## MEM Maps
#' <a href="#top">Back to top</a>
#+ project_memgene_mem_maps
########### MEMGENE maps ####
# map data
memdata <- data.frame(AFLP_C.memgene$memgene[,1:3])
memdata$longitude <- AFLP_C.coords$AFLP_C.lon
memdata$latitude <- AFLP_C.coords$AFLP_C.lat
# melt to long format
memdata_long_maps <- melt(memdata,
                          id.vars=c("longitude","latitude"))
colnames(memdata_long_maps)[3] <- c("MEMGENE")
tibble(memdata_long_maps)
# new facet labels
memgene_labs <- c("MEMGENE1","MEMGENE2","MEMGENE3")
names(memgene_labs) <- levels(memdata_long_maps$MEMGENE); memgene_labs
# percent of explained genetic variation by each MEMGENE
lab_text <- data.frame(
  label=c("Explained\nvariation:\n48%","Explained\nvariation:\n29%",
            "Explained\nvariation:\n23%"),
  MEMGENE=c("MEMGENE1","MEMGENE2","MEMGENE3"),
  x=c(5,5,5),
  y=c(57,57,57)); lab_text
# plot memgene using facets
AFLP_C.memgene_plot <- ggplot() +
  geom_polygon(data=global,
               aes(x=long,
                   y=lat,
                   group=group),
               fill="transparent",
               color="gray20") +
  coord_fixed(1.3,
              xlim=c(5,16),
              ylim=c(45,57)) +
  theme_bw() +
  labs(y="\n",
       x=expression(paste("Longitude [",degree*E,']')),
       title="") +
  theme(plot.margin=grid::unit(c(0,0,0,0),"mm"),
        plot.title=element_text(face="italic"),
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=16),
        axis.text.x=element_text(size=12,
                                 color="gray10"),
        axis.text.y=element_text(size=12,
                                 color="gray10"),
        legend.position="none") +
  geom_text(data=lab_text,mapping=aes(x=x,
                                       y=y,
                                       hjust=0,
                                       vjust=1,
                                       label=label)) +
  geom_point(data=memdata_long_maps,
             mapping=aes(x=longitude,
                         y=latitude,
                         size=value,
                         alpha=0.5,
                         fill=value<0),
             color='black',
             shape=21) +
  scale_fill_manual(name='value<0',
                    values=setNames(c('gainsboro','black'),c(T,F))) +
  facet_grid(.~MEMGENE,
             labeller=labeller(MEMGENE=memgene_labs)); AFLP_C.memgene_plot

#' ## Moran's I Correlogram
#' <a href="#top">Back to top</a>
#+ project_memgene_correlog
########### correlogram ####
# melt data
memdata_long <- melt(memdata,
                     na.rm=F,
                     id.vars=c("latitude","longitude"))
memdata_long$population <- rep(c(1:25),3)
str(memdata_long); memdata_long
# correlogram
set.seed(123)
AFLP_C.correlog <- ggplot(memdata_long,
                          aes(x=latitude,
                              y=value,
                              group=variable,
                              fill=value<0)) +
  geom_point(size=3,
             shape=21) +
  geom_text_repel(size=3,
                  label=memdata_long$population,
                  max.overlaps=12) +
  scale_fill_manual(name='value<0',
                    values=setNames(c('gainsboro','black'),c(T,F))) +
  geom_line()+
  theme_bw()+
  theme(legend.position="none",
        strip.background=element_blank(),
        panel.background=element_rect(fill="transparent",
                                      color=NA),
        plot.background=element_rect(fill="transparent",
                                     color=NA),
        # strip.text=element_blank(),
        axis.text.x=element_text(size=12,
                                 color="gray10"),
        axis.text.y=element_text(size=12,
                                 color="gray10"),
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=16))+
  labs(y="MEMGENE scores",
       x=expression(paste("Latitude [",degree*N,']')),
       title="")+
  facet_grid(cols=vars(variable),
             scales="free")+
  geom_hline(yintercept=0,
             linetype=2); AFLP_C.correlog

#' ## Figure 1B
#' <a href="#top">Back to top</a>
#+ project_figure1B_ibd
########### Figure 1B ####
# population-wise pairwise genetic distance (unbiased Nei's distance)
AFLP_C.dist 
# geographic distance
# create a distance matrix  (computed in metres)
# IMPORTANT: first column MUST be longitude (warning if lon/lat reversed!)
# distVincentyEllipsoid algorithm assuming WGS86 projection
AFLP_C.geodist <- distm(AFLP_C.coords,
                        fun=distVincentyEllipsoid)
# transform to kilometres
AFLP_C.geodist <- apply(AFLP_C.geodist,
                        c(1,2),
                        FUN=(function(i) i/1000)); AFLP_C.geodist
# make column and row names for the distance matrix
colnames(AFLP_C.geodist) <- paste0(1:25)
rownames(AFLP_C.geodist) <- paste0(1:25)
AFLP_C.geodist <- as.dist(AFLP_C.geodist); class(AFLP_C.geodist)
# IBD
AFLP_C.IBD <- as.data.frame(cbind(c(AFLP_C.dist),
                                  c(AFLP_C.geodist))); AFLP_C.IBD
names(AFLP_C.IBD) <- c("Fst","Dist")
AFLP_C.IBD$logDist <- log(1+AFLP_C.IBD$Dist)
AFLP_C.IBD$IBD <- AFLP_C.IBD$Fst/(1-AFLP_C.IBD$Fst); AFLP_C.IBD
# IBD Mantel test
set.seed(123)
AFLP_C.IBDmantel <- mantel.rtest(AFLP_C.dist,
                                 AFLP_C.geodist,
                                 nrepet=1000); AFLP_C.IBDmantel
# IBD ggplot
AFLP_C.IBDplot <- ggplot(AFLP_C.IBD,
                         aes(x=logDist,
                             y=IBD)) +
  geom_point(shape=20,
             size=4,
             alpha=0.3,
             color="gray50",
             fill="gray50") +
  scale_y_continuous(breaks=c(0,0.02,0.04,0.06,0.08,0.1,0.12)) +
  theme_cowplot() +
  theme(panel.border=element_rect(colour="black",
                                  fill=NA,
                                  size=1),
        plot.margin=unit(c(0.5,0.5,0.2,0.5),"cm")) +
  labs(x="Distance (log)",
       y=bquote("["*italic(F[ST])~"/ ("*1-italic(F[ST]*")]"))) +
  annotate("text",
           x=1,
           y=0.1,
           hjust=0,
           size=4.5,
           label="italic(r)[M] == 0.080~~(n.s.)",
           parse=T); AFLP_C.IBDplot
# save as png
ggsave(AFLP_C.IBDplot,
       file="./data/Figure1B_Eckert_et_al_2022_IBD.png",
       dpi=300,
       width=5,
       height=3)
# save as tiff
ggsave(AFLP_C.IBDplot,
       file="./data/Figure1B_Eckert_et_al_2022_IBD.TIFF",
       dpi=300,
       width=5,
       height=3,
       device=grDevices::tiff)

#' ## Figure S2
#' <a href="#top">Back to top</a>
#+ project_figureS2_memgene
########### Figure S2 ####
memgene_combi <- plot_grid(SC_map,
                           AFLP_C.correlog,
                           ncol=2,
                           nrow=1,
                           rel_widths=c(0.8,1),
                           label_size=20,
                           labels=c("A","B")) +
  theme(plot.margin=unit(c(1,1,1,1),"cm"),
        panel.background=element_rect(fill="transparent",
                                      color=NA),
        plot.background=element_rect(fill="transparent",
                                     color=NA)); memgene_combi
# save as png
ggsave(memgene_combi,
       file="./data/FigureS2_Eckert_et_al_2022_MEMGENE_AFLP_correlog.png",
       dpi=300,
       width=9,
       height=6)
# save as tiff
ggsave(memgene_combi,
       file="./data/FigureS2_Eckert_et_al_2022_MEMGENE_AFLP_correlog.TIFF",
       dpi=300,
       width=9,
       height=6,
       device=grDevices::tiff)
# and save memgenes as text file
write.table(memdata,
            file="./data/Data_Eckert_et_al_2022_MEMGENE_AFLP.txt",
            sep="\t",
            row.names=F)

#' ## Figure 1C
#' <a href="#top">Back to top</a>
#+ project_figure1C_memgene
########### Figure 1C ####
# labeller
labeller_MEMGENE <- c(
  MEMGENE1="MEMGENE1 (48%)",
  MEMGENE2="MEMGENE2 (29%)",
  MEMGENE3="MEMGENE3 (23%)"); labeller_MEMGENE
# MEMGENE1
AFLP_C.memgene1_plot <- ggplot() +
  geom_polygon(data=global,
               aes(x=long,
                   y=lat,
                   group=group),
               fill="transparent",
               color="gray20") +
  coord_fixed(1.3,
              xlim=c(6.3,14.7),
              ylim=c(46,55)) +
  theme_cowplot() +
  labs(y="",
       x="",
       title="") +
  theme(panel.border=element_rect(color="black",
                                  size=0.8),
        strip.text=element_text(size=15),
        strip.background=element_rect(color="transparent",
                                      fill="transparent"),
        plot.title=element_text(face="italic"),
        axis.line=element_line(color="transparent"),
        axis.title.x=element_text(size=15,
                                  color="transparent"),
        axis.title.y=element_text(size=16),
        axis.text.x=element_text(size=12,
                                 color="transparent"),
        axis.text.y=element_text(size=12,
                                 color="gray10"),
        axis.ticks.x=element_line(color="transparent"),
        legend.position="none") +
  geom_point(data=memdata_long_maps[memdata_long_maps$MEMGENE=="MEMGENE1",],
             aes(x=longitude,
                 y=latitude,
                 size=value,
                 alpha=0.5,
                 fill=value<0),
             color='black',
             shape=21) +
  facet_grid(cols=vars(MEMGENE),
             labeller=labeller(MEMGENE=labeller_MEMGENE))+
  scale_fill_manual(name='value<0',
                    values=setNames(c('gainsboro','black'),c(T,F))); AFLP_C.memgene1_plot
# save as png
ggsave(AFLP_C.memgene1_plot,
       file="./data/Figure1C_Eckert_et_al_2022_MEMGENE_AFLP_memgene1.png",
       dpi=300,width=3,height=4)
# save as tiff
ggsave(AFLP_C.memgene1_plot,
       file="./data/Figure1C_Eckert_et_al_2022_MEMGENE_AFLP_memgene1.TIFF",
       dpi=300,width=3,height=4,
       device=grDevices::tiff)

# MEMGENE2
AFLP_C.memgene2_plot <- ggplot() +
  geom_polygon(data=global,
               aes(x=long,
                   y=lat,
                   group=group),
               fill="transparent",
               color="gray20") +
  coord_fixed(1.3,
              xlim=c(6.3,14.7),
              ylim=c(46,55)) +
  facet_grid(cols=vars(MEMGENE),
             labeller=labeller(MEMGENE=labeller_MEMGENE))+
  theme_cowplot() +
  labs(y=expression(paste("Latitude [",degree*N,']'),"\n"),
       x="",
       title="") +
  theme(panel.border=element_rect(color="black",
                                  size=0.8),
        strip.text=element_text(size=15),
        strip.background=element_rect(color="transparent",
                                      fill="transparent"),
        plot.title=element_text(face="italic"),
        axis.line=element_line(color="transparent"),
        axis.title.x=element_text(size=15,
                                  color="transparent"),
        axis.title.y=element_text(size=17),
        axis.text.x=element_text(size=12,
                                 color="transparent"),
        axis.text.y=element_text(size=12,
                                 color="gray10"),
        axis.ticks.x=element_line(color="transparent"),
        legend.position="none") +
  geom_text(data=lab_text[2,],
            mapping=aes(x=x,
                        y=y,
                        hjust=0,
                        vjust=1,
                        label=label)) +
  geom_point(data=memdata_long_maps[memdata_long_maps$MEMGENE=="MEMGENE2",],
             aes(x=longitude,
                 y=latitude,
                 size=value,
                 alpha=0.5,
                 fill=value<0),
             color='black',
             shape=21) +
  scale_fill_manual(name='value<0',
                    values=setNames(c('gainsboro','black'),c(T,F))); AFLP_C.memgene2_plot
# save as png
ggsave(AFLP_C.memgene2_plot,
       file="./data/Figure1C_Eckert_et_al_2022_MEMGENE_AFLP_memgene2.png",
       dpi=300,
       width=3,
       height=4)
# save as tiff
ggsave(AFLP_C.memgene2_plot,
       file="./data/Figure1C_Eckert_et_al_2022_MEMGENE_AFLP_memgene2.TIFF",
       dpi=300,
       width=3,
       height=4,
       device=grDevices::tiff)

# MEMGENE3
AFLP_C.memgene3_plot <- ggplot() +
  geom_polygon(data=global,
               aes(x=long,
                   y=lat,
                   group=group),
               fill="transparent",
               color="gray20") +
  coord_fixed(1.3,xlim=c(6.3,14.7),
              ylim=c(46,55)) +
  facet_grid(cols=vars(MEMGENE),
             labeller=labeller(MEMGENE=labeller_MEMGENE))+
  theme_cowplot() +
  labs(y="",
       x=expression(paste("Longitude [",degree*E,']')),
       title="") +
  theme(panel.border=element_rect(color="black",
                                  size=0.8),
        strip.text=element_text(size=15),
        strip.background=element_rect(color="transparent",
                                      fill="transparent"),
        plot.title=element_text(face="italic"),
        axis.line=element_line(color="transparent"),
        axis.title.x=element_text(size=16),
        axis.title.y=element_text(size=16),
        axis.text.x=element_text(size=12,
                                 color="gray10"),
        axis.text.y=element_text(size=12,
                                 color="gray10"),
        legend.position="none") +
  geom_text(data=lab_text[3,],
            mapping=aes(x=x,
                        y=y,
                        hjust=0,
                        vjust=1,
                        label=label)) +
  geom_point(data=memdata_long_maps[memdata_long_maps$MEMGENE=="MEMGENE3",],
             aes(x=longitude,
                 y=latitude,
                 size=value,
                 alpha=0.5,
                 fill=value<0),
             color='black',
             shape=21) +
  scale_fill_manual(name='value<0',
                    values=setNames(c('gainsboro','black'),c(T,F))); AFLP_C.memgene3_plot
# save as png
ggsave(AFLP_C.memgene3_plot,
       file="./data/Figure1C_Eckert_et_al_2022_MEMGENE_AFLP_memgene3.png",
       dpi=300,
       width=3,
       height=4)
# save as tiff
ggsave(AFLP_C.memgene3_plot,
       file="./data/Figure1C_Eckert_et_al_2022_MEMGENE_AFLP_memgene3.TIFF",
       dpi=300,
       width=3,
       height=4,
       device=grDevices::tiff)

#' ## Figure 1A
#' <a href="#top">Back to top</a>
#+ project_figure1A_STRUCTURE
########### Figure 1A ####
# prepare data
global <- map_data("world") # extract world map for plotting
SC.coords <- data.frame(Population=c(1:25),
                        Latitude=AFLP_C.coords$AFLP_C.lat,
                        Longitude=AFLP_C.coords$AFLP_C.lon); tibble(SC.coords)
# load structure cluster data
piedata <- read.table("./data/STRUCTURE_AFLP_k2.txt",
                      header=T); tibble(piedata)
# aggregate mean per population
piedata_agg <- aggregate(.~pop,
                         piedata[,-2],
                         mean)
piedata_agg$pop <- as.factor(piedata_agg$pop)
colnames(piedata_agg) <- c("pop","A","B","long","lat")
str(piedata_agg)
piedata_agg$repel <- c(rep(c(0.5,-0.5),12),1); tibble(piedata_agg)
# re-order columns for annotation function (lon,lat,A,B,radius)
piedata_agg$radius <- 0.15
names(piedata_agg)[4] <- "lon_original"
piedata_agg$lon <- piedata_agg$lon+piedata_agg$repel
piedata_agg <- piedata_agg[,c(4,8,5,2,3,7,1,6)]
tibble(piedata_agg)
# plot map with pie charts
set.seed(123)
pie_map <-ggplot() +
  geom_polygon(data=global,
               aes(x=long,
                   y=lat,
                   group=group),
               fill="transparent",
               color="gray60") +
  coord_quickmap(xlim=c(6.3,14.7),
                 ylim=c(46,55)) +
  theme_bw() +
  labs(y=expression(paste("Latitude [",degree*N,']')),
       x=expression(paste("Longitude [",degree*E,']'))) +
  theme(legend.position="none",
        panel.grid=element_blank(),
        plot.title=element_text(face="italic"),
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=16),
        axis.text.x=element_text(size=12,
                                 color="gray10"),
        axis.text.y=element_text(size=12,
                                 color="gray10")) +
  geom_point(data=SC.coords,
             aes(x=Longitude,
                 y=Latitude),
             color="white",
             fill="black",
             shape=21,
             size=3) +
  geom_text_repel(data=SC.coords,
                  aes(x=Longitude,
                      y=Latitude,
                      label=row.names(SC.coords)),
                  segment.color="gray80",
                  size=4,
                  nudge_x=18,
                  direction="y") +
  north(data=NULL,
        x.min=6.3,
        x.max=10,
        y.min=54,
        y.max=58,
        "bottomleft",
        scale=0.3,
        symbol=3) +
  scale_bar(lon=9.7,
            lat=45.9,
            distance_lon=100,
            distance_lat=15,
            distance_legend=-15,
            legend_colour="gray20",
            legend_size=2.5,
            rec2_fill="gray20",
            rec_colour="gray20",
            rec2_colour="gray20",
            dist_unit="km",
            orientation=F); pie_map
# annotate pie data (otherwise they will be egg-shaped)
pie.list <- piedata_agg[,c(2:6)] %>% 
  tidyr::gather(type,value,-lon,-lat,-radius) %>%
  tidyr::nest(type,value) %>%
  # make a pie chart from each row, & convert to grob
  mutate(pie.grob=purrr::map(data,
                             function(d) ggplotGrob(ggplot(d,
                                                           aes(x=1,
                                                               y=value,
                                                               fill=type)) +
                                                      geom_col(color="black",
                                                               alpha=0.7,
                                                               fill=c("steelblue4","red1"),
                                                               show.legend=F) +
                                                        coord_polar(theta="y") +
                                                        theme_void()))) %>%
  # convert each grob to an annotation_custom layer
  rowwise() %>%
  mutate(radius=radius*4) %>%
  mutate(subgrob=list(annotation_custom(grob=pie.grob,
                                          xmin=lon-radius,xmax=lon+radius,
                                          ymin=lat-radius,ymax=lat+radius)))
pie.list
# add annotated pies to map
structured_pies <- pie_map +
  # Hides some tiles of the corresponding color scale BEHIND the pie charts, in order to create a legend for them (optional)
  geom_tile(data=piedata_agg[,c(2:6)] %>%
              tidyr::gather(type,value,-lon,-lat,-radius),
            aes(x=lon,
                y=lat,
                fill=type),
            alpha=0.3,
            color="black",
            width=0.01,
            height=0.01,
            inherit.aes=F) +
  labs(title=expression(paste(italic("Solidago canadensis")~"("*italic(k)~"= 2)"))) +
  pie.list$subgrob; structured_pies
# save as png
ggsave(structured_pies,
       file="./data/Figure1B_Eckert_et_al_2022_STRUCTURE_AFLPMSAP_pie.png",
       dpi=300,width=4.5,height=6)
# save as tiff
ggsave(structured_pies,
       file="./data/Figure1B_Eckert_et_al_2022_STRUCTURE_AFLPMSAP_pie.TIFF",
       dpi=300,width=4.5,height=6,
       device=grDevices::tiff)

#' # Session info
#' <a href="#top">Back to top</a>
#+ Session.info
sessionInfo()
#' <a href="#top">Back to top</a>
######## Session info .................. ####