#' ---
#' title: <center><b>Markdown document from&colon;</b><br>Traces of Genetic but Not Epigenetic Adaptation in the Invasive Goldenrod _Solidago canadensis_ Despite the Absence of Population Structure</center>
#' pagetitle: RMarkdown document from:&nbsp;Eckert&nbsp;et&nbsp;al.&nbsp;(2022)
#' subtitle: <center>doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.3389/fevo.2022.856453">10.3389/fevo.2022.856453</a></center>
#' author: <center>Eckert, S., Herden, J., Stift, M., Durka, W., van Kleunen, M., & Joshi, J.</center>
#' date: <center>`r Sys.Date()`</center>
#' abstract: <p align="justify">This RMarkdown script belongs
#'   to a series of scripts generated by Silvia Eckert as part of
#'   the statistical analysis for the above-mentioned manuscript.
#'   The data underlying the applied R code can be found in the ZENODO
#'   repository and contains genetic (AFLP) and epigenetic (MSAP) markers
#'   from offspring of 25 _Solidago canadensis_ populations sampled along a
#'   latitudinal gradient in Central Europe. This particular RMarkdown script
#'   is part 03/06 and applies the LEA admixture coefficient estimation on 
#'   the MSAP dataset. <b>Please cite this
#'   script as follows:</b></p><br><p>Eckert, S., Herden, J.,
#'   Stift, M., Durka, W., van Kleunen, M., & Joshi, J. (2022). Data From&colon;
#'   Traces of Genetic but Not Epigenetic Adaptation in the Invasive
#'   Goldenrod _Solidago canadensis_ Despite the Absence of Population
#'   Structure. _Zenodo_. doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.5281/zenodo.6388135">10.5281/zenodo.6388135</a></center></p>
#' geometry: margin=2cm
#' output:
#'   html_document:
#'      code_folding: show
#'      keep_md: FALSE
#'      theme: flatly
#'      highlight: textmate
#'      df_print: paged
#'      toc: true
#'      toc_float: true
#' ---
#' 

#'
#'```{r setup, include = FALSE}
#'knitr::opts_chunk$set(eval=FALSE, cache=FALSE, warning=FALSE)
#'```

#' # Packages
#' <a href="#top">Back to top</a>
#+ project_packages, results='hide', message=FALSE, warning=FALSE
########### packages ...................... ####
# install.packages("name_of_package") # install necessary packages
# install knitr to save this script as html output using RStudio with Ctrl+Shift+K (Windows & Linux) or Command+Shift+K (macOS)
# install.packages("knitr") 
# getwd() # get current working directory
# setwd() # set working directory
# create folder for datasets to be stored to get this RMarkdown script running
dir.create("./data",
           showWarnings=F)

#' # Load data
#' <a href="#top">Back to top</a>
#+ project_load.data
########### load data ....................... ####
source("RMarkdown_Eckert_et_al_2022_LEA_01.R")

#' # Population structure
#' <a href="#top">Back to top</a>
#+ project_LEA
######## LEA ................................ ####
# Estimation of individual ancestry coefficients using R package LEA
#' ## MSAP-m
#+ project_LEA.MSAP-m
######## MSAP-m ......................... ####
#' ### SNMF
#+ project_LEA.MSAP-m.snmf
######## SNMF ####
# convert struct files to geno and lfmm
# ploidy = 1, because dominant data (one column per marker)
struct2geno(input.file="./data_LEA/Input_MSAPm_C.struct",
            ploidy=1,
            FORMAT=1,
            extra.row=1,
            extra.column=2)
# rename
#file.rename(from="./data_LEA/Input_MSAPm_C.struct.geno",
#            to="./data_LEA/Input_MSAPm_C.geno")
#file.rename(from="./data_LEA/Input_MSAPm_C.struct.lfmm",
#            to="./data_LEA/Input_MSAPm_C.lfmm")
# evaluate population structure
set.seed(123)
MSAPm_C.pca=pca("./data_LEA/Input_MSAPm_C.lfmm",
                   center=T,
                   scale=T); plot(MSAPm_C.pca)
## run LEA
# takes up to 40 minutes depending on the number of CPU cores used
MSAPm_C.project=NULL # start new project
MSAPm_C.project=snmf("./data_LEA/Input_MSAPm_C.geno",
                        K=1:11,
                        seed=123,
                        CPU=3,
                        ploidy=2,
                        entropy=T,
                        repetitions=20,
                        iterations=100000,
                        project="new")
# re-load project
# MSAPm_C.project = load.snmfProject("./data_LEA/MSAPm_C.snmfProject")

#' ### Cross validation
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAP-m.snmf_crossVal
######## cross validation ####
MSAPm_C.snmf_data <- data.frame()
for (i in 1:length(MSAPm_C.project@runs)){MSAPm_C.snmf_data <- rbind(MSAPm_C.snmf_data,
                                                 c(MSAPm_C.project@runs[[i]]@K,
                                                   MSAPm_C.project@runs[[i]]@run,
                                                   MSAPm_C.project@runs[[i]]@crossEntropy))}
colnames(MSAPm_C.snmf_data) <- c("K","run","crossEntropy")
MSAPm_C.snmf_data$K <- as.factor(MSAPm_C.snmf_data$K)
tibble(MSAPm_C.snmf_data)
MSAPm_C.snmf_data_minCV <- aggregate(.~K,
                                      MSAPm_C.snmf_data,
                                      min); MSAPm_C.snmf_data_minCV
# plot
MSAPm_crossVal <- ggplot(data=MSAPm_C.snmf_data_minCV,
                          aes(x=K,
                              y=crossEntropy,
                              group=1)) +
  geom_line(alpha=0.3) +
  geom_point(shape=21,
             fill="gray60",
             size=4) +
  theme_bw() +
  labs(x=expression(paste("Number of ancestral populations"~italic("(K)"))),
       y="Cross entropy\n") +
  geom_vline(xintercept=2,
             linetype=2,
             col="gray60") +
  annotate(geom="text",
           x=3,
           y=0.475,
           hjust=0,
           vjust=1,
           label=expression(paste(italic(n)[repetitions]~" = 20"))) +
  annotate(geom="text",
           x=3,
           y=0.471,
           hjust=0,
           vjust=1,
           label=expression(paste(italic(n)[iterations]~" = 100,000"))) +
  annotate(geom="text",
           x=3,
           y=0.467,
           hjust=0,
           vjust=1,
           label=expression(paste(italic(K)["lowest cross entropy"]~" = 2")))+
  theme(panel.grid.major=element_line(color="gray97"),
        plot.margin=unit(c(1,0.5,1,0.5),"cm"),
        axis.title.x=element_text(size=12),
        axis.text.x=element_text(size=12),
        axis.title.y=element_text(size=12),
        axis.text.y=element_text(size=12)); MSAPm_crossVal

#' ### Population structure
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAP-m.snmf.stacked_barplot
######## population structure ####
# STRUCTURE-like barplot for first look
MSAPm_C.best = which.min(cross.entropy(MSAPm_C.project,K=2))
MSAPm_C.q = Q(MSAPm_C.project,K =2,run=MSAPm_C.best)
# save Q matrix
MSAPm_C.qmatrix <- tibble(data.frame(uniqueID=row.names(strata(MSAPm_C.genind)),
                                      population_ID=strata(MSAPm_C.genind)[7],
                                      MSAPm_C.q)); MSAPm_C.qmatrix
# prepare data
MSAPm_C.stacked <- reshape2::melt(MSAPm_C.qmatrix); tibble(MSAPm_C.stacked)
colnames(MSAPm_C.stacked)[3:4] <- c("cluster","proportion")
MSAPm_C.stacked$cluster <- as.factor(as.numeric(gsub("V","",
                                                      MSAPm_C.stacked$cluster)))
MSAPm_C.stacked$treatment <- "CON"
MSAPm_C.stacked$populationID <- factor(MSAPm_C.stacked$populationID,
                                        levels=as.character(1:25)); tibble(MSAPm_C.stacked)
# labeller
treatment_labeller <- c(
  `CON`="Control",
  `ZEB`="Zebularine")
# plot
MSAPm_C.snmf.plot <- ggplot(MSAPm_C.stacked,
                             aes(x=uniqueID,
                                 y=proportion,
                                 fill=cluster)) +
  geom_bar(position="fill",
           stat="identity",
           width=1.2) +
  scale_y_continuous(labels=percent_format(),
                     breaks=c(0.25,0.75),
                     expand=c(0,0)) + 
  facet_grid(treatment ~ populationID,
             scales="free_x",space="free_x",
             shrink=T,
             labeller=labeller(treatment=treatment_labeller)) +
  labs(title="MSAP-m",
       x=expression('Latitude [49.63 - 54.11 '*degree*N*']'),
       y=expression("Probability ("*italic(K)~"= 2)")) +
  theme_cowplot() +
  theme(plot.margin=unit(c(1,1,0.5,1),"lines"),
        plot.title=element_text(size=20),
        panel.spacing=unit(.1,"line"),
        strip.text=element_text(size=12),
        strip.background=element_rect(linetype="solid",
                                        fill="transparent",
                                        color="black",
                                        size=0.5),
        legend.position="none",
        axis.title.y=element_text(size=12),
        axis.line.x=element_blank(),
        axis.line.y=element_blank(),
        axis.title.x=element_text(size=12),
        axis.text.y=element_text(size=12),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  scale_fill_manual(values=c("black","#CC79A7")) +
  scale_x_discrete(breaks=c(0.1,5),
                   labels=c("a","b")) +
  coord_cartesian(clip="off"); MSAPm_C.snmf.plot

#' ### Cluster variation
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAP-m.snmf.cluster_Var
######## cluster variation ####
MSAPm_C.qmatrix_long <- reshape2::melt(MSAPm_C.qmatrix,
                                        by="populationID")
colnames(MSAPm_C.qmatrix_long)[3:4] <- c("cluster","proportion")
tibble(MSAPm_C.qmatrix_long)
# aggreagate population means
MSAPm_C.qmatrix_agg <- aggregate(MSAPm_C.qmatrix_long$proportion,
                                  by=list(MSAPm_C.qmatrix_long$populationID,
                                          MSAPm_C.qmatrix_long$cluster),
                                  FUN=mean)  # aggregate
colnames(MSAPm_C.qmatrix_agg) <- c("populationID","cluster","proportion_avg")
MSAPm_C.qmatrix_agg$populationID <- factor(MSAPm_C.qmatrix_agg$populationID,
                                            levels=as.character(1:25))
# create labeller
clust_labeller <- c(
  `V1`="Cluster 1",
  `V2`="Cluster 2")
# plot
MSAPm_clusterVar <- ggplot(MSAPm_C.qmatrix_agg,
                            aes(x=populationID,
                                y=proportion_avg,
                                group=cluster,
                                fill=cluster)) +
  geom_area(aes(x=populationID,
                y=proportion_avg)) +
  facet_grid(.~cluster,
             labeller=labeller(cluster=clust_labeller)) +
  coord_flip()+
  labs(x="Population",
       y=expression(paste("Average proportion of"~italic(K)*"cluster assignment per population"))) +
  scale_fill_manual(values=c("black","#CC79A7")) +
  theme_bw()+
  theme(axis.text.x=element_text(angle=65,
                                   vjust=0.6,
                                   size=12),
        legend.position="none",
        plot.margin=unit(c(1,0.5,0.5,1),"cm"),
        axis.title.x=element_text(size=12),
        axis.title.y=element_text(size=12),
        axis.text.y=element_text(size=12)); MSAPm_clusterVar

#' ### Figure S11
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAP-m.snmf_figureS11
######## Figure S11 ####
MSAPm_SNMFcombi <- ggarrange(MSAPm_C.snmf.plot,
                              ggarrange(MSAPm_crossVal,
                                        MSAPm_clusterVar,
                                        ncol=2,
                                        font.label=list(size=20),
                                        labels=c("B","C")),
                              nrow=2,
                              font.label=list(size=20),
                              labels="A") +
  theme(plot.margin=unit(c(1,1,1,1),"cm")); MSAPm_SNMFcombi
# save as png
ggsave(MSAPm_SNMFcombi,
       file="./data/FigureS11_Eckert_et_al_2022_LEA_snmf_MSAPm.png",
       width=15,
       height=10,
       dpi=300)
# save as tiff
ggsave(MSAPm_SNMFcombi,
       file="./data/FigureS11_Eckert_et_al_2022_LEA_snmf_MSAPm.TIFF",
       dpi=300,
       width=15,
       height=10,
       device=grDevices::tiff)

#' ## MSAP-n
#' <a href="#top">Back to top</a> 
#+ project_LEA.MSAPn
######## MSAP-n ......................... ####
#' ### SNMF
#+ project_LEA.MSAPn.snmf
######## SNMF ####
# convert struct files to geno and lfmm
# ploidy = 1, because dominant data (one column per marker)
struct2geno(input.file="./data_LEA/Input_MSAPu_C.struct",
            ploidy=1,
            FORMAT=1,
            extra.row=1,
            extra.column=2)
# rename
file.rename(from="./data_LEA/Input_MSAPu_C.struct.geno",
            to="./data_LEA/Input_MSAPu_C.geno")
file.rename(from="./data_LEA/Input_MSAPu_C.struct.lfmm",
            to="./data_LEA/Input_MSAPu_C.lfmm")
# evaluate population structure
set.seed(123)
MSAPn_C.pca = pca("./data_LEA/Input_MSAPu_C.lfmm",
                   center=T,
                   scale=T); plot(MSAPn_C.pca)
# run LEA
# takes up to 40 minutes depending on the number of CPU cores used
MSAPn_C.project = NULL # start new project
MSAPn_C.project = snmf("./data_LEA/Input_MSAPu_C.geno",
                        K=1:11,
                        seed=123,
                        CPU=3,
                        ploidy=2,
                        entropy=T,
                        repetitions=20,
                        iterations=100000,
                        project="new")
# re-load project
# MSAPn_C.project = load.snmfProject("RawData_LEA/MSAPu_C.snmfProject")

#' ### Cross validation
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPn.snmf_crossVal
######## cross validation ####
MSAPn_C.snmf_data <- data.frame()
for (i in 1:length(MSAPm_C.project@runs)) {MSAPn_C.snmf_data <- rbind(MSAPn_C.snmf_data,
                                                 c(MSAPn_C.project@runs[[i]]@K,
                                                   MSAPn_C.project@runs[[i]]@run,
                                                   MSAPn_C.project@runs[[i]]@crossEntropy))}
colnames(MSAPn_C.snmf_data) <- c("K","run","crossEntropy")
MSAPn_C.snmf_data$K <- as.factor(MSAPn_C.snmf_data$K)
tibble(MSAPn_C.snmf_data)
MSAPn_C.snmf_data_minCV <- aggregate(.~K,
                                      MSAPn_C.snmf_data,
                                      min); MSAPn_C.snmf_data_minCV
# plot
MSAPn_crossVal <- ggplot(data=MSAPn_C.snmf_data_minCV,
                          aes(x=K,
                              y=crossEntropy,
                              group=1)) +
  geom_line(alpha=0.3) +
  geom_point(shape=21,
             fill="gray60",
             size=4) +
  theme_bw() +
  labs(x=expression(paste("Number of ancestral populations"~italic("(K)"))),
       y="Cross entropy\n") +
  geom_vline(xintercept=3,
             linetype=2,
             col="gray60") +
  annotate(geom="text",
           x=4,
           y=0.385,
           hjust=0,
           vjust=1,
           label=expression(paste(italic(n)[repetitions]~" = 20"))) +
  annotate(geom="text",
           x=4,
           y=0.381,
           hjust=0,
           vjust=1,
           label=expression(paste(italic(n)[iterations]~" = 100,000"))) +
  annotate(geom="text",
           x=4,
           y=0.377,
           hjust=0,
           vjust=1,
           label=expression(paste(italic(K)["lowest cross entropy"]~" = 2")))+
  theme(panel.grid.major=element_line(color="gray97"),
        plot.margin=unit(c(1,0.5,1,0.5),"cm"),
        axis.title.x=element_text(size=12),
        axis.text.x=element_text(size=12),
        axis.title.y=element_text(size=12),
        axis.text.y=element_text(size=12)); MSAPn_crossVal

#' ### Population structure
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPn.snmf.stacked_barplot
######## population structure ####
# STRUCTURE-like barplot for first look
MSAPn_C.best = which.min(cross.entropy(MSAPn_C.project,K=3))
MSAPn_C.q = Q(MSAPn_C.project,K =3,run=MSAPn_C.best)
# save Q matrix
MSAPn_C.qmatrix <- tibble(data.frame(uniqueID=row.names(strata(MSAPn_C.genind)),
                                      population_ID=strata(MSAPn_C.genind)[7],
                                      MSAPn_C.q)); MSAPn_C.qmatrix
# prepare data
MSAPn_C.stacked <- reshape2::melt(MSAPn_C.qmatrix); tibble(MSAPn_C.stacked)
colnames(MSAPn_C.stacked)[3:4] <- c("cluster","proportion")
MSAPn_C.stacked$cluster <- as.factor(as.numeric(gsub("V","",
                                          MSAPn_C.stacked$cluster)))
MSAPn_C.stacked$treatment <- "CON"
MSAPn_C.stacked$populationID <- factor(MSAPn_C.stacked$populationID,
                                        levels=as.character(1:25)); tibble(MSAPn_C.stacked)
# labeller
treatment_labeller <- c(
  `CON`="Control",
  `ZEB`="Zebularine")
# plot
MSAPn_C.snmf.plot <- ggplot(MSAPn_C.stacked,
                             aes(x=uniqueID,
                                 y=proportion,
                                 fill=cluster)) +
  geom_bar(position="fill",
           stat="identity",
           width=1.2) +
  scale_y_continuous(labels=percent_format(),
                     breaks=c(0.25,0.75),
                     expand=c(0,0)) + 
  facet_grid(treatment ~ populationID,
             scales="free_x",
             space="free_x",
             shrink=T,
             labeller=labeller(treatment=treatment_labeller)) +
  labs(title="MSAP-n",
       x=expression('Latitude [49.63 - 54.11 '*degree*N*']'),
       y=expression("Probability ("*italic(K)~"= 3)")) +
  theme_cowplot() +
  theme(plot.margin=unit(c(1,1,0.5,1),"lines"),
        plot.title=element_text(size=20),
        panel.spacing=unit(.1,"line"),
        strip.text=element_text(size=12),
        strip.background=element_rect(linetype="solid",
                                        fill="transparent",
                                        color="black",
                                        size=0.5),
        legend.position="none",
        axis.title.y=element_text(size=12),
        axis.line.x=element_blank(),
        axis.line.y=element_blank(),
        axis.title.x=element_text(size=12),
        axis.text.y=element_text(size=12),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  scale_fill_manual(values=c("black","#CC79A7","blue")) +
  scale_x_discrete(breaks=c(0.1,5),
                   labels=c("a","b")) +
  coord_cartesian(clip="off"); MSAPn_C.snmf.plot

#' ### Cluster variation
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPn.snmf.cluster_Var
######## cluster variation ####
MSAPn_C.qmatrix_long <- reshape2::melt(MSAPn_C.qmatrix,
                                        by="populationID")
colnames(MSAPn_C.qmatrix_long)[3:4] <- c("cluster","proportion")
tibble(MSAPn_C.qmatrix_long)
# aggreagate population means
MSAPn_C.qmatrix_agg <- aggregate(MSAPn_C.qmatrix_long$proportion,
                                  by=list(MSAPn_C.qmatrix_long$populationID,
                                          MSAPn_C.qmatrix_long$cluster),
                                  FUN=mean)  # aggregate
colnames(MSAPn_C.qmatrix_agg) <- c("populationID","cluster","proportion_avg")
MSAPn_C.qmatrix_agg$populationID <- factor(MSAPn_C.qmatrix_agg$populationID,
                                            levels=as.character(1:25))
# create labeller
clust_labeller <- c(
  `V1`="Cluster 1",
  `V2`="Cluster 2",
  `V3`="Cluster 3")
# plot
MSAPn_clusterVar <- ggplot(MSAPn_C.qmatrix_agg,
                            aes(x=populationID,
                                y=proportion_avg,
                                group=cluster,
                                fill=cluster)) +
  geom_area(aes(x=populationID,
                y=proportion_avg)) +
  facet_grid(.~cluster,
             labeller=labeller(cluster=clust_labeller)) +
  coord_flip() +
  labs(x="Population",
       y=expression(paste("Average proportion of"~italic(K)*"cluster assignment per population"))) +
  scale_fill_manual(values=c("black","#CC79A7","blue")) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=65,
                                   vjust=0.6,
                                   size=12),
        legend.position="none",
        plot.margin=unit(c(1,0.5,0.5,1),"cm"),
        axis.title.x=element_text(size=12),
        axis.title.y=element_text(size=12),
        axis.text.y=element_text(size=12)); MSAPn_clusterVar

#' ### Figure S12
#' <a href="#top">Back to top</a>
#+ project_LEA.MSAPn.snmf_figureS12
######## Figure S12 ####
MSAPn_SNMFcombi <- ggarrange(MSAPn_C.snmf.plot,
                              ggarrange(MSAPn_crossVal,
                                        MSAPn_clusterVar,
                                        ncol=2,
                                        font.label=list(size=20),
                                        labels=c("B","C")),
                              nrow=2,
                              font.label=list(size=20),
                              labels="A") +
  theme(plot.margin=unit(c(1,1,1,1),"cm")); MSAPn_SNMFcombi
# save as png
ggsave(MSAPn_SNMFcombi,
       file="./data/FigureS12_Eckert_et_al_2022_LEA_snmf_MSAPn.png",
       width=15,
       height=10,
       dpi=300)
# save as tiff
ggsave(MSAPn_SNMFcombi,
       file="./data/FigureS12_Eckert_et_al_2022_LEA_snmf_MSAPn.TIFF",
       dpi=300,
       width=15,
       height=10,
       device=grDevices::tiff)

#' # Session info
#' <a href="#top">Back to top</a>
#+ Session.info
######## Session info ###
sessionInfo()
#' <a href="#top">Back to top</a>
######## Session info .................. ####