#' ---
#' title: <center><b>Markdown document from&colon;</b><br>Traces of Genetic but Not Epigenetic Adaptation in the Invasive Goldenrod _Solidago canadensis_ Despite the Absence of Population Structure</center>
#' pagetitle: RMarkdown document from:&nbsp;Eckert&nbsp;et&nbsp;al.&nbsp;(2022)
#' subtitle: <center>doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.3389/fevo.2022.856453">10.3389/fevo.2022.856453</a></center>
#' author: <center>Eckert, S., Herden, J., Stift, M., Durka, W., van Kleunen, M., & Joshi, J.</center>
#' date: <center>`r Sys.Date()`</center>
#' abstract: <p align="justify">This RMarkdown script belongs
#'   to a series of scripts generated by Silvia Eckert as part of
#'   the statistical analysis for the above-mentioned manuscript.
#'   The data underlying the applied R code can be found in the ZENODO
#'   repository and contains genetic (AFLP) and epigenetic (MSAP) markers
#'   from offspring of 25 _Solidago canadensis_ populations sampled along a
#'   latitudinal gradient in Central Europe. This particular RMarkdown script
#'   creates Venn diagrams of outlier markers based on genome scans from 
#'   AFLP and MSAP datasets. <b>Please cite this
#'   script as follows:</b></p><br><p>Eckert, S., Herden, J.,
#'   Stift, M., Durka, W., van Kleunen, M., & Joshi, J. (2022). Data From&colon;
#'   Traces of Genetic but Not Epigenetic Adaptation in the Invasive
#'   Goldenrod _Solidago canadensis_ Despite the Absence of Population
#'   Structure. _Zenodo_. doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.5281/zenodo.6388135">10.5281/zenodo.6388135</a></center></p>
#' geometry: margin=2cm
#' output:
#'   html_document:
#'      code_folding: show
#'      keep_md: FALSE
#'      theme: flatly
#'      highlight: textmate
#'      df_print: paged
#'      toc: true
#'      toc_float: true
#' ---
#' 

#'
#'```{r setup, include = FALSE}
#'knitr::opts_chunk$set(eval=FALSE, cache=FALSE, warning=FALSE)
#'```

#' # Packages
#' <a href="#top">Back to top</a>
#+ project_packages, results='hide', message=FALSE, warning=FALSE
########### packages ...................... ####
# install.packages("name_of_package") # install necessary packages
# install knitr to save this script as html output using RStudio with Ctrl+Shift+K (Windows & Linux) or Command+Shift+K (macOS)
# install.packages("knitr") 
# getwd() # get current working directory
# setwd() # set working directory
# create folder for datasets to be stored to get this RMarkdown script running
dir.create("./data",
           showWarnings=F)
# add necessary libraries
library(tibble)
library(tidyverse)

#' # Load data
#' <a href="#top">Back to top</a>
#+ project_load.data
########### load data ....................... ####
# To use this script, outliers from genome-scan approaches need to be saved in .txt files
#' ## AFLP
#+ project_load.AFLP
######## AFLP ####
AFLP_bayescan_outlier <- read.table("./data/Data_BayeScan_AFLP_outliers.txt",
                                    header=T); AFLP_bayescan_outlier
AFLP_LFMM_outlier <- read.table("./data/Data_LFMM_AFLP_outliers.txt",
                                header=T); AFLP_LFMM_outlier
AFLP_bayescenv_outlier <- read.table("./data/Data_BayeScEnv_AFLP_outliers.txt",
                                     header=T); AFLP_bayescenv_outlier

#' ## MSAP-n
#' <a href="#top">Back to top</a>
#+ project_load.MSAPn
######## MSAP-n ####
MSAPn_bayescan_outlier <- read.table("./data/Data_BayeScan_MSAPn_outliers.txt",
                                      header=T); MSAPn_bayescan_outlier
MSAPn_LFMM_outlier <- read.table("./data/Data_LFMM_MSAPn_outliers.txt",
                                  header=T); MSAPn_LFMM_outlier
MSAPn_bayescenv_outlier <- read.table("./data/Data_BayeScEnv_MSAPn_outliers.txt",
                                       header=T); MSAPn_bayescenv_outlier
MSAPn_RDA_outlier <- read.table("./data/Data_RDA_MSAPn_outliers.txt",
                                 header=T); MSAPn_RDA_outlier

#' ## MSAP-m
#' <a href="#top">Back to top</a>
#+ project_load.MSAPm
######## MSAP-m ####
MSAPm_bayescan_outlier <- read.table("./data/Data_BayeScan_MSAPm_outliers.txt",
                                      header=T); MSAPm_bayescan_outlier
MSAPm_LFMM_outlier <- read.table("./data/Data_LFMM_MSAPm_outliers.txt",
                                  header=T); MSAPm_LFMM_outlier
MSAPm_bayescenv_outlier <- read.table("./data/Data_BayeScEnv_MSAPm_outliers.txt",
                                       header=T); MSAPm_bayescenv_outlier
MSAPm_RDA_outlier <- read.table("./data/Data_RDA_MSAPm_outliers.txt",
                                 header=T); MSAPm_RDA_outlier

#' # Outlier loci
#' <a href="#top">Back to top</a>
#+ project_loci.outliers
#### Outliers .........................####
# AFLP
AFLP_VennMarker <- list(BayeScan=AFLP_bayescan_outlier$ID,
                        LFMM=unique(AFLP_LFMM_outlier$ID),
                        BayeScEnv=unique(AFLP_bayescenv_outlier$ID),
                        RDA=NULL); AFLP_VennMarker
# MSAP-n
MSAPn_VennMarker <- list(BayeScan=MSAPn_bayescan_outlier$ID,
                          LFMM=unique(MSAPn_LFMM_outlier$ID),
                          BayeScEnv=unique(MSAPn_bayescenv_outlier$ID),
                          RDA=unique(MSAPn_RDA_outlier$locus)); MSAPn_VennMarker
# MSAP-m
MSAPm_VennMarker <- list(BayeScan=MSAPm_bayescan_outlier$ID,
                          LFMM=unique(MSAPm_LFMM_outlier$ID),
                          BayeScEnv=unique(MSAPm_bayescenv_outlier$ID),
                          RDA=unique(MSAPm_RDA_outlier$locus)); MSAPm_VennMarker

#' ## Climate-related intersection
#' <a href="#top">Back to top</a>
#+ project_intersection.climate
#### Climate intersection ####
# intersection of BayeScEnv and LFMM results
# AFLP
AFLP_intersection <- Reduce(intersect,
                            AFLP_VennMarker[2:3]); AFLP_intersection
# MSAP-m
MSAPm_intersection <- Reduce(intersect,
                             MSAPm_VennMarker[2:3]); MSAPm_intersection
# MSAP-n
MSAPn_intersection <- Reduce(intersect,
                             MSAPn_VennMarker[2:3]); MSAPn_intersection
# find longest intersection list
clim_int_List <- list(AFLP_intersection,
                      MSAPm_intersection,
                      MSAPn_intersection); clim_int_List
# combine list
intersection_df <- tibble(data.frame(
  AFLP=c(AFLP_intersection,
           rep(NA,
               length(unlist(clim_int_List[which.max(lengths(clim_int_List))]))-
                 length(AFLP_intersection))),
  MSAPm=c(MSAPm_intersection,
            rep(NA,
                length(unlist(clim_int_List[which.max(lengths(clim_int_List))]))-
                  length(MSAPm_intersection))),
  MSAPn=c(MSAPn_intersection,
            rep(NA,
                length(unlist(clim_int_List[which.max(lengths(clim_int_List))]))-
                  length(MSAPn_intersection))))); intersection_df
# save list
write.table(intersection_df,
            file="./data/Data_OutlierScan_Climate_intersection.txt",
            sep="\t",
            row.names=F,
            col.names=T)

#' ## Autocorrelation-related intersection
#' <a href="#top">Back to top</a>
#+ project_intersection.autocorrelation
#### Autocorr intersection ####
# intersection of BayeScEnv and LFMM results
# AFLP
AFLP_autocorr_intersection <- Reduce(intersect,
                                     AFLP_VennMarker[c(2,4)]); AFLP_autocorr_intersection
# MSAP-m
MSAPm_autocorr_intersection <- Reduce(intersect,
                                      MSAPm_VennMarker[c(2,4)]); MSAPm_autocorr_intersection
# MSAP-n
MSAPn_autocorr_intersection <- Reduce(intersect,
                                      MSAPn_VennMarker[c(2,4)]); MSAPn_autocorr_intersection
# find longest intersection list
autocorr_int_List <- list(AFLP_autocorr_intersection,
                          MSAPm_autocorr_intersection,
                          MSAPn_autocorr_intersection); autocorr_int_List
# combine list
autocorr_intersection_df <- tibble(data.frame(
  AFLP=c(AFLP_autocorr_intersection,
           rep(NA,
               length(unlist(autocorr_int_List[which.max(lengths(autocorr_int_List))]))-
                 length(AFLP_autocorr_intersection))),
  MSAPm=c(MSAPm_autocorr_intersection,
            rep(NA,
                length(unlist(autocorr_int_List[which.max(lengths(autocorr_int_List))]))-
                  length(MSAPm_autocorr_intersection))),
  MSAPn=c(MSAPn_autocorr_intersection,
            rep(NA,
                length(unlist(autocorr_int_List[which.max(lengths(autocorr_int_List))]))-
                  length(MSAPn_autocorr_intersection))))); autocorr_intersection_df
# save list
write.table(autocorr_intersection_df,
            file="./data/Data_OutlierScan_Autocorr_intersection.txt",
            sep="\t",
            row.names=F,
            col.names=T)

#' # Venn data
#' <a href="#top">Back to top</a>
#+ project_venn.data
#### Venn data ......................####
# create Venn object
# AFLP
AFLP_vennObj <- venn(AFLP_VennMarker[1:3]); AFLP_vennObj
# MSAP-n
MSAPn_vennObj <- venn(MSAPn_VennMarker); MSAPn_vennObj
# MSAP-m
MSAPm_vennObj <- venn(MSAPm_VennMarker); MSAPm_vennObj

#' ## Venn plots
#' <a href="#top">Back to top</a>
#+ project_venn.plots
#### Venn plots ####
# AFLP
AFLP_venn.plot <- plot(AFLP_vennObj,
                       edges=T,
                       lty=c(3),
                       col=c("gray40","gray40","gray40"),
                       fill=c(rep("transparent",5),
                              "gainsboro",
                              "transparent"),
                       lwd=2); AFLP_venn.plot
AFLP_venn.ggplot <- as.ggplot(AFLP_venn.plot) +
  labs(title=expression(paste(bold('AFLP')))) +
  theme(plot.title=element_text(hjust=0.5)); AFLP_venn.ggplot
# MSAP-n
MSAPn_venn.plot <- plot(MSAPn_vennObj,
                        edges=T,
                        col='gray40',
                        lty=c(3),
                        fill=c(rep("transparent",7),
                               "gainsboro",
                               "gainsboro",
                               rep("transparent",6)),
                         lwd=2); MSAPn_venn.plot
MSAPn_venn.ggplot <- as.ggplot(MSAPn_venn.plot) +
  labs(title=expression(paste(bold('MSAP-n')))) +
  theme(plot.title=element_text(hjust=0.5)); MSAPn_venn.ggplot
# MSAP-m
MSAPm_venn.plot <- plot(MSAPm_vennObj,
                        edges=T,
                        col='gray40',
                        lty=c(3),
                        fill=c(rep("transparent",7),
                               "gainsboro",
                               "gainsboro",
                               rep("transparent",6)),
                         lwd=2); MSAPm_venn.plot
MSAPm_venn.ggplot <- as.ggplot(MSAPm_venn.plot) +
  labs(title=expression(paste(bold('MSAP-m')))) +
  theme(plot.title=element_text(hjust=0.5)); MSAPm_venn.ggplot
# combine
venn_combi <- plot_grid(AFLP_venn.ggplot,
                        MSAPm_venn.ggplot,
                        MSAPn_venn.ggplot,
                        ncol=3,
                        vjust=0,
                        labels=c('A','B','C'),
                        label_size=24) +
  theme(plot.margin=unit(c(2,1,1,1),"cm")); venn_combi
# save as png
ggsave(venn_combi,
       file="./data/Figure3_Eckert_et_al_2022_VennDiagrams.png",
       dpi=300,
       width=12,
       height=5)
# save as tiff
ggsave(venn_combi,
       file="./data/Figure3_Eckert_et_al_2022_VennDiagrams.tiff",
       dpi=300,
       width=12,
       height=5,
       device=grDevices::tiff)

#' # Session info
#' <a href="#top">Back to top</a>
#+ Session.info
sessionInfo()
#' <a href="#top">Back to top</a>
######## Session info .................. ####