#' ---
#' title: <center><b>Markdown document from&colon;</b><br>Traces of Genetic but Not Epigenetic Adaptation in the Invasive Goldenrod _Solidago canadensis_ Despite the Absence of Population Structure</center>
#' pagetitle: RMarkdown document from:&nbsp;Eckert&nbsp;et&nbsp;al.&nbsp;(2022)
#' subtitle: <center>doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.3389/fevo.2022.856453">10.3389/fevo.2022.856453</a></center>
#' author: <center>Eckert, S., Herden, J., Stift, M., Durka, W., van Kleunen, M., & Joshi, J.</center>
#' date: <center>`r Sys.Date()`</center>
#' abstract: <p align="justify">This RMarkdown script belongs
#'   to a series of scripts generated by Silvia Eckert as part of
#'   the statistical analysis for the above-mentioned manuscript.
#'   The data underlying the applied R code can be found in the ZENODO
#'   repository and contains genetic (AFLP) and epigenetic (MSAP) markers
#'   from offspring of 25 _Solidago canadensis_ populations sampled along a
#'   latitudinal gradient in Central Europe. This particular RMarkdown script
#'   loads STRUCTURE run files and creates stacked barplots from Q matrices. <b>Please cite this
#'   script as follows:</b></p><br><p>Eckert, S., Herden, J.,
#'   Stift, M., Durka, W., van Kleunen, M., & Joshi, J. (2022). Data From&colon;
#'   Traces of Genetic but Not Epigenetic Adaptation in the Invasive
#'   Goldenrod _Solidago canadensis_ Despite the Absence of Population
#'   Structure. _Zenodo_. doi&colon; <a target="_blank" rel="noopener noreferrer" href="https://www.doi.org/10.5281/zenodo.6388135">10.5281/zenodo.6388135</a></center></p>
#' geometry: margin=2cm
#' output:
#'   html_document:
#'      code_folding: show
#'      keep_md: FALSE
#'      theme: flatly
#'      highlight: textmate
#'      df_print: paged
#'      toc: true
#'      toc_float: true
#' ---
#' 

#'
#'```{r setup, include = FALSE}
#'knitr::opts_chunk$set(eval=FALSE, cache=FALSE, warning=FALSE)
#'```

#' # Packages
#' <a href="#top">Back to top</a>
#+ project_packages, results='hide', message=FALSE, warning=FALSE
########### packages ...................... ####
# install.packages("name_of_package") # install necessary packages
# install knitr to save this script as html output using RStudio with Ctrl+Shift+K (Windows & Linux) or Command+Shift+K (macOS)
# install.packages("knitr") 
# getwd() # get current working directory
# setwd() # set working directory
# create folder for datasets to be stored to get this RMarkdown script running
dir.create("./data",
           showWarnings=F)
# add necessary libraries
library(pophelper)
library(gridExtra)
library(tibble)
library(ggrepel)
require(ggsn)

#' # Load data
#' <a href="#top">Back to top</a>
#+ project_load.data
########### Load data ...................... ####
source("RMarkdown_Eckert_et_al_2022_loadMolecularData.R")
# split by treatment level (CON=control; ZEB=zebularine-treated)
# AFLP
AFLP_C <- AFLP[AFLP$treatment=='CON',]
AFLP_Z <- AFLP[AFLP$treatment=='ZEB',]

# IMPORTANT PREMISE
# 1) STRUCTURE input data needs to be sorted according to population ID from 1 to 25
# 2) labeling strategy of STRUCTURE files: AFLPc_K[0-9]{1,2}_param_run_[1-8]_f
# load STRUCTURE run files
sfiles <- list.files(path=getwd(),
                     pattern="AFLPc_K[0-9]{1,2}_param_run_[1-8]_f"); sfiles
# convert q-matrix files to R qlist object
slist <- readQ(files=sfiles,
               filetype="structure"); slist # takes some seconds...
# tabulate additional columns
slist_tab <- tabulateQ(slist); slist_tab
# summarise runs
slist_sum <- summariseQ(slist_tab); slist_sum
# Evanno results
analyseQ(files=sfiles,
         exportpath="./data",
         plotruns=F)

# IMPORTANT: create file with group labels from STRUCTURE analysis (id=plant id,pop=population)
# load file with group labels
labs <- read.table("./data/Data_STRUCTURE_AFLP_labels.txt",
                   header=T,
                   sep="\t",
                   stringsAsFactors=F); labs
labs$pop <- as.character(labs$pop)
str(labs)
pops <- data.frame(Pops=as.character(labs$pop))
head(pops); str(pops)
# write cluster information to table
k2_data <- cbind(labs,slist_merged); dim(k2_data); tibble(k2_data)
# add coordinates
k2_coords <- AFLP_C.coords
k2_coords$pop <- c(1:25); k2_coords
k2_final <- merge(k2_data,
                  k2_coords,
                  by="pop",
                  all=T); k2_final
dim(k2_final)
# write table to file
write.table(k2_final,
            file="./data/Data_STRUCTURE_AFLP_k2.txt",
            row.names=F)

#' # Merge Q Data
#' <a href="#top">Back to top</a>
#+ project_MergeQ
########### Merge Q-data ................ ####
# create color palette based on Okabe & Ito (2002)
okabe_ito_cols=c("black","orange","blue","yellow")
# K=2
sfiles[c(25:32)] # extract files for all runs of K=2
K2_aligned <- alignK(slist[c(25:32)]); K2_aligned
K2_merged <- mergeQ(K2_aligned); K2_merged
K2_plot <- plotQ(qlist=K2_merged,
                 exportpath=getwd(),
                 returnplot=T,
                 basesize=14,
                 clustercol=okabe_ito_cols,
                 grplab=pops,
                 grplabsize=4,
                 ordergrp=T,
                 divgrp="Pops",
                 divcol="black",
                 showindlab=F,
                 grplabpos=0.8,
                 linepos=0.9,
                 grplabheight=2,
                 splab="K = 2",
                 sppos="left",
                 grplabspacer=-0.5,
                 subset=as.character(1:25))
grid.arrange(K2_plot$plot[[1]])
# K=4
sfiles[c(41:48)] # extract files for all runs of K=4
K4_aligned <- alignK(slist[c(41:48)]); K4_aligned
K4_merged <- mergeQ(K4_aligned); K4_merged
K4_plot <- plotQ(qlist=K4_merged,
                 exportpath=getwd(),
                 returnplot=T,
                 basesize=14,
                 clustercol=okabe_ito_cols,
                 grplab=pops,
                 grplabsize=4,
                 ordergrp=T,
                 divgrp="Pops",
                 divcol="black",
                 showindlab=F,
                 grplabpos=0.8,
                 linepos=0.9,
                 grplabheight=2,
                 splab="K = 4",
                 sppos="left",
                 grplabspacer=-0.5,
                 subset=as.character(1:25))
grid.arrange(K4_plot$plot[[1]])
# K=5
sfiles[c(49:56)] # extract files for all runs of K=5
K5_aligned <- alignK(slist[c(49:56)]); K5_aligned
K5_merged <- mergeQ(K5_aligned); K5_merged
K5_plot <- plotQ(qlist=K5_merged,
                 exportpath=getwd(),
                 returnplot=T,
                 basesize=14,
                 clustercol=okabe_ito_cols,
                 grplab=pops,
                 grplabsize=4,
                 ordergrp=T,
                 divgrp="Pops",
                 divcol="black",
                 showindlab=F,
                 grplabpos=0.8,
                 linepos=0.9,
                 grplabheight=2,
                 splab="K = 5",
                 sppos="left",
                 grplabspacer=-0.5,
                 subset=as.character(1:25))
grid.arrange(K5_plot$plot[[1]])

#' # Session info
#' <a href="#top">Back to top</a>
#+ Session.info
sessionInfo()
#' <a href="#top">Back to top</a>
######## Session info .................. ####